/**
 * Created by Kunal Nagpal on 11-12-2014.
 *  GraVITas Premier League
 *  Copyright (C) 2014  IEEE Computer Society - VIT Student Chapter <ieeecs@vit.ac.in>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
module.exports =
    [
        "short ball and a slower one, he softly pulls it to short fine leg",
        "this was jammed full outside off, looks to dig it out",
        "drifting down the leg side and nearly clipped the leg stump on the way through",
        "that's the line! The bowler bowls it on the corridor outside off and the ball shapes away late, fizzes past  the edge",
        "this one skidded through quickly and hit the back pad, looked like drifting down leg",
        "missed out, he drills it back to the bowler",
        "a bit too short and he finds cover",
        "makes a bit of room and looks to smash that over the off side and he's beaten",
        "makes a hint of room and the bowler follows him by drifting on the pads, he can only drive back to the bowler",
        "the batsman seems happy to defend",
        "missed out, this was short and he could only smack this back to the bowler",
        "can only mistime it to short midwicket",
        "doesn't give him much room as he steers it to point",
        "keeps it nice and straight, goes back and defends",
        "squares him up with beautiful away movement, this moves away late and the batsman was chasing it",
        "he fires that full outside the off stump and he looks to jam it out but misses",
        "drops a sitter! It was length ball and the batsman chips it ever so tamely to short cover, for a moment,   the fielder had it covered, don't know how that slipped out",
        "he tamely pushes it to the off side",
        "full and straying on the pads, clips the pads as he looks to flick it away",
        "this one moves away and he pokes at it, nearly edges it",
        "decent shout for an lbw? Straightens and hits him on the top flap as he stays on the back foot,   looked close though, appeal turned down",
        " tossed up and he pushes it back to the bowler",
        "he rocks back and cuts but can't beat extra cover",
        "very low and wide full toss, slips under the bat swing",
        "skidding across him from a length and he cannot do anything with it",
        "tries to launch this length ball over midwicket, inside edges onto pad",
        "cuts across the batsman from back of a length, is pushed back",
        "tries to square drive a full and widish one but is beaten",
        "well bowled, he angles it full and wide of the batsman this time",
        "sharp stop from the keeper, this was a wide away swinging full toss and he got a thick edge to it,   it was travelling but the keeper reacted in time",
        "he tries to slog to leg, and the slower one keeps very low to beat him, that was very close to leg stump too",
        "he steps out looking to go over square leg but is hit on the pad",
        "full and quicker on the pad, he tries to whip it square but misses",
        "angled flat into the pad, the batsman misses as he goes down on a knee",
        "comes down the track and flashes it straight back to the bowler",
        "lovely delivery, angled in just outside off, makes him play, and straightens and kicks past the edge",
        "slower and fuller, he taps it to extra cover",
        "tries a cut but is done in by the extra bounce",
        "tries to whack a length ball down the ground but it moves away and beats him",
        "moving away outside off, left alone",
        "flashes at a wide delivery that ws going away and misses it",
        "this does not come in and goes past the outside edge as the batsman pushes forward to defend",
        "ending around off this time, he goes on his toes and keeps it down",
        "a wide yorker, the batsman misses it",
        "full and wide once more, but fortunately for the bowler, it is driven straight to backward point",
        "a full delivery driven to mid off",
        "tries to make room and upper cut, but is beaten by the bounce on this back of a length ball",
        "cracks this overpitched ball for extra cover",
        "slower length ball on off, knocked back down the track",
        "slower outside off, flashed to backward point",
        "goes hard, but now he finds the bowler",
        "smacks a pull to midwicket",
        "overpitched outside off now, and he has slammed it straight to extra cover",
        "looks to step out, the bowler shortens it, and the batsman defends it square on off",
        "pitched up and angled into middle and leg, defended",
        "a touch fuller and square driven to backward point",
        "appeal for leg-before as he pushes forward, but this was doing too much with the angle",
        "pitched up and angled into middle and leg, defended",
        "a touch fuller and square driven to backward point",
        "goes back to punch it to the bowler",
        "full on leg again, Samson clips it straight to midwicket",
        "he tries to pull this too hard, but mishits it, couple of bounces to mid on",
        "calmly moves forward and pushes a good length ball to extra cover",
        "jumps out of the crease now, bowler shortens the length, and the batsman knocks it back",
        "comes in with the angle and is pushed down the track",
        "defends a good length ball on off",
        "mistimes a forcing stroke in front of square on the leg side",
        "tries to force this good length ball from just outside off, but turns it straight to mid on",
        "moves across to off stump, pushes forward and defends this length delivery to covers",
        "gentle length ball on the pad, nudged away",
        "beaten on the sweep",
        "now this one straightens, and almost hits the off stump, missed by inches, the batsman had no idea this time",
        "no clue about this one as it rips across him to beat a waft",
        "wants to slog this over midwicket but fails to connect to the length ball just outside off",
        "he fires the next one in, it moves away from the batsman and beats him",
        "a full ball pushed to extra cover",
        "goes back to a pitched up ball and pushes it to extra cover",
        "tries to dab this length ball to third man but it kicks sharply and beats him",
        "opens the face to this one climbing around off, finds backward point",
        "takes a step across and lets this go with the angle, he is expecting a wide call, but is not getting one",
        "bowled full at the stumps and blocked back calmly",
        "beaten on the cut, this was fullish outside off",
        "tapped to backward point",
        "goes across the this time, and the batsman misses the sweep, had his foot grounded even as the keeper took  the bails off",
        "goes after a widish one, but under edges it on the bounce to the keeper",
        "diving stop from at short extra cover saves some runs",
        "goes back to a good length, defends it late, down the track",
        "leans into a push but it goes off the inner part of the blade for midwicket to make a diving stop",
        "bowled slowly again, he pushes it to backward point, sets off, but there is no single there, and he gets back  just in time",
        "waits on this one outside off and decides to cut quite late, hits it to backward point",
        "squeezes a good length ball to covers",
        "punches this good length ball to the bowler who parries it behind him",
        "walks out to a good length ball, is too close to it, and can only knock it to point",
        "short and climbing outside off, left alone",
        "they are running away to nowhere, the batsman goes through with another punchy drive in the air,   mid off is there, and had he hit, the non striker would have been out, he had wandered that far out",
        "lunges forward and has a heave but is beaten by this pitched up ball",
        "a nothing shot, tries to belatedly guide it towards point, beaten by the pace and bounce",
        "finds the radar now, hits his favoured back of a length, and it rears up at the striker, who is fortunate  not to edge it",
        "good one, this one goes away after drawing the batsman into a forward push, beaten by some margin",
        "he tries some kind of a reverse scoop, but this is shortish and bounces past",
        "top stuff from the bowler, first he pings it into the blockhole, the batsman knocks it to his left,   and  the bowler goes flying like a goalkeeper to pouch it",
        "walks far across but fails to get bat on this delivery that goes past leg stump",
        "makes room outside leg, this one is on middle and staying a bit low, he toe-ends it to the bowler",
        "bowls it around off, the batsman tries to dab it away, but cannot get much purchase on it",
        "comes out again, the bowler pings it full into the pad, the batsman adjusts to nudge it square",
        "he comes forward and runs it to point, not getting anything for that",
        "pushes forward, and it is a bit of a leading edge down the track",
        "dances down and goes through with an elegant attempted loft down the ground, but misses the ball entirely",
        "now he bowls a conventional delivery, it is defended towards cover, non-striker wants non-existent singles,   but escapes as the throw is weak, and bowler is standing too far behind the stumps expecting a stronger one",
        "flying stop by the man at point, as the batsman guides this slowish length ball to his right",
        "it just isn't happening for the batsman at the moment, he tries to make some room and manufacture a cut,   but is beaten by some extra bounce",
        "the batsman is cramped for room this time, plays it back",
        "beaten on the pull now, it is a slower delivery, and the batsman played too early",
        "too good for him again as he fails to get bat on ball this time",
        "length ball just outside off, and the batsman plays a nothing shot, opening the face and ultimately pushing  well inside the line",
        "he walks across the stumps, but the bowler gets one to nip in and hurry on into the pads, too high, though",
        "the batsman is looking clueless at the moment against this aggresive burst from the opposition,   another  one comes in, cramps him for room and he does not help himself by hopping and getting into a tangle",
        "now this one comes in a long way after pitching, thick inside edge on to pad flap as the batsman hops again",
        "pitched up for the drive outside off, left alone",
        "beaten, as he follows this length ball which bounces and moves away sharply",
        "holds the line and zips through past the batsman from a good length outside off,   who pulls his bat inside  the line late",
        "going across him, played out towards point",
        "produces a beauty first up, bangs it in shortish, angles it in, then gets it to move away just outside off,   the batsman is off balance, he is jumping, and even as he tries to leave it half-heartedly, it pings the bat, but falls short of slip",
        "the batsman lifts his bat to let it pass",
        "super, had the batsman beaten first up, this pitches short of a length around middle and leg and moves away  as the batsman tentatively pushes at it",
        "he reverts to the line just outside off, this one goes straightish, and the batsman comes out of his crease  and lets it be",
        "that's a good ball, really full and difficult to get away",
        "a full ball on the stumps and he drills it to cover",
        "stays back and chops it to point, not quite in his hitting length",
        "drifts down the leg side and he clips it towards short fine leg",
        "bowls that full on the stumps and he digs it out back to the bowler",
        "close shout for an lbw, across the line and may have missed the stumps",
        "he looks to cut but misses",
        "plays this ball back to the bowler",
        "big swing and a miss, the frustration getting to him? Outside off and he misses it completely",
        "drives square on the front foot and backward point does well to stop it",
        "skids on the pads and he looks to work it to the leg side but the ball rolls to the off side",
        "This time, he makes him play again and he defends this to the off side",
        "bowls it straight and he stands back and defends",
        "this was still a bit short and he went back and chopped it to extra cover",
        "this was angled wider across the batsman and he flashed at it, smart bowling",
        "tucked him up for room there, he went back to defend and the ball nearly rolled over to the stumps",
        "this was full on the off stump and he pushes it wide of mid-off",
        "kept him quiet there by bowling it dead straight, on middle and skidded through, he defends",
        "Dropped! This was coming straight at his face, slower ball and the batsman was looking to drive straight and  it was chipped back at the fielder, he cupped his hands in front of his face, slipped and couldn't hang on",
        "This one just managed to evade the batsman's slashing flick and the stumps en route to the keeper",
        "full and speared in on the pads, the batsman looks to swipe it away but gets struck on the pads. No appeal,  would have gone well down leg",
        "on the pads, nudged into midwicket",
        "He changed his stance, but not the grip on his bat as he reverse swept to third man",
        "back of a good length and outside off, he slashes and misses.",
        "The batsman gets gets a life now ! It was flighted outside off and he thumps it into the covers.   The  fielder dives full length to his right and almost hand it but it popped out",
        " back of a length and he was setting up for the front foot pull, doesn't succeed",
        " charges at him but as he finds the length is a little shorter he settles for a nudge through square leg",
        " has trouble beating that man at midwicket as the bowler continues darting in length balls on the stumps",
        " shortish delivery on leg stump, worked to midwikcet",
        "fired in on the pads, the batsman can't put it away with the flick. Shakes his head",
        "comes forward and pushes at the length ball on off stump. Gets an inside edge to mid-on",
        "shortish on off stump, the batsman punches it back to the bowler",
        " pushed through quicker on off stump, he goes for the sweep but gets an inside edge",
        " slower ball accompanied by a big grunt. The batsman was on the front foot and goes for that pull again, but  the ball just scuttles underneath his bat",
        "charges down the track and the room he's made for himself allows the carve into the covers but the fielder  dives to his right and keeps it to none",
        "pitched up on middle and leg, the batsman plays across the line and is struck on the knee-roll. Big shout  from the bowler again but this time the umpire doesn't agree. It was tight",
        "a little more effort behind this delivery and the bounce beats the batsman's cut",
        "short but not quite wide enough, the batsman flat bats it down to mid-off.",
        "full and outside off, the batsman looks to blast it through the covers but mistimes it. The fielder cuts  the angle and dives to his right to keep it to none",
        "hint of inward dip to start off, the batsman negotiates it well by coming forward and presenting a straight  bat",
        "That was a brilliant piece of bowling ! He must be rewarded with a wicket soon !",
        "Defended off the front foot, the bowler is keen to give the batsman a piece of his mind.",
        "Where did that come from ? The bowler has managed to bowl an absolute beauty out of nowhere!",
        "The batsman was into the shot early, the ball drops just short of square leg. Sheepish smiles all around.",
        "That was a whisker away from off stump, dangerous leave there by the batsman",
        "What a terrible delivery, the bowler is lucky to have been let off this time",
        "And we have a comedy of errors here ! The batsman pulls away from a half hearted attempt, the ball hits the  bat nevetheless,   a needless run is called for. A better throw from point would have the non striker out nine times out of ten, but this time the ball just pops up to the man backing up, no run taken.",
        "A hint of movement, but the batsman strides forward to block.",
        "Play and a miss ! The bowler has his head in his hands.",
        "Played on the up, but the fielding captain has done his homework",
        "The intent was there, but the connection wasn't, the ball sails through to the keeper.",
        "he's struck on the front pad and he seemed pretty adjacent too! But the ball might just have gone over the  stumps.   He was walking across and the bowler responded with a slower delivery just back of a length. Deceived the batsman as it darted back in at him and his guide to third man was nowhere close to it",
        "just outside off, pushed back to the bowler.",
        "fires a low full toss on leg stump and the batsman goes for the flick a little too early, resulting in a  leading edge back to the bowler.",
        "good length ball outside off and the batsman goes for the booming drive through the covers but there is no  timing on the shot",
        "slower ball outside off and the batsman is flummoxed by it. Goes for a slog-sweep and misses",
        "searing delivery fired in down the leg side and the batsman cannot get bat to it",
        "crisply punched into the covers as he leans forward to the fuller delivery angled across him",
        "dug in short on middle, defended",
        "The batsman leaves it watchfully",
        "strides forward and defends to point.",
        "how close was that! It was a shorter ball and he looked to dab it in front of point for a quick single.   The fielder swoops on the ball and sends in the throw in one motion. The non-striker has to pull out a full-length dive as well and it saves him, just about",
        " the bowler has a giant smile on his face after executing the perfect wide yorker to keep the batsman quiet",
        "cramps up the batsman, back of length once more, squirted that away to the leg side",
        "beaten outside off, great line there, bounce as well as he drops it a touch shorter",
        "Was that low or what ? The batsman gets his bat down in time to keep that one out",
        "he was moving outside off again and the bowler follows him with a fuller delivery. The slash doesn't beat  point",
        "shimmies down the pitch but he pulls the length back and the batsman can only nudge it to square leg",
        " rock-solid forward defensive from the batsmen at the striker's end",
        "fullish on off stump, he goes forward and blocks into the covers. Searches for the single but the non-striker  says no",
        "comes down the track and carves a full and wide delivery to point",
        "skips down the track but the ball seems to stop on the pitch before reaching him. Gets hit high on the bat  as he pushes into the covers.   Fell not too far away from the fielder either",
        "outside edge off the slower ball outside off. Tries to steer it down to third man but it bounces short of  the keeper",
        "spears it in on middle and he was looking to clip to midwicket. Gets a leading edge to point."
    ];