/**
 * Created by Kunal Nagpal <kunagpal@gmail.com> on 09-02-2015.
 *  GraVITas Premier League
 *  Copyright (C) 2014  IEEE Computer Society - VIT Student Chapter <ieeecs@vit.ac.in>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
module.exports =
    [
        "",
        "short ball and a slower one, he softly pulls it to short fine leg",
        "this was jammed full outside off, looks to dig it out",
        "drifting down the leg side and nearly clipped the leg stump on the way through",
        "that's the line! The bowler bowls it on the corridor outside off and the ball shapes away late, fizzes past  the edge",
        "this one skidded through quickly and hit the back pad, looked like drifting down leg",
        "missed out, he drills it back to the bowler",
        "a bit too short and he finds cover",
        "makes a bit of room and looks to smash that over the off side and he's beaten",
        "makes a hint of room and the bowler follows him by drifting on the pads, he can only drive back to the bowler",
        "the batsman seems happy to defend",
        "missed out, this was short and he could only smack this back to the bowler",
        "can only mistime it to short midwicket",
        "doesn't give him much room as he steers it to point",
        "keeps it nice and straight, goes back and defends",
        "squares him up with beautiful away movement, this moves away late and the batsman was chasing it",
        "he fires that full outside the off stump and he looks to jam it out but misses",
        "drops a sitter! It was length ball and the batsman chips it ever so tamely to short cover, for a moment,   the fielder had it covered, don't know how that slipped out",
        "he tamely pushes it to the off side",
        "full and straying on the pads, clips the pads as he looks to flick it away",
        "this one moves away and he pokes at it, nearly edges it",
        "decent shout for an lbw? Straightens and hits him on the top flap as he stays on the back foot,   looked close though, appeal turned down",
        " tossed up and he pushes it back to the bowler",
        "he rocks back and cuts but can't beat extra cover",
        "very low and wide full toss, slips under the bat swing",
        "skidding across him from a length and he cannot do anything with it",
        "tries to launch this length ball over midwicket, inside edges onto pad",
        "cuts across the batsman from back of a length, is pushed back",
        "tries to square drive a full and widish one but is beaten",
        "well bowled, he angles it full and wide of the batsman this time",
        "sharp stop from the keeper, this was a wide away swinging full toss and he got a thick edge to it,   it was travelling but the keeper reacted in time",
        "he tries to slog to leg, and the slower one keeps very low to beat him, that was very close to leg stump too",
        "he steps out looking to go over square leg but is hit on the pad",
        "full and quicker on the pad, he tries to whip it square but misses",
        "angled flat into the pad, the batsman misses as he goes down on a knee",
        "comes down the track and flashes it straight back to the bowler",
        "lovely delivery, angled in just outside off, makes him play, and straightens and kicks past the edge",
        "slower and fuller, he taps it to extra cover",
        "tries a cut but is done in by the extra bounce",
        "tries to whack a length ball down the ground but it moves away and beats him",
        "moving away outside off, left alone",
        "flashes at a wide delivery that ws going away and misses it",
        "this does not come in and goes past the outside edge as the batsman pushes forward to defend",
        "ending around off this time, he goes on his toes and keeps it down",
        "a wide yorker, the batsman misses it",
        "full and wide once more, but fortunately for the bowler, it is driven straight to backward point",
        "a full delivery driven to mid off",
        "tries to make room and upper cut, but is beaten by the bounce on this back of a length ball",
        "cracks this overpitched ball for extra cover",
        "slower length ball on off, knocked back down the track",
        "slower outside off, flashed to backward point",
        "goes hard, but now he finds the bowler",
        "smacks a pull to midwicket",
        "overpitched outside off now, and he has slammed it straight to extra cover",
        "looks to step out, the bowler shortens it, and the batsman defends it square on off",
        "pitched up and angled into middle and leg, defended",
        "a touch fuller and square driven to backward point",
        "appeal for leg-before as he pushes forward, but this was doing too much with the angle",
        "pitched up and angled into middle and leg, defended",
        "a touch fuller and square driven to backward point",
        "goes back to punch it to the bowler",
        "full on leg again, Samson clips it straight to midwicket",
        "he tries to pull this too hard, but mishits it, couple of bounces to mid on",
        "calmly moves forward and pushes a good length ball to extra cover",
        "jumps out of the crease now, bowler shortens the length, and the batsman knocks it back",
        "comes in with the angle and is pushed down the track",
        "defends a good length ball on off",
        "mistimes a forcing stroke in front of square on the leg side",
        "tries to force this good length ball from just outside off, but turns it straight to mid on",
        "moves across to off stump, pushes forward and defends this length delivery to covers",
        "gentle length ball on the pad, nudged away",
        "beaten on the sweep",
        "now this one straightens, and almost hits the off stump, missed by inches, the batsman had no idea this time",
        "no clue about this one as it rips across him to beat a waft",
        "wants to slog this over midwicket but fails to connect to the length ball just outside off",
        "he fires the next one in, it moves away from the batsman and beats him",
        "a full ball pushed to extra cover",
        "goes back to a pitched up ball and pushes it to extra cover",
        "tries to dab this length ball to third man but it kicks sharply and beats him",
        "opens the face to this one climbing around off, finds backward point",
        "takes a step across and lets this go with the angle, he is expecting a wide call, but is not getting one",
        "bowled full at the stumps and blocked back calmly",
        "beaten on the cut, this was fullish outside off",
        "tapped to backward point",
        "goes across the this time, and the batsman misses the sweep, had his foot grounded even as the keeper took  the bails off",
        "goes after a widish one, but under edges it on the bounce to the keeper",
        "diving stop from at short extra cover saves some runs",
        "goes back to a good length, defends it late, down the track",
        "leans into a push but it goes off the inner part of the blade for midwicket to make a diving stop",
        "bowled slowly again, he pushes it to backward point, sets off, but there is no single there, and he gets back  just in time",
        "waits on this one outside off and decides to cut quite late, hits it to backward point",
        "squeezes a good length ball to covers",
        "punches this good length ball to the bowler who parries it behind him",
        "walks out to a good length ball, is too close to it, and can only knock it to point",
        "short and climbing outside off, left alone",
        "they are running away to nowhere, the batsman goes through with another punchy drive in the air,   mid off is there, and had he hit, the non striker would have been out, he had wandered that far out",
        "lunges forward and has a heave but is beaten by this pitched up ball",
        "a nothing shot, tries to belatedly guide it towards point, beaten by the pace and bounce",
        "finds the radar now, hits his favoured back of a length, and it rears up at the striker, who is fortunate  not to edge it",
        "good one, this one goes away after drawing the batsman into a forward push, beaten by some margin",
        "he tries some kind of a reverse scoop, but this is shortish and bounces past",
        "top stuff from the bowler, first he pings it into the blockhole, the batsman knocks it to his left,   and  the bowler goes flying like a goalkeeper to pouch it",
        "walks far across but fails to get bat on this delivery that goes past leg stump",
        "makes room outside leg, this one is on middle and staying a bit low, he toe-ends it to the bowler",
        "bowls it around off, the batsman tries to dab it away, but cannot get much purchase on it",
        "comes out again, the bowler pings it full into the pad, the batsman adjusts to nudge it square",
        "he comes forward and runs it to point, not getting anything for that",
        "pushes forward, and it is a bit of a leading edge down the track",
        "dances down and goes through with an elegant attempted loft down the ground, but misses the ball entirely",
        "now he bowls a conventional delivery, it is defended towards cover, non-striker wants non-existent singles,   but escapes as the throw is weak, and bowler is standing too far behind the stumps expecting a stronger one",
        "flying stop by the man at point, as the batsman guides this slowish length ball to his right",
        "it just isn't happening for the batsman at the moment, he tries to make some room and manufacture a cut,   but is beaten by some extra bounce",
        "the batsman is cramped for room this time, plays it back",
        "beaten on the pull now, it is a slower delivery, and the batsman played too early",
        "too good for him again as he fails to get bat on ball this time",
        "length ball just outside off, and the batsman plays a nothing shot, opening the face and ultimately pushing  well inside the line",
        "he walks across the stumps, but the bowler gets one to nip in and hurry on into the pads, too high, though",
        "the batsman is looking clueless at the moment against this aggresive burst from the opposition,   another  one comes in, cramps him for room and he does not help himself by hopping and getting into a tangle",
        "now this one comes in a long way after pitching, thick inside edge on to pad flap as the batsman hops again",
        "pitched up for the drive outside off, left alone",
        "beaten, as he follows this length ball which bounces and moves away sharply",
        "holds the line and zips through past the batsman from a good length outside off,   who pulls his bat inside  the line late",
        "going across him, played out towards point",
        "produces a beauty first up, bangs it in shortish, angles it in, then gets it to move away just outside off,   the batsman is off balance, he is jumping, and even as he tries to leave it half-heartedly, it pings the bat, but falls short of slip",
        "the batsman lifts his bat to let it pass",
        "super, had the batsman beaten first up, this pitches short of a length around middle and leg and moves away  as the batsman tentatively pushes at it",
        "he reverts to the line just outside off, this one goes straightish, and the batsman comes out of his crease  and lets it be",
        "that's a good ball, really full and difficult to get away",
        "a full ball on the stumps and he drills it to cover",
        "stays back and chops it to point, not quite in his hitting length",
        "drifts down the leg side and he clips it towards short fine leg",
        "bowls that full on the stumps and he digs it out back to the bowler",
        "close shout for an lbw, across the line and may have missed the stumps",
        "he looks to cut but misses",
        "plays this ball back to the bowler",
        "big swing and a miss, the frustration getting to him? Outside off and he misses it completely",
        "drives square on the front foot and backward point does well to stop it",
        "skids on the pads and he looks to work it to the leg side but the ball rolls to the off side",
        "This time, he makes him play again and he defends this to the off side",
        "bowls it straight and he stands back and defends",
        "this was still a bit short and he went back and chopped it to extra cover",
        "this was angled wider across the batsman and he flashed at it, smart bowling",
        "tucked him up for room there, he went back to defend and the ball nearly rolled over to the stumps",
        "this was full on the off stump and he pushes it wide of mid-off",
        "kept him quiet there by bowling it dead straight, on middle and skidded through, he defends",
        "Dropped! This was coming straight at his face, slower ball and the batsman was looking to drive straight and  it was chipped back at the fielder, he cupped his hands in front of his face, slipped and couldn't hang on",
        "This one just managed to evade the batsman's slashing flick and the stumps en route to the keeper",
        "full and speared in on the pads, the batsman looks to swipe it away but gets struck on the pads. No appeal,  would have gone well down leg",
        "on the pads, nudged into midwicket",
        "He changed his stance, but not the grip on his bat as he reverse swept to third man",
        "back of a good length and outside off, he slashes and misses.",
        "The batsman gets gets a life now ! It was flighted outside off and he thumps it into the covers.   The  fielder dives full length to his right and almost hand it but it popped out",
        " back of a length and he was setting up for the front foot pull, doesn't succeed",
        " charges at him but as he finds the length is a little shorter he settles for a nudge through square leg",
        " has trouble beating that man at midwicket as the bowler continues darting in length balls on the stumps",
        " shortish delivery on leg stump, worked to midwikcet",
        "fired in on the pads, the batsman can't put it away with the flick. Shakes his head",
        "comes forward and pushes at the length ball on off stump. Gets an inside edge to mid-on",
        "shortish on off stump, the batsman punches it back to the bowler",
        " pushed through quicker on off stump, he goes for the sweep but gets an inside edge",
        " slower ball accompanied by a big grunt. The batsman was on the front foot and goes for that pull again, but  the ball just scuttles underneath his bat",
        "charges down the track and the room he's made for himself allows the carve into the covers but the fielder  dives to his right and keeps it to none",
        "pitched up on middle and leg, the batsman plays across the line and is struck on the knee-roll. Big shout  from the bowler again but this time the umpire doesn't agree. It was tight",
        "a little more effort behind this delivery and the bounce beats the batsman's cut",
        "short but not quite wide enough, the batsman flat bats it down to mid-off.",
        "full and outside off, the batsman looks to blast it through the covers but mistimes it. The fielder cuts  the angle and dives to his right to keep it to none",
        "hint of inward dip to start off, the batsman negotiates it well by coming forward and presenting a straight  bat",
        "That was a brilliant piece of bowling ! He must be rewarded with a wicket soon !",
        "Defended off the front foot, the bowler is keen to give the batsman a piece of his mind.",
        "Where did that come from ? The bowler has managed to bowl an absolute beauty out of nowhere!",
        "The batsman was into the shot early, the ball drops just short of square leg. Sheepish smiles all around.",
        "That was a whisker away from off stump, dangerous leave there by the batsman",
        "What a terrible delivery, the bowler is lucky to have been let off this time",
        "And we have a comedy of errors here ! The batsman pulls away from a half hearted attempt, the ball hits the  bat nevetheless,   a needless run is called for. A better throw from point would have the non striker out nine times out of ten, but this time the ball just pops up to the man backing up, no run taken.",
        "A hint of movement, but the batsman strides forward to block.",
        "Play and a miss ! The bowler has his head in his hands.",
        "Played on the up, but the fielding captain has done his homework",
        "The intent was there, but the connection wasn't, the ball sails through to the keeper.",
        "he's struck on the front pad and he seemed pretty adjacent too! But the ball might just have gone over the  stumps.   He was walking across and the bowler responded with a slower delivery just back of a length. Deceived the batsman as it darted back in at him and his guide to third man was nowhere close to it",
        "just outside off, pushed back to the bowler.",
        "fires a low full toss on leg stump and the batsman goes for the flick a little too early, resulting in a  leading edge back to the bowler.",
        "good length ball outside off and the batsman goes for the booming drive through the covers but there is no  timing on the shot",
        "slower ball outside off and the batsman is flummoxed by it. Goes for a slog-sweep and misses",
        "searing delivery fired in down the leg side and the batsman cannot get bat to it",
        "crisply punched into the covers as he leans forward to the fuller delivery angled across him",
        "dug in short on middle, defended",
        "The batsman leaves it watchfully",
        "strides forward and defends to point.",
        "how close was that! It was a shorter ball and he looked to dab it in front of point for a quick single.   The fielder swoops on the ball and sends in the throw in one motion. The non-striker has to pull out a full-length dive as well and it saves him, just about",
        " the bowler has a giant smile on his face after executing the perfect wide yorker to keep the batsman quiet",
        "cramps up the batsman, back of length once more, squirted that away to the leg side",
        "beaten outside off, great line there, bounce as well as he drops it a touch shorter",
        "Was that low or what ? The batsman gets his bat down in time to keep that one out",
        "he was moving outside off again and the bowler follows him with a fuller delivery. The slash doesn't beat  point",
        "shimmies down the pitch but he pulls the length back and the batsman can only nudge it to square leg",
        " rock-solid forward defensive from the batsmen at the striker's end",
        "fullish on off stump, he goes forward and blocks into the covers. Searches for the single but the non-striker  says no",
        "comes down the track and carves a full and wide delivery to point",
        "skips down the track but the ball seems to stop on the pitch before reaching him. Gets hit high on the bat  as he pushes into the covers.   Fell not too far away from the fielder either",
        "outside edge off the slower ball outside off. Tries to steer it down to third man but it bounces short of  the keeper",
        "spears it in on middle and he was looking to clip to midwicket. Gets a leading edge to point.",
        "kept to a good length on middle, the batsman goes back and blocks",
        "drifting onto the pads, he looks to nurdle it around the corner but doesn't connect. Optimistic leg before appeal ensues",
        "full and creeping in at him, he adjusts for it as he clips to mid-on. Kept his front foot out of the way of the bat",
        "closes the face of the bat too early on this short of a length delivery, gets the leading edge to point",
        "fullish and around off stump, pushes down the ground to mid-off",
        "seeks the blockhole and finds it just about, the batsman digs it out",
        "slower short ball and the batsman was completely fooled. It was the offcutter and it bounces over the stumps.",
        "good length ball just outside off, the batsman comes forward and hits it on the up into the covers",
        "back of a length on off stump, the batsman guides it to point and has to send his partner back as he sees the fielder race up to the ball",
        "good length ball on and around middle, the batsman is stuck in the crease as he looks to defend",
        "full toss on leg stump, he can't get it past square leg. Lucky escape",
        "skips down the track but the bowler has pulled all the pace off it and keeps the batsman honest",
        "shortish and outside off, the batsman is back and punches to point",
        "dropped! It was a massive edge and so a pretty sizeable deflection. The extra bounce from this delivery doesn't allow for the punch through the covers that the batsman was looking for. That needed to have been a reflex catch",
        " shortish and outside off, he backs away and cuts through the covers",
        "on off stump, he defends",
        "holds in the pitch a little more as he looks to nudge it through midwicket. Lobs up in the air back to the bowler but he can't get around the batsman quick enough to have a chance",
        "shortish and on middle, he exhibits a short-armed pull to square leg",
        "pushed through short and on off stump, the batsman punches towards extra",
        "he skips down the track but gets struck on the pads as he was looking to flick",
        "a little more pitched up on leg stump, the batsman blocks",
        "cramped for room as he tucks the back of a length ball to midwicket",
        "just a little more bounce than the batsman thought. He was on the front foot and looking to lash it through the covers but is beaten",
        "dug in short. The batsman has to wait and even when he pulls he can't beat short fine leg",
        "good length and on middle and off, the batsman stays back and steers it to point",
        "fullish and outside off, the batsman can't beat point again",
        "ull and on the pads, the batsman can't pick it away",
        "he's keeping things tight here. The batsman wants to break free as he backs away to cut the slower, length ball. Point is in the way again",
        "gets this into the blockhole on off stump, the batsman pushes to mid-off.",
        "fullish on off stump, the batsman dabs behind point. Pace off the ball is not allowing the batsmen to time the ball",
        "low full toss outside off, the batsman bunts it to short cover",
        "he's pulling the over back big time. The batsman was setting up outside leg and he followed him with a very full delivery. Goes for the sweep but is a little slow on it",
        "this time the ball sneaks through his legs while he was looking to slog sweep as a right hander.",
        "backs away and the bowler fires it wide outside off, it's too far away for the batsman to connect and just inside the wide line too.",
        "the away shape has him worried. He was looking to defend first, then wants to pull his bat away and ends up under edging it to the keeper",
        "just short of a good length on off stump, the batsman blocks",
        "back of a length and outside off, the batsman presents an open face to point",
        "a little away shape outside off, the batsman is squared up as he blocks into the covers",
        "just back of a good length on off stump, the batsman is kept to a block down the pitch",
        "length ball outside off, he looks to cart it over midwicket but miscues it",
        "moves outside leg and creams this flighted ball to mid-off",
        "shortish and outside off, he steers it to point and forgets it's Warner down there. Swoops on the ball and forces the batsman to back track.",
        "shortish on middle, the batsman was looking for it to be a little more shorter and gets a bit of leading edge. Doesn't carry to the bowler",
        "not quite short enough to cut there. Cross-seamer doesn't rise as high and sneaks under the bat. The bowler flashes a smirk at the striker",
        "flat on middle and the batsman was backing away and cuts to cover",
        "that's more like it. Tossed it up on off stump and keeps the batsman to a defensive",
        "slower through the air and flighted on off stump, the batsman comes forward and blocks with an open face",
        "shortish and outside off, cut towards point",
        "lovely delivery just outside off, the batsman comes forward and blocks",
        "outside off, driven into the covers",
        "there's the magic ball, moves away from the batsman's cut shot and he's not pleased that it wasn't a wide. Tight call that",
        "that's a lovely ball. Makes the batsman waft at a ball pitched on a good length and in the corridor. Soundly beaten",
        "lunges forward to block the delivery outside off",
        "a couple of steps down the track to counter the movement on this tossed up delivery and block into the on side",
        "squares him up on off stump with one that is flat and pushed through on off stump",
        "his one grips the pitch and moves across him to hit his back thigh. Mild appeal but this was way too high",
        "slower ball, into the block hole. the batsman punches it down the ground but the fielder's reach is long enough to pull it down",
        "Drifts it in on middle and enjoys some help from the pitch as it rips right across his outside edge",
        "skips down the track but can't beat the man at extra cover. Crowd thinks it's a catch and goes up",
        "comes down the track but he has pulled the length back and KP has to block",
        "leading edge, but it doesn't carry to the bowler. This was drifted into the pads and he closed the face a little too early in his search for midwicket",
        "deceived by the off-cutter. It was length too and in the slot to be smacked over the top but his swing misses",
        "tossed up just outside off. He mistimes a drive into the covers",
        "back of a length, he swings off his feet and misses extravagantly outside off. Shades of Stick Cricket there.",
        "it's on a good length close to off stump, and the batsman presses forward to defend towards point",
        "full outward delivery, a bit of width outside off. He stretches out to drive, can't beat cover point",
        "back of a length, angling into off stump. He hops across and tucks it down towards midwicket",
        "lbw appeal as the batsman pushes his hands in front of his body to drive down the ground, feet going nowhere, and the inward angle cayuses the ball to hit his pad. May have got an inside-edge on that",
        "length ball outside off, left alone, rare outcome for a length ball in this format of the game",
        "length ball on off and middle. He presses forward to block it back to the bowler",
        "length ball on off stump, defended back to the bowler",
        "this one isn't nearly as full as the batsman expected. He gets a half-stride out and plays a punchy drive to cover point",
        "very full, a bit of width outside off, as he jams his bat down and jabs it away firmly but can't beat cover point",
        "beauty. On a good length, straightening a touch on a fifth-stump line. The batsman pushes at it and the ball beats his outside edge",
        "full on middle and leg, blocked into the on side",
        "shortish outside off, slapped hard but straight to point",
        "that kind of bounce would make any ast bowler proud. Wasn't particularly short, outside off,and he was actually on the front foot. Took off, and he could only tuck his bat behind his pad and leave it alone",
        "length ball, angling across towards middle and off. He defends into the leg side",
        "fullish, angling away from off stump, left alone",
        "a brilliant ball! Angling away from the striker, on the perfect length to entice the drive. Feet were going nowhere, and the bat swished through the wrong line",
        "along the same angle but a touch shorter this time, the batsman shoulders arms",
        "quickish length ball, darts in towards off stump, blocked back to the bowler",
        "short and wide, no movement, slapped firmly and the fielder dives to his right and makes an excellent stop at point. Takes a moment to turn to release the throw to the bowler's end, since he has to transfer the ball to his left hand, and the batsman, who had hared out of his crease, returns home safely",
        "floated up on middle stump, turns like a legbreak. He didn't pick that, got his front pad in the way as he came forward to defend. Polite appeal for lbw, that was clearly going down leg",
        "quicker, closer to off and middle. The batsman has to bring his bat down in a hurry to defend",
        "fullish on middle and off, defended nervously towards mid-off, no footwork at all",
        "again, that beautiful length. Pitches on off, continues to go away with the angle, and he plays and misses, looking for the drive through mid-off",
        "length ball on middle stump, blocked back towards the bowler",
        "floated up full on off stump, the batsman gets forward to block into the on side",
        "length ball on off stump. Stays on the back foot, it keeps a bit low, and he jams his bat down in a hurry to poke it away towards point",
        "fuller now, on middle stump, blocked back towards the bowler",
        "length ball outside off. Comes forward and steers it away towards third man",
        "shortish, angling into the body. Doesn't get up as high as the batsman expected, and he was also through the pull a little too early, hits him on the stomach",
        "short and wide, again a bit of low bounce. Looks to cut, the ball sneaks under his bat and bounces through to the fielder",
        "length ball floated across Anderson, who steps back, makes a bit of room, and slaps it towards cover",
        "length ball on off stump, stays leg-side of the ball and carves it towards point",
        "slower ball on the pads, flicked straight to midwicket",
        "angling across, had to fetch the pull from outside off, and couldn't put bat to ball",
        "angling in towards middle and leg, the angle opened up his feet, and then it moved away sharply, beat the outside edge of his prodding bat, and missed off stump",
        "loopy delivery outside off, flat-bat drive to short extra cover",
        "back of a length outside off, dabbed to backward point",
        "full on off stump, blocked back towards the bowler",
        "down the track, drives hard to cover point",
        "dropped. Down the track comes the batsman, swings wildly across the line. This one's the mystery ball, and the edge pops straight out of the keeper's gloves",
        "fired in again, straighter this time, driven down to long-onflat and full outside off, looks for the inside-out drive, hits it hard and straight to the bowler",
        "full, in the blockhole, following the batsman as he clears his leg to hit over the leg side, smacks him on the foot",
        "shorter now, digs it in, gets it up to shoulder height, in that awkward area outside off, can't connect with the pull",
        "short of a length, outside off, slight shape away, defended with an open face",
        "this time, the away movement beats the defensive prod. The bowler looks on.",
        "this one starts around middle and off, and shapes away towards off. The batsman defends towards mid-on.",
        "short of a length, on off, punched to mid-off. Another dot",
        "and he has broken his bat!. That will teach him to charge at him. He jumps out of the crease, looks to hit hard, but is left only with his handle in the hand as the ball hits the shoulder of it",
        "gets a leading edge this ball but it doesn't carry to mid-off",
        "short of a length, no room, defended to mid-off",
        "dropped. The hits just don't stop. This is short of a length, on off, he opens the face as it angles across him, edges it low to the fielder's left, but he can't hold on despite the dive",
        "good length this time, angled across. Plays for the swing, looking to push towards mid-off, but it holds its line and beats his outside edge",
        "his feet were going nowhere as he poked at it, looking to play into the covers, and it curled in sharply and beat his inside edg",
        "down the track, heaves across the line looking to go over midwicket. The ball was slanting away from him all the time and he was nowhere near connecting",
        "back of a length, a bit of swing in to cramp him for room. Stays leg-side of the ball and bunts it towards backward point",
        "short and wide, slapped away but can't beat the diving man at cover",
        "Mr batsman, what are you doing? Didn't have too much idea of what this ball was going to do. It was on a good length, around off stump, and he poked at it with an open-faced, angled bat, playing for swing. Kept going with the angle and narrowly beat his inside edge",
        "short outside off, doesn't come on. Looks to cut, ends up hitting too early, dragging it off the bottom of his bat to cover",
        "length ball angled across, steered to short third man",
        "length ball on middle and leg, looks to tuck it into the leg side, hits it too close to the bowler",
        "flat, angled across towards off stump. Looks to make room to cut, can only chop it down feebly into the off side",
        "full on middle and leg, punched back to the bowler",
        "back of a length on off stump, punched into the covers",
        "slower ball on middle and leg, checks his attempted clip to make sure it drops short of midwicket",
        "full-toss outside off. The batsman goes hard at the drive, ends up playing down the wrong line. Outside edge, but it bounces down on its way to the keeper",
        "shortish outside off, chopped towards point",
        "full outside off, driven back firmly to the bowler",
        "back of a length outside off, dabbed away towards short third man",
        "back of a length outside off, punched off the back foot. The fielder dives to his right from backward point to stop it",
        "fullish, a bit of swerve from middle to off. Defends solidly into the off side",
        "Starts from a slightly shorter length, wider outside off, plays and misses, looking to push it into the covers",
        "full and wide, slapped firmly to the diver at point",
        "angling down leg. Goes for the hook, doesn't connect. Not given wide, even though there was an argument for it both in terms of line and height",
        "full and wide. Goes for an extravagant drive, plays and misses",
        "hits him flush on the side of the helmet as he swivels round to try and hook",
        "slower short ball outside off, fails to connect with the pull",
        "beats the inside edge as it jags back in. Headed down leg",
        "this is closer to off, gives him less room, and the batsman defends it back to him",
        "short of a length, wide on the crease, angling across him, defended with an open face",
        "Full, outside off, holds the line a touch, and beats the outside edge on the big attempted drive",
        "and he gets it to hold its line from wide on the crease, beating the edge. That's good bowling, and the batsman is struggling immediately",
        "solid front-foot defensive.",
        "short of a length, on off, angles away, beats the tentative push from Raina. The captain belts out an appeal for a catch, but he is the only one going up",
        "short of a length, just outside off, defended towards cover",
        "full, on off, the batsman is caught deep in the crease, perhaps expecting a bouncer. Pushes in front of his body. To mid-off",
        "hit powerfully down the ground, but straight to mid-off",
        "short of a length, wide delivery, he shuffles across, but ends up getting too close to it. Ends up pushing it straight to cover",
        "on off, Smith plays for movement, but the ball doesn't. Hits the inside half of the bat",
        "fired in, on a length, no turn, no room, hits his pad. Headed down leg, though",
        "Is he dropped? Heard a sound as this one passed the bat. The keeper hasn't collected this cleanly. No replays",
        "doesn't pick it, is beaten on the inside edge, but the ball is headed down leg",
        "stays back to a flat one, punches it, but can't beat point",
        "length ball, on off, no turn, defended to leg",
        "gets extra bounce, hits the splice of the bat as the batsman defends. His head rocks back too",
        "outside off, flicks this back to the non striker's end",
        "the front-of-the-hand quick delivery. Pretty accurate. The batsman hasn't seen this early enough to be able to play a productive shot. Finds midwicket",
        "flat length ball, punched to extra cover, Another dot, and the crowd gets restless",
        "stays back to a length-ball offbreak, is cramped for room, and punches it straight to cover",
        "lighted this time, on off, it turns back in to cramp him up again, ekes out another dot",
        "down the wicket, not quite to the pitch of the ball, and the crowd gets restless with this dot",
        "sees him come down the wicket, and bowls that side of the hand. Beats him in and hits his pad",
        "backs away this time, but Mishra slows it down and bowls a lovely loopy legbreak to beat the outside edge",
        "short of a length, no room, defended with an open face. A dot",
        "short of a length, holds its line outside off, he shuffles across to defend. Just gets too close to the line of the ball to be able to work it for one",
        "short ball, an effort ball, hurries him into the pull, hits the bat as opposed to the bat hitting the ball. A decent over.",
        "fires this one as the striker shimmies down. No room. Hit back to the bowler",
        "quick ball, a dot as he pushes this straight to cover",
        "just outside off, defended in front of the body",
        "Quick, on a length, no room. Defended back to him",
        "pressure telling on the striker here. Looks for a wide slog. That's not him. Wild slogging is not his game. The ball is in SJT, he is swinging in GDN. Beaten by a length ball",
        "short of a length, pretty straight, defended. This is a superb demonstration of disciplined bowling",
        "short of a length, he looks to manufacture a pull. The ball is nearly not short enough. He can't get this off the square",
        "skiddy quick short ball, late into the pull. He seems to have of late made it a habit to sit back and wait for the bad balls, might have to hit the good ones here",
        "short of a length, slower ball, his timing is off, and he has hit it straight to mid-off",
        "full and straight this time, and he has found midwicket. Dots galore",
        "sharp bounce, too quick for a pull, is beaten over his left shoulder. Not given out as they put in a half shout, but that's a dot ball anyway",
        "beats his attempt to drive a length ball",
        "short of a length, again some shape back in, pushed to cover. No room",
        "shape back in from the bowler, he defends it in front of off",
        "pretty straight, no room, defended back to him",
        "down the wicket again, this time the swing eats his inside edge and hits his pad. he is down the wicket so there is no shout for lbw",
        "uppish as he drives hard at a length ball that doesn't quite come on. Bounces just short of mid-on",
        "this time he keeps it along the carpet, and finds mid-off",
        "looks to shuffle all the way across and try the paddle over fine leg, but the bowler keeps going across with him, and he plays it into his own body",
        "comes from a bit of a slog. This shot is a reaction to the field placement. Gets an inside edge to mid-on",
        "he looks at the third man, but the bowler is too close too his body to let him open the face. Hits his glove after cramping him up",
        "short of a length, no room, punched away, but straight to backward point",
        "wide length ball, he drives on the up, but can't beat point",
        "works this to leg from just outside off, finds midwicket this time",
        "slower ball, swings wildly, and is beaten by the movement away",
        "looks to pull, times it well, but finds midwicket",
        "backs away, the bowler bowls outside off, and the extra bounce beats his cut",
        "slightly off pace as makes room again, and he beats him for pace",
        "lovely bowling. The batsman is shaping up for a slog, the bowler bowls slower through the air, a traditional delivery, and he lets it go at the last moment. Misses the off stump by a whisker",
        "short of a length, on off, stops on him, defended to off",
        "short and wide, but he has created distance as the striker is backing away. The cut is not timed well, and finds point",
        "short of a length, just outside off, beats the cut with extra bounce",
        "stays back to punch a length ball to backward point. The striker sets off for a run, is slow to come back, but has made sure he is back in by the time the keeper flicks one into the stumps",
        "backs away and looks to pull, but this ball doesn't quite come on and beats him for pace",
        "walks down at him, the bowler digs it in, draws some bounce, beats his cut",
        "gives him the charge, the bowler slows it down, the batsman recovers well to play the defensive shot",
        "flicked to leg, this time the fielder fields well this time at short midwicket",
        "looks to make room and cut, but is beaten by a skiddy short ball",
        "backs away again, the bowler pushes one outside off, and beats his attempt to cut. Seems to be having some issues out there.",
        "full, angling across, goes for the cover-drive, and is beaten by the angle",
        "length ball outside off, gets extra bounce, beats the edge as he looks to push",
        "short of a length, angling away, beats this open face",
        "smart bowling. The batsman has been backing away, the bowler follows him, cramps him up, draws a dot",
        "slower one, wide outside off too, draws him wide, the batsman defends",
        "yorker from out of nowhere!. Lovely delivery. Looking to open up the leg side, but the yorker gives him nothing. The striker digs it out, but turns down the single",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ];