/**
 * Created by Kunal Nagpal <kunagpal@gmail.com> on 09-02-2015.
 *  GraVITas Premier League
 *  Copyright (C) 2014  IEEE Computer Society - VIT Student Chapter <ieeecs@vit.ac.in>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
module.exports =
    [
        "",
        "that's the best of the lot! Overpitched outside off and he has come down on it with a straight bat and blitzed it  through the covers. Just skims away",
        "and he celebrates that stroke with a bit of cheek. It was shortish and on off stump, the batsman waited and waited  and chopped it so fine to the third man boundary",
        "miss it once, my fault. Tempt me again, I'll whack you to the square leg boundary. Full toss angling into the pads,  the batsman finds release with an efficient flick.",
        "Half-tracker with width and the batsman has thumped it through point ",
        "one-bounce four behind point! The bowler is offering freebies and he is accepting them gleefully. Shorter and wider  than the previous one in the over and the batsman does not hold back with the cut",
        "do not bowl there to him. Short and wide and he lashes it through point. Too well hit for the fielder inside the  circle",
        "this time it's short and wide. The batsman knows there is no third man and cuts it away to the boundary. Simply done",
        "he's thrown caution to the winds and his risk comes off. Mid-off was up and he launches the a length ball over his  head. Hadn't timed it anywhere near well and the bat face opened on impact too",
        "shortish and just a shade outside off, the batsman goes back in his crease and punches it in front of point with an  open face. Pierces the gap and the timing takes care of the rest",
        "width on offer and he has lashed it over the head of cover. Wasn't really all that short but it's a pretty true  pitch with the new ball still in operation and the batsman trusted the pace and bounce and hit through the line",
        "The batsman goes back and picks it away. A fielder chases after it and tries to pull it back gingerly. Doesn't succeed  the first time and his slide has pushed the boundary rope back and on the second touch, his feet were beyond where the advertising skirtings were and that's a four",
        "he bowls it full and wide and for someone like him, it's a freebee.. It's clobbered over mid-off",
        "gets a fuller delivery and it provides a release as the batsman thumps it over cover for a four",
        "poor ball from the bowler.. this is a full toss and a high one.. the batsman smashes it over midwicket with ease",
        "he looks to make room, but that's a bluff.. The bowler fires it on his pads and all the batsman has to do is to get  some bat on it.. he flicks it to deep backward square leg boundary",
        "this is even better.. just punches it through the same gap again.. just timing and a bit of placement..",
        "beautiful! He leans forward and uses his wrists to punch this with precision in the gap at extra cover",
        "pace or no pace, spin or no spin, this guy plays his own game.. He gets a back of length delivery and whacks it over  midwicket",
        "slower delivery outside off, the batsman looked to push it towards point but gets a useful little under edge through  the vacant slip region..",
        "who doesn't love a bit of medium pace.! This batsman certainly does.. he whacks this back of length delivery with a  lot of authority to deep midwicket boundary",
        "length delivery and he is taking some toll on this bowling now.. he swings across the line and gets enough bat on it  to pick up a boundary over wide mid on",
        "he is growing in confidence now.. arches back and ramps the short of length delivery over the slip fielder.. Wonderful shot by the batsman",
        "He moves to the leg side, gets a fuller delivery that he thumps over the bowler's head.. one bounce and four..",
        "there is a slip in place but this one flies between the keeper and that fielder.. He was moving towards the leg side  and is surprised as this thick outside edge flies quickly past him",
        "what timing on that one.. He was opening his stance, the bowler followed him with a length ball, he just flicks him  over square leg and that races quickly...",
        "manages to get his swing down in time.. not the best of timing behind that, but it clears mid-on",
        "fuller length delivery outside off, the batsman reaches out and slices it over point to find the boundary. Doesn't  move his feet much, just throws his bat at that",
        "short and wide, slapped hard through the crowded point region.. the fielder flew to his left, but that was spanked.. no chance for anyone",
        "this is full and wide outside off and guess what the batsman does.. the batsman sweeps him from there and past midwicket for a boundary.. Extraordinary shot",
        "No chance for the fielder this time as this half-volley is thumped between extra cover and him this time",
        "what has the cover fielder done there! The batsman drives it beautifully, but this just spins away from the fielder..  Can't blame him for that.",
        "now there is some power on this shot! He moves a little to the leg side and drives it all along the ground, between  the bowler and the man at mid-off",
        "what a shot that was! There is absolutely no room on this short of length delivery, but he arches back and not only  manages to create room, but also times it perfectly behind point to pick up a boundary",
        "that was not too far from the mid-on fielder! The batsman punches this through the line and in the air and although  it looks to be a good shot in the end, a little to the right and that would have gone straight to mid-on",
        "short and wide, he is a decent batsman and he is not going to miss out on these ones.. he arches back and punches  it over point for a boundary",
        "rank long hop and the batsman has pulled it with the greatest authority",
        "short ball and he's carted it away behind square. Pulled that with considerable disdain",
        "sliding down leg and he has glanced it quite fine. A fielder runs across but mistimes the slide. The ball sneaks in  through his legs and into the boundary",
        "and he plays with the field by getting down the track, taking the ball on the full and creaming it through extra  cover",
        "great stroke! There were two men square on the off side but the batsman has threaded it through them. Went back and  across and timed the punch brilliantly",
        "gets the ball to curl away outside off, a thick outside edge as the bat pokes at it, past the slip for four, too  fine for third man",
        "length ball is whipped away towards the square leg innings, again the line is on the legs, the batsman capitalises",
        "outside edge and off it flies to the third man boundary. Full and sliding across the batsman, the batsman  shuffles  across and swings. Gets lucky",
        "short ball and he pounces on it. Let one go earlier in the over but this time he puts a lot more muscle into the  shot. And found the gap between long-on and midwicket",
        "there's some aggression. Lashes it inside out over the cover field. Made room and opened up his stance to place it  in the gap",
        "he glances it to the left of short fine leg and it has enough to skim off to the boundary. The bowler is angry with  his poor line",
        "this time he goes aerial. It was fullish on off stump, but he stayed put to make sure his arms had enough room to  swing clean through the line. The advertising boards at long-off takes a battering.",
        "low full toss on off stump, the batsman plants his front leg down the pitch and drills it to the long-off boundary.  There was no stopping that",
        "Late cuts a back of a length ball from off stump and beats short third man",
        "no trouble despite the lack of room. It has to be on middle to keep him quiet and this was down leg stump and the  batsman has pulverized it to the long leg boundary",
        "no trouble timing that one. Again when there is width on offer, he looks imperious. Sinks down to reach the almost  wide yorker and squeezes it through point",
        "that was clean! Invited the batsman on the front foot and was also offering enough room for him to exploit. A simple  extension of the arms sends it scurrying through the cover field",
        "slower one outside off, he moves outside leg and smashes it past extra cover's dive",
        "over midwicket, attacks a length delivery from outside off and crashes it one bounce over the rope",
        "succeeds this time, another one gets up, not as much as the previous one, but the batsman is ready and cuts it high  over point",
        "gets some width and slaps the length delivery in the air and wide of extra cover",
        "down the pads this time and he sends it wide of short fine leg",
        "this was fuller, going across, providing him some room to lean forward and stroke it between extra cover and mid  off",
        "starts with a very high full toss, the batsman swings hard, gets a top edge that flies over short third man, not  called a no-ball for height, the bowler was lucky there",
        "the batsman jabs bat down on it, third man is square and has little chance with this",
        "tries a full and wide one, the batsman reaches for it and coolly lifts it into the straight boundary",
        "incredible hitting this, reverse sweep now, bowled full and quick into the legs, but the batsman is quick enough to  set himself up to force it high over point",
        "he skips out, and lifts it over midwicket, right in the gap, long on has no chance",
        "full down the pad with fine leg up, the batsman swings it hard and almost gets six",
        "that will go in the gap between point and short third man, a wide yorker, the batsman squeezes it out and splits  the gap",
        "a chance, the fielder in fact pulled out here at long as the batsman lofted this to his left, was possibly blinded  by the lights",
        "the batsman lunges on a knee and sweeps it very cleanly over the man",
        "fine leg is up, the bowler sends in a full rocket on the pads, the batsman gives it direction over the fielder with  a stylish, wristy flick",
        "a slower ball gets the batsman going, he has smacked it over midwicket",
        "pitches this up around off, and the batsman slams it with disdain over mid off",
        "straightening down the leg side and the batsman has all the time in the world to pull hard through square leg this  time",
        "tossed up on middle and leg and he slogs him over midwicket",
        "nicely played, the keeper was up, a hint of width, no slip and he gently steered this down to third man",
        "that was a gift, friendly full toss on the pads, all he had to do was shuffle slightly and work it wide of the keeper",
        "crashed that past the gap! This was on a good length wide outside off, slapped that wide if backward point",
        "lovely use of the wrists! This was a half volley on the stumps, shuffles across the stumps, works the wrists and  places it wide of midwicket",
        "drops it short, the batsman lifts that on the up, good contact to launch that over cover, a couple of bounces before  reaching the boundary",
        " makes room and caves a full ball over point to finish the innings with a boundary",
        "falls inches short of the rope, this was too short and wide outside off, the batsman hops and upper cuts it down to  third man, a little more power and it would have gone all the way",
        "That was smashed with such force and the bowler did well to get his head out of the way, full ball and the batsman  made room and smashed that down the ground",
        "this time he fires it full on the stumps, the batsman drives firmly wide of extra cover, the field was up",
        "too good for the boundary rider! This was too full and wide outside off, the batsman shuffled a long way to meet the  ball, placed wide of cover and the sweeper couldn't stop it",
        "strays down leg, fine leg leg was up, he sweeps fine and it's an easy boundary",
        "picks the vacant area, this was drifting on the pads, the batsman shuffled across early and neatly chipped it over  short fine leg",
        "this was dropped fractionally short, he read the length early and pulled him flat over square leg, one bounce and  over",
        "this was pitched up wide outside off, in the hitting zone, lofts through the line and clears cover, long-on cannot  cut it off",
        "invites the batsman to use his feet, comes down the pitch and lofts him over mid-off",
        "sped away quickly, this was too full and wide outside off, the batsman gets across and smashes it along the turf  wide of cover",
        "this was the right length for the batsman to pull, length ball a touch wide outside off, he fetches that and pulls  along the ground wide of midwicket",
        "out of nowhere, he has connected with a scoop, he goes outside off, bends the knee and turns this length ball to the  fine leg rope",
        "swings at a full delivery, and a thick inside edge runs fine down the leg side",
        "opens the face and drives through the covers for four more, he is toying with the field",
        "there is no width here, full and on middle stump, but the batsman has opened the face and timed it in the gap past  extra cover",
        "third man is up, this is short and wide, and he hops to cut it miles over the man",
        "this time he goes way in front of square, dragging the full delivery over the infield, no chance for the sweeper",
        "reverse sweep that clears point very comfortably",
        "he sets himself up for the reverse sweep even as the bowler is about to release the ball, and connects the low full  toss to beat short third man",
        "he goes over mid on, goes back and to the leg side, and swings it over the infield",
        "played with lots of aggression, width outside off, and he cuts hard behind point",
        "the bowler staying wide outside off and the batsman going off this time, a full toss is lifted easily over extra  cover",
        "a wide yorker now, but in vain, third man is up and he squeezes it wide of the fielder",
        "a full toss outside off is smashed back down the ground, and beats long on and long off",
        "full into the pad, he shuffles a bit, and manages to run it fine",
        "he uses his reach, reaches the pitch of this one outside off and swats it straight down the ground",
        "picks the gap at deep midwicket, this is full and angled in, and he clears front leg to swing it away",
        " lofts this pitched up ball over extra cover now, stretches forward and powers it away",
        "he carts this full delivery to long who drops it, and it runs behind him into the boundary",
        "tries to mow his big slog sweep, manages only an inside edge that somehow eludes his stumps and trickles away to the  ropes",
        "he goes back, has some width this time, and cuts hard to the third man rope with the man up in the ring",
        "makes good use of the poor delivery, goes back in the crease and slogs hard over midwicket",
        "hammered down the ground, the umpire stretches his right hand to signal no-ball and at the same time, also gets out  of the way as the batsman cracks this pitched up ball straight back",
        "some hitting from the batsman, this is not short at all, but he's picked it up so cleanly, it flies to the deep  midwicket rope",
        "he's leaned into this drive, timed it on the up, and placed it past short extra cover's dive",
        "he swivels to pull it in the air to the deep backward square leg boundary",
        "steps out, stretches a bit, and lifts it flat over extra cover",
        "outside edge, there is no slip, and these are four fortunate runs, came forward to defend, but this was the one that  went the other way",
        "that is would have pierced the bowler right in half, it's hit hard down to him at long off, couple of bounces, the  bowler bends and cups his wrists to stop the ball, but it goes through",
        "what a shot, he's walked out, and his momentum has given this lofted push so much distance, it's almost gone over  the deep extra cover rope, it is in the gap anyway",
        "scooped fine over the keeper, the batsman comes across, bends and gets enough bat on this length ball",
        "length ball angled in to the pad, and the batsmans tucks it very fine",
        "now the cut, width provided, and the batsman capitalises with a sharp cut",
        "the slog sweep, an almighty top edge of a slog sweep, no one at deep square leg, and it plonks down near the rope  and rolls into it",
        "that is as clean a hit as any, the batsman has made some room outside leg stump, and blitzed this length delivery  over mid off with a straight, high follow thorugh",
        "too short, too wide, he intentionally flays it in the air and comfortably clears cover",
        "connects well, slightly fuller, the batsman comes forward and lifts it over covers",
        "length in to the pad now, and the batsman steps down the track and turn it neatly through midwicket",
        "shot, gets on his toes and punches this back of a length ball in the air just past point",
        "madness out there, he turns it to midwicket, he wants the single for about a few steps, then he doesn't, his partner  wants it some more, then he hesitates, decides to go for it, he has no choice, the captain has made it for him, the throw is way off target at the keeper's end, the man backing up follows up with a worse one at the bowler's end, and it runs all the way to the straight boundary",
        "keeps eyes on the ball and twists his wrists very late to send the ball to the rope",
        "this is a very high full toss, and the batsman has sent it screaming over short third man with a neat reverse paddle  even as he swivels away to avoid getting hit",
        "poor line to given the situation, good length down the pads, and he swipes it to the deep backward square boundary",
        "and finds the boundary this ball, whips a full ball angled in, beats midwicket's jump, and also a sliding attempt  in the deep",
        "neatly done, very full outside off, not too much width, but the batsman opens the face and times it to deep backward  point rope",
        "he's swung a boundary to deep square leg, reached forward and mowed it in the air",
        "down the pads, swept hard, and well wide of short fine leg",
        "the batsman trying to assert his flow, on the leg side now, this is shortish, be swings it off the front foot and  times it to the deep square leg rope",
        "he wants a single after pushing to the leg side, non-striker is not interested, is half way down when he turns, he  should have no chance, but he will instead get bonus runs, as the throw is nowhere near the keeper, let alone the stumps",
        "he reverse sweeps a full ball from around off, and beats short third man with a crisp connection",
        "a really clean hit, the bowler continues to push it towards leg stump, and the batsman carts it in front of square  leg once more",
        "sees him coming out, pushes it quick into the pad, the batsman swings in front of square and beats the man in the  deep",
        "this has been cracked through extra cover, the batsman walks across to a full and wide one, and clobbers it",
        "short again, but in striking range this time, and he slams a pull in the air, to the deep midwicket boundary",
        "connects for some returns, the bowler digs in the short ball, and the batsman is waiting to pull it hard to the  deep midwicket rope",
        "the batsman forehands it over mid-off for four. Not clean connection, but the man is up in the circle",
        "No energy behind this bowling. Gentle, on a length, wide, and the batsman rashes it over cover for four",
        "no sting behind it, and he has been dismissed through midwicket region. This is a slower bouncer.",
        "down the wicket, takes a length ball, swipes it through midwicket for four",
        "lovely square push drive. Full outside off, the batsman presses forward, covers the swing, and meets it with an open  face. Bisects square cover and cover",
        "short and wide, outside off, the batsman might as well celebrate his birthday right now.",
        "this time it's a low full toss and he makes room and places it down to the vacant deep point region",
        "he doesn't need a sighter! This was too full and wide outside off, the batsman made room and smashed it wide of cover,  the sweeper can't cut it off",
        " he makes room to a length ball and cuts him hard and fast past backward point, big gap there",
        "he whips a full delivery on middle and leg with such force that the ball blazes away wide of midwicket",
        "a pressure-relieving boundary, this was flighted on the pads, he was on his knee early and swept it firmly to fine  leg",
        "this was nicely punched down the ground wide of mid-off off a full delivery",
        "outside edge but no slip, this was full and swinging away, he drove hard at it and the edge flew past the keeper and  down to third man,",
        "in the air but very safe in the end, it was pitched up and he made a bit of room to carve that over the off side,  bisected mid-off an cover very well, the field was up",
        "committed to the sweep early, tossed up on the pads and he gets down and sweeps with conviction",
        "a clean pull, this is poor bowling, too short, sits up nicely for the pull, one bounce to deep midwicket",
        "short and wide outside off, slapped to deep point",
        "clears the infield, this was a length ball, ",
        "overpitched and on the pads, clipped through midwicket for four",
        "overpitched ball outside off, eases that through cover for four, doesn't try to power that one, gets the placement  right",
        "welcome boundary there, the bowler errs by bowling it too wide outside off and short, he makes room and slaps it  down to deep point",
        "looked a bit ungainly but effective, he shuffled across his stumps, exposed all of them and slogged him just wide  of short fine leg",
        " good placement again, third man was up, he had the width outside off to steer it wide of point",
        "that's a lovely cover drive! Half volley outside off, he leans forward and drives crisply wide of cover, races away",
        "full outside off and he lofts him over mid-off",
        "Third man was up and he knew that, the ball was angled across and he had enough width to deftly steer that wide of  short third man and backward point",
        "that's emphatic! Short ball pulled powerfully to the deep midwicket boundary",
        "in the slot and he has hoicked it over the long-on boundary. Cleared his front leg and let the hands go",
        "that was clever. Waited on this shortish ball with just a little room and he dabbed it fine of short third man and  it just skimmed away",
        "big full toss outside of and he's reverse pulled it over the head of short third man",
        "he essays a lovely, orthodox cover drive. All along the ground and stamped with his considerable power.",
        " there wasn't much room to get under this but somehow he does and the sweep skims hard and flat to the deep midwicket  boundary",
        " tossed up on off stump, the batsman plants his front leg down the pitch and slogged it away to the deep midwicket  boundary. The fielder tried to flick it back into the field of play, but he was stamping on the boundary ropes while doing so",
        "drifting down on the pads and he sweeps him one-bounce to the long leg boundary ",
        " and he's switch hit to the point boundary! Changed his stance and then the grip on his bat and blasted it away to  the fielder down there. Pulled out a diving effort but couldn't pull it back",
        "races down the track and though the bowler went short and tried to put it past the reach of the batsman's lashing  blade",
        "gets another fortuitous edge to the third man boundary. Too much room on offer and an open blade is enough to take  advantage",
        "low full toss wide of off stump and the batsman squeezes it away to the third man boundary",
        "length ball on off stump, the batsman swings madly and gets it more off a thick inside edge than anything. But  it's got enough wood on it to find the boundary at deep midwicket",
        "outside off, the batsman gets down on one-knee and reverses sweeps it to the third man boundary",
        "hint of room outside off and the batsman goes back and opens the face to beat short third man",
        "that's a bazooka down the ground!",
        "slashed behind point and this time the fielder isn't quick enough to cut it off.",
        "offers up another overpitched delivery outside off, the batsman says thank you very much and lofts it over extra  cover",
        "bit of extra bounce outside off the off and he rides it well enough with a cut that sails well over the infield.  Couple of bounces and into the hoardings",
        "digs it into the middle of the deck again and the batsman is comfortably pulling them from the crease to the square  leg boundary",
        "shifted his weight onto the back foot and he's just picked up this short ball from outside off and carted it to the  square leg boundary. Whistled away to the boundary",
        "smashed! Overpitched and he eases onto his front foot and drills it through extra cover",
        "got a lot closer to off stump with the back of a length delivery, the batsman goes for the pull and gets a top edge  that sails over the keeper's desperate leap",
        "he tried to outsmart him by bowling short but the batsman is so good square of the wicket. Raced down the track and  though it was dug in short he lashed it over the infield to the point boundary",
        "he manages to thump it through midwicket. Not enough pace to worry the batsman here",
        "this is short and it allows the batsman to rock back and pull in between the long-on and deep midwicket regions.  Muscled away.",
        "this time he picked the line wonderfully well. Saw it drifting into the pads and swung it dead square",
        "flat-batted to the long-on boundary! Cleared his front leg and slammed the back of a length ball outside off stump",
        "Charges at him while making room outside leg and carves it over extra cover",
        "hoisted over the top. Got under it nicely and muscled it down the ground. The fielder at long-on can only usher it  to the boundary",
        "smacked through extra cover. Made room for himself, opened his shoulders up and thumped this length ball on middle  to the boundary",
        "this length ball has pummeled this between long-on and deep midwicket. Clears his front leg and let the bat just  swing freely",
        "walks around his crease and he has upset the bowler's rhythm wonderfully well. Moved outside leg first and lured  him to angle the fuller ball in at him. And once that was done he quickly switched outside off and lap swept it to the long leg boundary",
        "length ball carted away to the deep midwicket boundary! Terrible length to bowl and the batsman pounces on it as he  clears his front leg and dismisses it.",
        "walks at him and swings it away to the long leg boundary! Top shot from the batsman. Picked it up off a length and  whipped it into the gap",
        "This was full and outside off and he has reverse flicked it to the third man boundary! That is an astounding stroke!",
        "in the slot on off stump and he has smeared it to the extra cover boundary. Made room outside leg and launched it  and more importantly found the gap",
        " dug in short and he takes it on to hook it powerfully behind square",
        "Perfect connection this time, and the length ball on middle is dispatched to the deep midwicket boundary. Hadn't middled it but he did hit the gap",
        "cleared his front leg away to whip the fuller delivery on leg stump away to the square leg boundary. Such quick hands ",
        "blindly swings again and this time he gets the benefit of a thick outside edge that scurries away to the third man  boundary",
        "another slower ball as he rolls his fingers down the side of the ball. The batsman plants his front foot down the  line and goes for that big golf swing again. Another outside edge, another third man boundary. The bowler throws his head back in dismay",
        "the batsman had to reach for it but he did manage to connect it well enough to beat the boundary fielder",
        " deep midwicket has a chance this time but he has rushed in too much and makes a mess of what should have been a  simple catch. Low full toss on middle and the batsman hoicked it off the front foot and gets a boundary for his trouble",
        "great effort from the keeper there, flinging himself to his left to nearly grab that one off the batsman, who just  glanced that leg-side delivery",
        "the ball is dropped short by Parnell, the batsman is quickly onto it, pulling it away in front of midwicket for four",
        "full and angled across him, the batsman swings from the crease and gets a thick outside edge that flies away to the  third man boundary, despite a tumbling effort near the ropes",
        "spots the batsman charging and digs it in short, but makes the mistake of bowling wide. The batsman slaps it over  point. Thumping boundary !",
        " pulls out the sweep and it's timed extremely well. He's not bothered with keeping the ball down and why should he,  when he hits it in the gap",
        "that was a snorter of a bouncer. The eyes came off the ball and he was mostly taking evasive action when the bat  sort or jutted out and the top edge was taken to run away to the boundary at long leg",
        "that was a set up for the batsman and he's walloped it to the square leg boundary. The bowler bowls waist-high short  ball and it was the slower one as well. Comfortably dispatched. The ball seems to have caught the cables of the spider-cam and usually it provides grounds for a dead ball, but the umpires give a little leeway",
        "how about that. It's length on middle and leg and he's slapped it down the ground. Came back at the bowler uppishly but it was struck too well for him to have a chance",
        "he's good down the ground and this was in the slot. Length with a bit of room to free the arms and the batsman has launched it towards the sightscreen. Quite elegant",
        "times this to perfection. He backed away and that helped him gain enough room to hoist it over extra cover.",
        "he was afraid of the batsman charging him and pushes this through short and flat. The batsman though was happily waiting on the back foot and pulls it one-bounce to the square leg boundary",
        "presents a short one and he's slapped it behind point. It was pretty much the diet they were given and now these batsmen are getting their fill of it",
        "oh, terrible work from short fine leg. This was a slow, low full toss which he sweeps. Comes at a lovely bounce to the fielder but he was getting ready to throw before he had control of the ball. Boundary gifted",
        "walks across and whips it to the left of short fine leg. The bowler's leisurely pace is working for Daredevils here.",
        "tossed up just outside off, the batsman pulls out a reverse swat and beats short third man. Their change is paying rich dividends here",
        "slog swept and no one is stopping that. This was flighted on off stump but he shuffles across and connects with elan.",
        "igs it in quite short and the batsman is late on the hook. Gets a top edge that just about evades the keeper",
        "stand and deliver. It was length on off stump and he has smashed it wide of midwicket. That bottom hand has loads of power",
        "straight of midwicket again and its the same pick up shot. Back of a length and just outside off, he is well balanced in the crease and finds the boundary",
        "bit more bounce on this and he gets a thick outside edge that sails away to the third man boundary ",
        "reverse swept off the back of the bat! Good length ball, he stretches forward and just helps it on its way.",
        "just a little too full and the batsman has lashed it through point. Too fine for the sweeper to have any chance. Guess that's why he wanted the strike, he's feeling he's hitting them well",
        "this was full and outside off, the batsman walks across and laps him to the right of short fine leg. That's a very brave shot, considering he was almost taking his eyes off the ball",
        "he is giving the impression of being in red hot form! This was short and wide and he hoists it over point.",
        "goes for the yorker again but this was a full toss with ample width, the batsman has skipped down the track and smashed it over point. What a shot!",
        "flatter and quicker and again, Finch goes back and picks it away. a fielder chases after it and tries to pull it back gingerly with his injured hand. Doesn't succeed the first time and his slide has pushed the boundary rope back and on the second touch, his feet were beyond where the advertising skirtings were and that's a four",
        "width on offer and the batsman has lashed it over the head of cover. Wasn't really all that short but it's a pretty true pitch with the new ball still in operation and the batsman trusted the pace and bounce and hit through the line",
        "shortish and just a shade outside off, he goes back in his crease and punches it in front of point with an open face. Pierces the gap and the timing takes care of the rest",
        "he's thrown caution to the winds and his risk comes off. Mid-off was up and he launches the a length ball over his head. Hadn't timed it anywhere near well and the bat face opened on impact too",
        "this time it's short and wide. Finch knows there is no third man and cuts it away to the boundary. Simply done",
        "do not bowl there to him. Short and wide and he lashes it through point. Too well hit for the fielder inside the circle",
        "one-bounce four behind point! The bowler is offering freebies and the striker is accepting them gleefully. Shorter and wider than the previous one in the over and the batsman does not hold back with the cut",
        "Why are they feeding his strength? Half-tracker with width and the batsman has thumped it through point to add another four runs to the score",
        "miss it once, my fault. Tempt me again, I'll whack you to the square leg boundary. Full toss angling into the pads, he finds release with an efficient flick.",
        "and he celebrates that stroke with a bit of cheek. It was shortish and on off stump, he waited and waited and chopped it so fine to the third man boundary.",
        "that's the best of the lot! Overpitched outside off and he has come down on it with a straight bat and blitzed it through the covers. Just skims away",
        "tries at long-on, rushes to his left and pulls out a desparing dive but this was always heading for the boundary. Full toss in the hitting arc and the batsman has dismissed it",
        "saw the batsman making room and slips in a slower ball, the adjusts well enough and helps it away to the fine leg boundary",
        "told you he's good at that! The bowler goes offside as he sees the batsman making room, but he flays his bat at the ball and though one of his hands comes off the bat, it is sliced to the point boundary",
        "the slower ball goes short and the batsman has mauled it to the midwicket boundary. Looks like they wont need him today",
        "skips down the ground and belts the full toss down the ground. Murderous hit from the striker",
        "wide length ball, just stands tall and drives on the up, past cover, all along the ground. Nowhere near the line of the ball but he has executed it superbly with his hands",
        "superb on drive. He plants the front foot down a long way and drives this length ball between the bowler and mid-on. Shows what a difference it makes going between facing international bowlers down under to GPL bowlers in Vellore",
        "on a roll here. Drives this wide length ball on the up. Into the ground it goes, and bounces over the fielder at cover for four more",
        "just swings at one without getting his eye in, and gets a thick edge, which bursts through the hands of first slip",
        "takes the calculated risk. Banks on lack of pace with the bowler. Just short of a length, and he short-arm pulls this through midwicket for four",
        "short of a length, and again he can play the short-arm pull because of the lack of pace. Through midwicket it goes",
        "top shot. Dances down the wicket, stays inside the line of a length ball, extends his arms through it, and chips it over extra cover",
        "short of a length, just outside off, punched away through extra cover for four",
        "flighted outside off, this is a half-volley, and his driving arc sends it back over the bowler's head for four",
        "the expected result. This time, the batsman decided to not watch it closely, to get an edge. The edge, though, flies wide of slip. Just too thick an edge",
        "backs away, and punches it over extra cover for four",
        "Short ball, but that at this bowler's pace is a long hop. The batsman rocks back and pulls him through midwicket for four",
        "lovely shot to break the monotony. This is just pure timing. Short of a length, he shuffles across to reach the line of the ball, and dabs it beautifully in front of third man and to the left of point. Superb timing to beat both of them",
        "starts by angling one into the pads and he whips it away to the fine leg boundary",
        "too full, on the pads, and that's a freebie for the batsman, who flicks it in the air, into the vacant square leg region",
        "gentle, floaty delivery outside off. Looked like a slower ball. He gets forward and plays a flowing drive between cover point and short extra cover",
        "once again some width, not as full, and Tare opens his bat face and punches it away into the gap between backward point and cover point",
        "starts with a full-toss floated wide outside off, and the batsman plonks his front leg forward and drives it confidently to the cover boundary",
        "this time he gives him a bit of width, and Anderson drives powerfully through extra cover, bringing his wrists into the shot to hit that on the top of the bounce and find the big gap to the right of mid-off",
        "short and wide, and that is easy pickings for him, who slashes hard and pierces the gap between backward point and short third man",
        "short, wide, smacked. It sat up to be hit wherever he wanted, and he swivelled through his hips and powered that away to the left of the man at cover",
        "goes back to another length ball, and this time he manages to swivel powerfully through his hips and pummel that past the bowler, down to the long-on boundary",
        "length ball on middle stump, clears his front leg and has a big swing at it, doesn't quite time it, but manages to place it far enough to the right of long-on to pick up four and reach his half-century",
        "length ball outside off, makes a bit of room, and absolutely creams that, flat-batting it in the air, into the gap to the right of extra cover and the left of long-off",
        "what a shot! Another length ball, this time wide outside off, but even though there was width on offer he really had to time that brilliantly to beat third man. Simply moved forward, towards the ball, and sliced through the line with an open bat face to send it rocketing away to the right of the fielder",
        "tossed up outside off, reaches out and drives sweetly to the left of the diving short extra cover",
        "this one's angled in towards leg stump, and he clears his front leg and sweeps it hard to the forward square leg boundary",
        "tossed up outside off, and he drives powerfully into the gap between sweeper cover and long-off. Russell, sprinting in from sweeper cover, throws himself to his right to stop it but can only deflect it into the ropes",
        "boom. That was fired in again, but it's too full, low full-toss, and he backed away and made enough swinging room to hit it hard over the bowler and drill it between long-on and long-off",
        "shot! That's fired in flat and full outside off, and he slices it away cleanly to the deep point boundary",
        "walks down to a length ball to overcome that early swing, and he whips this from outside off through midwicket for four. That is a risk taken alright, but well played at it",
        "top shot. This man can pack a punch. He definitely has here. This is a length ball, wide, and he drives on the up, square through the off side. Four all along the ground",
        "short ball, not a great idea at his pace. The batsman sits back, waits for it to arrive, and pulls this in front of square for four",
        "shot. Looks in good batting form. This is on a length, angling away from him, and he pushes this on the up, with an open face, wide of mid-off, gets four. Lovely timing yet again",
        "takes a risk but this is a high-percentage shot. He goes with bowler's angle and chips this over cover. Not the most powerful of hits, but his intention is to just clear the ring",
        "that's lucky. He takes the risk first ball, backing away and swinging at a wide delivery. The bowler has actually done well because he has seen he back away. But he goes at it, and gets an edge that goes fine of third man",
        "lovely shot. The batsman has made room, and the bowler has cramped him up, but he opens the face from in front of leg to guide this fine of third man for four",
        "short ball, on off, he goes back and punches this in front of point. The fielder has made a stiff effort there. Doesn't dive. The captain wont be happy. Removes him from there",
        "short and wide, the batsman gets under it, and deliberately cuts it in the air to beat backward point.",
        "picks the length early, and even though this is only slightly short, he has rocked back early and has enough time to pull this over midwicket. Excellent shot",
        "pulls this ball he faces for four. Over midwicket. Just a soft short ball",
        "and the keeper hasn't gone for this! Short and wide, he is lucky that the batsman has edged it, which is high to Dhoni's left, but not too high. You want to see your keeper go for these. He hasn't",
        "lucky runs. Poor ball, though. Wide length ball, thw striker goes hard at it, gets a thick edge wide of the keeper, and he gets four. This might be the magic finish.",
        "short ball on leg stump, and it only gets up to waist height. Easily pulled away to the backward square leg boundary",
        "looks to whip through the leg side. Too quickly into his shot and the leading edge pops into the air on the off side, runs away for four to the right of third man",
        "It's shortish, wide, and it sits up outside off. He is on the front foot, and he flat-bats it crisply to the cover boundary",
        "tarts with a full ball wide outside off, and the striker gets a massive stride forward to cream a drive through the covers",
        "short, plenty of width, and he leans back and plays a precise cut to the left of point, times it beautifully and gives sweeper cover no chance of cutting it off",
        "sees a bit of air, skips down the track nimbly, gets inside the line, and chips this leg-stump ball inside-out, over extra cover, and the fielder, sprinting to his right from long-off, has no chance",
        "short and wide this time, and that is brilliant placement from the batsman. A sure-footed step back and across and a jab to place it to the left of point and far enough to the right of sweeper cover to pick up another boundary",
        "dropped! A bit of uppishness and he goes hard at it, looking to hit down the ground. Goes low to the fielder's right, and he crouches and gets both hands to hit, but it simply deflects off them and runs away to the boundary",
        "full, angled across towards middle and off. The batsman clears his front leg and shovels it over mid-on. Didn't hit it too cleanly, but picked out an unguarded area",
        "short, angled down leg, and he whips it off his hips and easily beats long leg, who sprints to his right and sprawls full-length in a desperate attempt to stop the ball",
        "full and wide, and he gets four for his team with a crisp drive to the extra cover boundary",
        "He misses by six feet. The bowler has played with fire here, but he has been lucky: the batsman is exhausted. He has bowled six length balls to a man who loves length balls. Final ball is on a length too. It is outside off, he drives it hard, and in the air, and wide of long-off, but it falls six feet inside the rope",
        "",
        "",
        "",
        ""
    ];