/**
 * Created by Kunal Nagpal <kunagpal@gmail.com> on 09-02-2015.
 *  GraVITas Premier League
 *  Copyright (C) 2014  IEEE Computer Society - VIT Student Chapter <ieeecs@vit.ac.in>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
module.exports =
    [
        "",
        "tries to scoop this from way outside off stump, but he edges it into his body instead, scampers a single",
        "cranks up and has a slog, but he can only mishit it tamely through midwicket",
        "slower one picked from outside off and slogged on the bounce to deep midwicket",
        "steps out and heaves, manages a single to long on",
        "comes out, but cannot get under the ball too well, drives it to long off",
        "had walked outside off trying to go leg side, but this was bowled slow and full, and he dabs it to third man",
        "steps out and clips a full delivery to long on",
        "he gives this full delivery everything, but it just rolls across the outfield to long on",
        "goes straight and aerial now, on the bounce to long on who has run across",
        "moves across and whips this full one wide of fine leg, but is getting only one",
        " low full toss, he drives with an open face to the sweeper",
        "length ball worked to deep midwicket",
        "full just outside off now, the batsman looks to drill it over extra cover, but only hits it along the ground  to long off,   he is visibly angry with himself",
        "almost bowled him, full delivery pushed through, the batsman plays it rather uncertainly, and only an inside  edge saves him",
        "charges out, but only manages a thick inside edge to square leg",
        "cut away for a single",
        "comes out again and swings hard, mishits to long on",
        "bowled slower outside off, the batsman slogs, a thick inside edge runs behind square leg",
        "charges out and forces it through extra cover",
        "comes out a tossed up ball, takes it on the full and hits it to long on",
        "dabs a length ball to point and goes for a quick single",
        "that could have been out, back of a length down the pad, and the batsman disdainfully helps it in the air,  but fine leg is in the way",
        "slogs a very full one to deep midwicket, along the ground",
        "follows him with a full one as the batsman makes more room outside leg, but can only dig it out",
        "sitter dropped, a fielder settles under this leading edge at mid on and it goes straight through his hands  to smack him on the face, he indicates he lost it in the lights, the batsman was trying to forcefully whip it over square leg",
        "a chance, the batsman moves down the track and to the leg side, bowler follows him with a slower one, he  pops it back in the air,   but it is just out of teh fielder's reach",
        "short of a length, worked to mid on's right",
        "turned wide of mid on",
        "walks out and dabs a length ball past slip to third man",
        "ull into the pad and turned in front of square leg",
        "opens the face and runs a length ball to third man",
        "tailing in, worked off the pad to fine leg",
        "moving in and rising from back of a length now, the batsman tucks it to fine leg",
        "dropped, he jumps out and slams it into the bowler, and it rolls away into the off side, shout of 'catch it',  that was struck very hard, and slipped through the bowler's fingers",
        "follows him as he makes room outside leg, the batsman lofts the length ball, couple of bounces to long off",
        "slow, short and very wide, he wants to attack it but is done in by the lack of pace",
        "very full and angled in from wide of the crease, driven to long on",
        "almost a run out, a slower length ball is turned through midwicket, he wants the second, but the fielder  releases the ball quickly even as he falls to the ground,   the batsman dives back, direct hit could have meant trouble",
        "moves forward and drives a full one to long off",
        "nudged square on the leg side",
        "full and angled into the pad, turned to deep midwicket",
        "goes across, the bowler pitches it up on off, and the batsman eases it to long on",
        "flicks a full delivery in the air off the pads, mid on runs it down to his right",
        "a slower one into the pads now, it pops up in the air as he nudges it, but falls in the gap at square leg",
        "angled across him now, and he flashes it past point's dive, third man runs across",
        "waits on this length ball now, it holds its line outside off, and he guides it to third man",
        "he thrusts the slog sweep and gets to the other end",
        "he makes plenty of room outside leg, the bowler follows him every inch of the way, and hits him with a short  of a length ball, it pops up towards point, there is a chance for a run out, but the throw misses",
        "short and wide slower one, he mistimes a cut to the sweeper",
        "tries the reverse sweep, not much on it, but enough for a single wide of short third man",
        "squeezed into the off side for a single, could have been tight",
        "down the track and eases it to long on",
        "bowls it full and wide, the batsman is eyeing the leg side but he has to hit it down to long off",
        "taken from well outside off and worked to deep square leg",
        "that looked dead straight, but the umpire spots the inside edge and remains unmoved",
        "takes this from outside off and manages a top edge on the slog sweep, it weakly loops and falls in front of  deep midwicket",
        "shortish outside off stump, he cuts it in the air, in the gap at cover and down to the sweeper",
        "a top edge loops towards short third man as he tries a reverse paddle",
        "punches this one sliding across him to extra cover, he had backed up too much and would have been gone in  case of a direct hit",
        "punches a good length ball to extra cover, he has a go at the non-striker's, and misses",
        "skips out to this tossed up ball and eases it to long on",
        "hits it along the ground and straight to long off",
        "turned off the pad to deep midwicket",
        "taps a length ball to wide mid on and is taking it easy on the single before he realises he has to hurry,   makes it, throw misses anyway",
        "short of a length into the pad and with one leg in the air, he tucks it to fine leg",
        "very tight single, short ball dropped in front of cover, the non-striker was gone in case of a direct hit",
        "and one more in the blockhole, terrific execution from the bowler, the batsman can only squeeze it to the  off side",
        "in the blockhole, dug out into the pitch and over the bowler, he is running back for the second,   but he  is sent back, no way the non-striker was making it back in time",
        "cracks a full ball straight down the ground, long on slides and saves it, but they have taken only one",
        "has a heave at a pitched up ball, which travels high and falls at vacant mid on",
        "cannot get under this full delivery and squeezes it out to the off side instead",
        "well adjusted, he did not have the length or the angle to swing leg side, so he waits and chips it over the  bowler",
        "full toss on middle, the batsman turns it straight to square leg, there is a direct hit here,   but the  batsman has made it back in time, he was a tad slow in turning around",
        "he's charged out but mishit this lofted stroke, a fielder comes forward at long on, he dives in front, but  it bounces ahead of him, nice effort",
        "that did quite a bit, it was angled sharply into the pad initially and seemed to straighten on the batsman,   who defended and accepted the single as it rolled square on the off side",
        "pulled with intent, straight to deep midwicket though",
        "dropped, the batsman checks a pull and hits it high to short midwicket, he gets both hands to the ball as it  comes over his head, parries it over, but falls to the ground and even as he stretches, the ball falls well out of his reach",
        "comes forward and opens the face to pick up an easy single to cover-point region",
        "comes down the crease, the bowler slows it down, and batsman stops and adjusts to knock it to the off side",
        "a good length ball outside off, that is pushed to mid off for one",
        "opens the face and guides a back of a length ball to third man",
        "comes down the track, but is cramped for room by a shortish one, knocks it past the non-striker for one",
        "turns it towards midwicket for a single",
        "ending inches outside off stump after being pushed across on a length, he adjusts to guide it to third man",
        "back of a length, coming in with the angle, worked to midwicket who makes a sliding stop to keep them to one",
        "softly drops a back of a length ball ",
        "moves across to this length ball outside off and square drives towards third man",
        "pushed away on the off side",
        "this back of a length ball is angled in, tucking him up, he squeezes it to the on side and setts off, direct  hit was needed",
        "yorker, dug out to point, they jog through for one. The fielder at long-off, but they don't chance the second",
        "slogs at a length ball, gets an inside edge for one",
        "nearly bowled him. Another variation form the bowler, the batsman gets a bottom edge on the slog sweep, but  it misses the stumps.",
        "the ball is shorter than ideal for such a shot, and he pushes it towards point for one. The fielder swoops in, underarms this towards the stumps, and he would have had his man had he hit. Good effort, though",
        "punched to deep cover",
        "on the pads, gets a single to long-on",
        "long hop, pulled away to deep midwicket for one",
        "drilled to long-on as he pitches this up",
        " into the ribs, tucked away for one",
        "slow through the air again, clipped away for a single to leg",
        "pushed into the leg side for one",
        "short of a length, pretty straight, bunted to leg for one. A collision in the middle as he dashes across to  field.   No unpleasantness between the two, and we seem to have some action off the pitch as well.",
        "goes after it without feet, and edges it over point for one",
        "down the wicket to drill this down straight of long-off, and the flying fielder saves three runs there with  the dive and a quick throw",
        "down the wicket, more in hope than conviction, gets a thick outside edge for one",
        "on a length, outside off, driven to deep cover",
        "steered to third man for one",
        "short of a length, holds its line in front of middle and leg, bunted to leg for one",
        "outside off, punched away, a diving save at cover-point saves three runs",
        "short of a length, just outside off, dropped towards cover for one",
        "short of a length, angling in, gets an inside edge onto the pad for a single",
        "too full, too straight, clipped away for a single",
        "pushed wide of mid-off for one",
        "short of a length, tucked away off the hip",
        "short of a length, angling in, gets off the strike with a bunted single to leg",
        "full in length outside off and he drives him down to deep cover",
        "slower ball and he drives him to cover",
        "he looked to pull that with more force but he held back and softly places it to square leg",
        "bowls it flat and restricts the big hit, goes back and cuts hard to point",
        "flatter one and he mistimes it to the leg side",
        "comes down the track and he drives him to long-on",
        "he rocks back and thumps it down to mid-off",
        "he makes room and looks to cut but gets an outside edge, short third man cuts it off",
        "full, driven to long-off",
        "slower ball and he punches it to the off side",
        "Dropped ! The bowler gives it more air and tempts the batsman to go for the slog, it was hit flat and dipped  towards the man at long-on,   dived forward and couldn't catch it, not the easiest take either",
        "he tucks it away behind square leg",
        "shuffles across early and he mistimes the flick to the leg side",
        "fetches that from the off stump and clips it to the leg side, good use of wrists",
        "good running, he merely pushed it with soft hands towards cover and sets off quickly, the non-striker is  quick to respond",
        " he goes back at the crease and clips it to the on side",
        "just a short arm flick towards midwicket and they complete a single",
        " punched towards mid-off and there's a misfield and that allows a single",
        " fullish on the pads and clipped just wide of mid-on",
        "he bowls it full on the stumps, pushes it just in front of mid-on and sets off",
        " this time he strays on the pads and he clips it away to the leg side",
        " fires this one full outside off and he digs it out to cover",
        "that's a good yorker and he really had to dig that out to the leg side, nearly lost his balance",
        "minimum footwork but those hands are good enough to cut the shortish delivery down to deep third man",
        "tossed up on off stump, defended with soft hands into the covers",
        "dropped and it is the most comical of the lot. The batsman goes for the reverse sweep but this time he gets  it off the shoulder of the bat and it goes straight up.   The short third man lunges at the ball with both hands outstretched, but to no avail.",
        "fired in on middle and off, the batsman closed the face too early and gets a leading edge to long-off",
        "nearly a yorker on middle and leg, dug out to long-on",
        "short and on the pads again, pulled to deep square leg",
        "good length ball on middle and off, he strides forward to push it down the ground to long-on",
        "slower ball on off stump, the batsman isn't fooled as he dabs into the covers and rotates the strike",
        "low full toss outside off, he opens the face and slices it to deep point",
        "finds the yorker outside off and the batsman pushes it down to long-on",
        "flat-batted down the ground as this is shortish and outside off",
        "the batsman rocks back and cuts to the sweeper",
        "length ball outside off, the batsman is balanced at the crease and pulls it to deep midwicket",
        "good length ball on and around off stump, the batsman punches it down to long-off",
        "drags it from well outside off and pulls down to long-on. Short of a good length",
        "good length ball outside off, it was a little slower too and he taps it down to the man at deep cover",
        "fires it in on middle and leg and it's punched down to long-on. Nicely bowled",
        "shortish and on middle, pulled to deep midwicket",
        "stays put to loft the overpitched delivery to long-off. Hit in the air but falls short of the man rushing in",
        "full on middle, clipped away to deep midwicket",
        "goes for the yorker on off stump, the batsman is good enough to dig it out past the bowler's extended left  hand",
        "nice and full outside off as he drags it away wide of long-on",
        "fired in full and outside off, the batsman steers it through point with an open face",
        "backs away and slashes a length ball behind point",
        "thumped down the ground but long-off is on hand to keep it to a single. Doesn't get it quite right",
        "ample opportunity to swing those shoulders and he lashes to the sweeper again",
        "another full toss on middle and leg, the batsman flicks wide of long-on",
        "skips down the track and looks to beat short cover but has to settle for the single after the misfield",
        " round the wicket and fires it on the stumps and he drills it down to long-on",
        "full toss outside off, pushed down the ground to long-off",
        "fullish and outside off, he goes for a hoick to midwicket and gets an inside edge",
        "dances down the track while making room for himself and laces a drive to long-off",
        "pulls all the pace off this ball as he targets the wide line. He reaches out and slashes it over the infield",
        "full and just outside off, he drives all along the ground to deep cover",
        "fired in on middle and leg, the batsman shuffles across and clips it behind square leg",
        "goes shorter and quicker, the batsman works it for a single to midwicket",
        "slower ball angled into him, worked away into the midwicket region",
        "Tighter line on off stump and a fuller length. Pushed to long-on",
        "good length ball cut off the stumps for a single through the covers",
        "stays back and tucks the short of a length ball away into the square leg region",
        "flatter delivery on the stumps, picked away through midwicket",
        "a little slower on off stump, the batsman is wise to it and guides it off the back foot to third man",
        "continues back of a length but this is the slower one, Smith works it into the leg side",
        "full and angled into the pads, he isn't able to whip it away and has to settle for a single",
        "waits on this nicely, stays beside the shortish ball and taps to deep cover",
        "back of a length on middle and leg, he goes back and blocks and manages an inside edge that squirts out into  the on side",
        "the lack of pace surprised him !. Think this held in the pitch a little more, as the batsman who was looking  to drive on the up had to check his shot. Went uppishly but it evaded the cover field",
        "fullish and on the stumps, he pushes it down to mid-on",
        "hustles for a quick single and had the bowler's throw broken the stumps things might have been interesting.   The batsman nudged to the right of the bowler and took off just that smallest bit late",
        "drifting on the pads and the batsman eases it to deep midwicket",
        "shortish and angled in at him, whipped away calmly to deep midwicket",
        "good length ball on middle, the batsman looks to whip it away but there isn't enough pace on it this time",
        "quick, length ball on the pads. Whipped to deep midwicket",
        "his trip down the track ends up being detrimental as he yorks himself. Dug out to cover",
        "The batsman was making room but the bowler follows him. Again hits the bat hard as he runs it down to third  man",
        "good length ball on middle and off, clipped into midwicket",
        "his use of feet turns a shortish ball into a length one which is belted to long-off",
        "neatly clipped into the vacant midwicket region",
        "Drags a short ball from well outside off to deep square leg",
        "Very thick bottom edge and it would have tested a regular keeper as well.",
        "thick outside edge that evades the slips. The batsman was bringing a closed defensive face down on the ball  and is deceived",
        "back of a length and outside off, steered to deep third man",
        "taps and runs to point as he rides the bounce on this shortish ball outside off",
        "widish yorker, nudged into the covers and raced off for the single",
        "stays deep in his crease and late cuts it down to deep third man",
        "low full toss shaping in at off stump, the batsman was forward and punches to long-off",
        "strides down the track and succeeds in getting it to deep midwicket",
        "shortish and outside off, the batsman goes back and cuts to point who misfields and the two batsman hesitate  in the middle of the pitch wondering if they should go for the single.   By the time the ball is taken control of though, they rush through for the single",
        "drills the low full toss to the sweeper.",
        "opens the face to slice this full delivery outside off to deep cover",
        "slower short ball and the batsman was just a little too exuberant. Mistimes the pull and finds deep square  leg",
        "the batsman looks to steer it down to third man but bottom edges it. The non-striker sees the ball going  into a gap behind the wickets and rushes up for a single",
        "nicely done by the batsman. Realised the ball was defended with soft hands, into the off side, just about  enough to sneak a quick single",
        "slower delivery kept right up there on off stump, the batsman is wise to it as he adjusts his stroke and  pushes to mid-off",
        "nudged to mid-on",
        "rips a back of a length delivery right across the batsman. Well-managed in the end as he plays with soft  hands and lets the outside edge run down to third man",
        "dabbed off the back foot to third man as the bowler is persistent with the off stump channel",
        "back of a length on middle, the batsman tucks it into the midwicket region and they race across for a quick  single",
        "the batsman looks to whack it through the covers but doesn't reach the pitch and ends up mistiming it.  Single taken though",
        "goes back, very deep in his crease and dabs it behind point.",
        "cut away, but there is protection at deep square leg. Lunged forward and kept it all along the ground",
        "the bowler saw the batsman charging at him and pulled his length back. The batsman blocks into the off side  and a fielder rushes in from short cover to cut the angle.",
        "shortish and outside off, the batsman goes back and cuts to deep point",
        "tapped to third man as the bowler tightens his line outside off",
        "flicks a good length ball off his knees to the left of short fine leg",
        "makes room outside leg and beats cover with a punch",
        "goes down the track and eases this into the covers. The fielder is vigilant, and had he struck the stumps direct, we would have had a wicket on our hands",
        "full and on the pads again, whiped to deep square leg",
        "slower ball outside off stump, tapped away to point for a single",
        "full length on middle, punched down the ground",
        "full delivery outside off smeared through point",
        "dropped at short fine leg. The batsman was making big-time room outside leg and the bowler followed him with  a full delivery speared in at his pads. He flicks it to gully, where a sitter is dropped",
        "slogged to deep midwicket. Ugly sort of a shot",
        "goes wide of the crease and presents a slower ball outside off, the batsman is out of his crease and pulls  to deep midwicket",
        "the batsman walks across to push this fuller delivery down the ground",
        "low full toss on the pads, glanced it down to long leg",
        "he's gotten away with that. It was a length ball outside off and the batsman can only hit it as far as deep  cover",
        "pulled uppishly, but it bounces short of the man at the long leg boundary. Picked up the short ball on  middle and leg and helped it along, but because of the slower pace the ball went up in the air",
        "this time the pull doesn't quite work, a bottom edge onto the body as he throws his bat at that one",
        "pushed through on off stump as the batsman taps it into the covers and goes to the other end",
        "comes down the track and thumps it into the covers",
        "he almost falls over in his attempt to make room. So much effort into his shots and it only ends up a single  to long-off as he flat-bats the short ball",
        "full toss on off stump, the batsman flicks to deep midwicket. Took the toe end there",
        "skips down the track and thumps it down to long-off. The bat turns in his hands, not exactly the best piece  of timing.",
        "that's a dolly and he's dropped it at short fine leg! Mr fielder, what have you done?! Clipped uppish but  straight to the man, at abound waist high and at a very comfortable pace coming at him. But it pops in and then pops out",
        "bit of room on offer and he essays a late cut to find deep third man",
        "another drop and it's in the square boundary on the off side. Raced down the track and slapped a short ball  hard and flat. the fielder had to run in and come forward but he spills it",
        "whipped away into the leg side as those strong wrists take over",
        "waist-high full toss and he swipes it away to deep square leg",
        " short again but this was just a touch quicker and the batsman pulls to long-on.",
        "slower ball outside off, the batsman waits for it and thumps it to deep cover",
        "overpitched outside off, the batsman's flashing blade gives work for the sweeper",
        "nice length and teasing just outside off. He gets a thick outside edge to deep third man",
        "comes forward and works it to the left of midwicket. Tight single, but well done in the end",
        "back of a length and outside off, De Kock taps to point and seeks a single. But the batsman is wary of agility in that region. Sends him back but the overthrow allows the score to tick",
        "back of a length and keeping him tucked up on middle, he works it down to short fine leg",
        "fullish and outside off, the batsman eases it to the left of mid-off and he sets off for a single. Steyn was moving to back up and in the process cuts the batsman's path and had that hit direct he would have been out. They shake hands after though, so no harm done",
        "gets a thick outside edge that wanders off to deep third man, away swing off the fuller delivery",
        "back of a length and he's beaten for pace as he looks to flick. The batsman pulls him through for the single as the ball lobs over to point",
        "ack of a length and on the body, the batsman works it behind square leg",
        "shortish and just outside off, the batsman drops and runs to point but I suspect had the fielder's underarmed throw hit he would have been short. Dived and threw in one action, that's wonderful work",
        "on leg stump, worked away to the left of mid-on",
        "his is on a good length and is picked away in front of midwicket. THe batsman scurries in from deep midwicket and keeps it to a single. That's incredibly good fielding",
        "ries to open up the off side by making room for himself, but the man at point follows him. Cut through point",
        "shortish on middle, tapped it behind point",
        "shortish and angled into the pads, flicked into midwicket",
        "nice and tight on leg stump, he picks it away to deep midwicket",
        "think this was the other one, nicely tossed up outside off and the batsman opens the face and picks up a single towards point. Soft hands",
        "full and on middle and leg, the batsman works it to deep midwicket",
        "flighted on off stump, the batsman goes back and works through midwicket.",
        "they've decided to play him off the back foot. This was on a fullish length on off stump, punched down to long-on",
        "tossed up outside off, stands deep in the crease and carves it to deep point",
        "teases him with flight outside off, but the batsman hammers it down to long-off",
        "swept off a good length but there is protection at deep square leg",
        "loopy delivery on leg stump, think that was the odd one. The batsman clips to long-on",
        "this was seam-up and bowled from wide of the crease, he lofts it down to long-off",
        "back of a length and it holds in the pitch a bit, he pushes it down the ground for a well-judged single",
        "full and in the block hole, the batsman sets up for the slog but can't get under it enough. Inside edges to short fine leg",
        "clips the good length ball through to deep midwicket",
        "flatter now and tucking him up on middle, worked away through midwicket",
        "he saw the batsman setting up for the reverse sweep and goes for the seam-up yorker. The batsman still manages to lace it to point",
        "on a good length and the batsman nudges it to deep midwicket",
        "lat delivery on middle, he pulls to deep midwicket",
        "fullish on the stumps, flicked away through midwicket",
        "tossed up on off stump, the bowler slips in his follow through and that's a single down to long-off",
        "rilled into the covers to get off the mark. Loads of power in the stroke as he stays leg side and punches the flighted ball",
        "just a little short and the striker cuts behind square. There is a sweeper out there though",
        "good length ball, turns the other way as he clips through midwicket",
        "moves across and sweeps to deep midwicket",
        "pushed down the ground for a single",
        "low full toss, the batsman punches it down the ground",
        "lower ball on middle, the batsman shuffles across and laps it. Doesn't bother keeping it down and it wasn't too far away from the man who was running in from long leg",
        "overpitched just outside off, belted down to long-off",
        "bit of width outside off on this full delivery and the batsman pummels it down the ground. Drops short of long-off",
        "good length ball just outside off, the batsman punches into extra cover and his partner called him through for a suicidal run. Direct hit and he was out, as he had given up",
        "full on off stump, he drills it to the left of mid-off. The fielder dives a little early but he is tall enough to reach his hand out and cut the progress of the ball",
        "good length ball with a hint of away shape, the batsman gets an outside edge that wanders down to third man",
        "flighted outside off, he hacks it away to deep midwicket",
        "steers it behind point for a single",
        "shortish and outside off, the batsman has no intention of getting in line and cuts. Goes aerial and away to the sweeper",
        "that's a terrific ball seeking the base of middle, the batsman clips it through to midwicket",
        "low full toss just outside off, the batsman steers it to extra cover for a single",
        "finds the yorker on leg stump, the batsman was backing away and gets a thick outside edge that goes down to deep third man. They've taken the single.",
        "slower ball well outside off, he reaches out and pushes it into the covers. Had he left that it would have been a wide",
        "comes down again but the low full toss can only be hit down to long-off",
        "full on leg stump, clipped off the toes to long leg",
        "back of a length, angling in towards off and middle. The batsman jumps across to tuck it away towards square leg",
        "fullish on off stump, straightens a touch as he looks to push through the covers, no real footwork. Ends up edging thickly to third man",
        "back of a length, angling in towards leg stump. Shuffles to work it into the leg side, runs off towards square leg",
        "length ball angling in towards off stump, He uses the angle to clip it to long leg",
        "width again, fullish length, and this time he slashes with an angled bat and edges it down to third man",
        "length ball on middle stump, poked to mid-on with soft hands",
        "back of a length on off stump. Stands tall and pulls it away towards deep backward square leg",
        "fired in round-arm, full, towards off stump. Worked away with the angle through square leg",
        "fired in quicker, into the pads, tucked away through square leg",
        "length ball on off stump, clipped to long-on",
        "back of a length on off stump. The striker gets on his toes, uses the inward angle to tuck it away towards midwicket",
        "back of a length on middle and off, punched away through point",
        "slowish length ball on middle and off, goes with the angle. He stays on the back foot and punches it down the ground towards long-off",
        "length ball on off stump, quite slow, no movement. The batsman waits on it and whips it away through square leg",
        "length ball outside off, dabbed softly towards short third man",
        "back of a length on off stump, stays inside the line, gets on his toes, and squirts it away to third man",
        "length ball on off stump, gets his front foot across to work it away through forward square leg",
        "back of a length, turns from middle to leg, semi-punched, semi-pulled to long-on",
        "shortish outside off, slapped to sweeper cover",
        "length ball on middle stump, and he clears his front leg to make a bit of room to flick it away towards deep midwicket",
        "slower ball, full outside off, driven to long-off",
        "shortish on off stump, pulled to long-on. Came on quicker than he expected, maybe. May have wanted to hit that more towards midwicket",
        "short outside off, steered away to the right of third man. He chases it down, slides to stop it, and throws it back to the keeper while lying on his back",
        "tossed up again, swept firmly to deep midwicket",
        "tossed up outside off. Goes deep in his crease, clubs it down to long-off",
        "length ball on off stump, punched to long-off",
        "tossed up on off stump, clipped to long-on",
        "length ball on the pads, worked away towards deep square leg",
        "fired in flat on the pads, clipped to deep square leg",
        "a bit more air, floated across towards off stump. He goes down on one knee to swipe that to deep midwicket",
        "length ball on leg stump. The batsman stays leg-side of the ball and bunts it into the covers for a single",
        "full on off stump, and that is a terrible drop from the man at deep midwicket. The batsman swung hard at it, hit it in the air, with the turn, and hit it straight to the fielder, who only had to cup his hands in front of his body to catch the ball, but it was straight in and out.",
        "tossed up, angled in towards middle stump. Clears his front leg and sweeps it towards deep square leg",
        "length ball, turns in towards off and middle, clipped away towards deep midwicket",
        "down the track now, makes room as he comes at the bowler, slaps this off-stump ball down to long-off",
        "on the pads, worked away to deep midwicket",
        "full and flat outside off, driven to sweeper cover",
        "full and wide, looks to slog it over midwicket, ends up bottom-edging it into the ground, bounces up to keeper, jogging to his right",
        "full outside off, jabbed down to long-off",
        "full again, swiped to deep midwicket",
        "down the track, driven to long-on",
        "around off, the batsman defends, and the ball runs off the inside half of the bat for one",
        "stays in the crease this time. Lets the ball come on this time and opens the face for a single to third man",
        "this time he takes on mid-off, and completes an easy single",
        "was that another drop? Looked like it. Moved into him again as he came forward to drive. May have been looking to go through mid-off, ended up hitting it back towards the bowler, low to his right. Dived and got his right hand to it but it simply didn't stick",
        "length ball outside off, and he comes forward and picks up yet another poked single to point",
        "fullish outside off, good stride forward to push into the covers",
        "in the blockhole on off stump, jabbed to mid-on",
        "length ball, straightens a bit and cramps the batsman as he tries to chop a middle-stump ball square on the off side. Ends up inside-edging it into the pitch, near his feet",
        "length ball angling away from off stump, chopped away towards backward point",
        "length ball on off stump, pushed off the back foot towards long-on",
        "flat and short on middle and off, pulled away to deep midwicket",
        "tossed up full on leg stump, clipped away to deep square leg",
        "back of a length outside off, leans back and dabs it to the right of short third ma",
        "tossed up outside off, driven to long-off",
        "overpitched on middle and leg, clipped through square leg",
        "length ball on off stump, goes on the back foot and tucks it into the midwicket region",
        "shortish outside off, and the batsman launches it down the ground, looking to clear long-off, who completely misjudges it, comes in too far off the rope, ends up having to leap in the air and reach overhead, one-handed, and can't hold on.",
        "back of a length outside off, dabbed away backward of point",
        "fuller now, driven to long-off",
        "waits on it and tucks it away through square leg",
        "in the blockhole on middle and leg, clipped to the left of the man at short midwicket",
        "low full-toss on the pads, whipped away to deep square leg",
        "full outside off, The batsman gets on the front foot, head over the ball, and uses his wrists to whip it down to long-on",
        "full on middle stump, gets his front foot out of the way and drives down to long-off",
        "tossed up outside off, driven to long-off",
        "length ball on off stump, turns away to accentuate the angle across. The batsman rocks back to cut it away towards deep point",
        "length ball outside off, dabbed away to third man",
        "back of a length on off stump. Looks to poke it towards point, ends up chopping it down into his feet",
        "back of a length outside off. The batsman lets it come on and dabs it to the right of the keeper",
        "tossed up outside off, whipped away to long-on",
        "shortish, turns from middle to off. He rocks back and pulls towards long-on",
        "flat length ball on off stump, whipped away to deep midwicket",
        "short again, pulled in the air, bounces down to long-on",
        "length ball outside off, comes forward and works it towards long-on",
        "short ball angling into the body, pulled away towards deep backward square leg",
        "back of a length outside off, steered away towards third man",
        "in the blockhole on leg stump, clipped to long-on",
        "back of a length outside off, steered down to third man",
        "slower ball in the blockhole on middle stump, whipped in the air, bounces down towards long-on",
        "slower short ball outside off, swatted over the bowler's head, mid-on runs to his right to field it",
        "full on off stump, smacked hard to long-on, lots of bottom hand",
        "slower ball, makes room and swings hard",
        "half-volley, outside off, pushed wide of mid-off with an open face. Gets a single",
        "this one stops a bit at him, hits it uppishly down to long-on for one",
        "full, angling in, dug out into the leg side for one",
        "short of a length, wide, cut away to third man",
        "short of a length, angling in, worked into the leg side for one",
        "short of a length, worked into the leg side for one",
        "short ball, not quick, not high, pulled away for a single",
        "short of a length, flat, on the pads, worked away for one",
        "short, on off, goes back to punch it into the leg side",
        "stays back to another length-ball, punches it to deep cover for one",
        "really slow, but short too. He waits for it, and then short-arms it to long-on",
        "flatter, out of the front of the hand, pushed to long-on for one",
        "quicker, front-of-the-hand delivery, pushed into the leg side",
        "quick, flat, straight, worked into the leg side",
        "sharp delivery, but too short, and is easily punched down to long-on for one",
        "worked off the pad for a single",
        "long hop, and he is lucky the batsman takes just the single to deep midwicket. The timing is off on the pull",
        "flighted outside off, driven to long-off for one",
        "slider this time, and is punched down to long-off for one",
        "short of a length, worked to leg for a single that brings about another cheer. ",
        "worked off the pads for a single",
        "slightly short, but he has no room to play the pull, and ends up slugging it to deep midwicket for one",
        "gets lucky with this one. Looks to open the front leg and slog, gets an outside edge for a single to third man",
        "short of a length, wide, punched to deep cover",
        "flighted outside off, pushed into the off side for a single",
        "full toss, gets away with a single to long-on. He's just not looking to go big",
        "flat quick delivery, just a bit short, He is not looking to take any risks, and gets just the single to long-on despite playing it with soft hands",
        "flat, front of the hands, punched to deep cover for one",
        "full, straight and fast, driven to long-on for one",
        "another defensive push, gets just the single to long-off",
        "short of a length, on off, opens the face, takes a single, but if he hits from point, the non-striker is gone. Just the one stump to aim at so only a half chance. ",
        "down the track but he bowls full and flat, gives him no room, concedes just the single",
        "that's smart bowling. The bowler has anticipated that the batsman wants to go wide long-on and midwicket, and he bowls a slow loopy wide delivery. It is away from the batsman but not quite a wide. All he manages is a single to long-off",
        "short ball, quick again, late into the pull again. Just the single",
        "wide on the crease to bowl a yorker that cramps him up. Dug out for just a single",
        "he moves across first ball and whips this from around off to long leg. Not a high-percentage shot",
        "uppish again. This time with the cut, but he has hit it left enough of the diving fielder at backward point",
        "shuffles across to push a wide length ball between mid-off and cover for one",
        "on a length, angling in, bunted into the leg side for a single",
        "short ball, into the ribs, his eye is off the ball as he fends this into the leg side for one",
        "length ball, angling in, pushed wide of mid-on to get off the mark first ball",
        "lovely shot, and equally good fielding. He rocks back to punch this length ball square on the off side. A fielder flies to his left at point to save three runs",
        "short of a length, outside off, for some reason he looks to whip this to leg, gets a thick leading edge that gets him a single",
        "closer to his body, the batsman, pushes this wide of mid-off for a single this time.",
        "short of a length, just outside off, runs this down to third man for one",
        "looks for the slog. All it takes is a few dot balls for the low-percentage shot to come out. The bottom edge gets him a single",
        "full, just outside off, driven straight of mid-off for a single",
        "short of a length, a bit of a loosener, punched to long-on for one",
        "into the leg side for a single",
        "pushed to mid-on with soft hands, sneaks in a single",
        "slightly short, he goes back to cut, but the ball turns back in sharply, which means he gets just a single after being cramped up",
        "short of a length, outside off, he opens the face to run this down to third man for one",
        "slogged away from off, gets a thick inside edge for one",
        "whips a length ball away from outside off, gets a single to deep midwicket",
        "punched to long-on for one",
        "short again, and he is punched away for on",
        "nicely worked away with the turn for a single. This player looks in his element playing here",
        "short of a length, outside off, runs this down to third man for one",
        "sends him the dummy. Shuffles across, and then backs away to cut this to deep cover for one",
        "quicker, flatter ball, cut away to deep cover for one",
        "full and straight, pushed to long-on",
        "makes room to smash this shortish ball straight to the man at short cover. He mis-fields to allow a single. A bit of a bad bounce really, which hits the top of his wrist and ricochets away for one",
        "short and wide again, lucky to get away with just the single as he has cut this to the sweeper",
        "gets lucky there. He walks at the bowler who bowls the effort bouncer, which gets big on him, but the edge beats midwicket",
        "mis-hit on a pull, but the top edge has not carried to midwicket",
        "short of a length, angling in, worked to leg for one",
        "stylish defensive push off the front foot. Gets a single to the left of point",
        "makes room again, he keeps it straight, cramps him up, concedes just the single on the pull",
        "looks to pull, mis-hits a skiddy delivery, gets a single to long-on",
        " on a length, outside off, pushed wide of mid-off, gets the single",
        "full, outside off, driven to long-off for one",
        "short of a length, outside off, runs this down to third man for one",
        "short of a length, no room, but he still runs this down to third man for one",
        "shuffles across all the way to try a paddle. Gets a thick inside edge for one",
        "full and straight, driven down the ground, the bowler sticks his foot out, they take a single off the ricochet. He has saved three runs because mid-off was up",
        "length ball, angling in, worked to square leg in the circle, but they take a single",
        "short of a length, wide, punched away to deep cover for one",
        "short of a length, punched down to long-on for one",
        "opens the face on this one, gets a single to point.",
        "pushes this length ball to point and gives up. Other batsmen make this single easy, he has given up. The fielder's throw misses, though, and they get the single",
        "low full toss. He has erred on the full side, but he has a deep midwicket in place to keep this down to one",
        "nearly a yorker outside off, the batsman hits hard but he can't mid-off. The single he takes is a lazy one, and the throw would have got him had he hit the stumps",
        "ordinary bowling again, but he doesn't have any length left. Short ball, waist high, right in his slogging arc, but he mis-hits this to long-on, and he is off strike",
        "fuller and comes in on off, moves across and ticks it to the right of midwicket as he gets a single",
        "back of a length and on off, comes forward, the ball hits the splice of the bat as opposed to the bat hitting the bat. Pushed to mid-on",
        "full and straight, he works it to mid-on",
        "pitched up and curls in on off, the batsman does not cover for the inward movement and gets an inside edge, which trickles away wide of midwicket",
        "full and tails in from outside off, gets an inside edge, this one sneaks to short fine",
        "pitched up and outside off, he comes forward and executes a good-looking drive to point. The fielder there comes into action, making a diving stop",
        "very full and fired just outside off, he aims to flick. Thick-outside edge skews to third man",
        "fuller and on middle and leg, tucked away to the right of mid-on now. Towards deep midwicket",
        "short and on off, gets on top of the bounce and bunts it to the left of the covers",
        "on a length and cuts back in on middle, glanced it away fine for a single",
        "on a length and outside off, caressed away to deep cover",
        "looped up on middle, he is down the track as he milks it down towards long-on",
        "short and wide outside off, he rocks back and clunks a cut to deep point",
        "nips down the track and drives it to long-on",
        "fuller and veering onto the pads, glanced away fine for a single",
        "worked away to the leg side as the batsman darts it on the leg stump",
        "shortish and widish outside off, cut away towards sweeper cover",
        "drags his length back, nips down the trick and drives it down to long-on",
        "good length ball targeting the stumps, he gets an inside edge towards deep backward square-leg",
        "full and tossed up outside off, crashed to long-off, straight to the man there",
        "he charges down the track, takes this on the full and drives it to long-off",
        "darted flat and quick at the base of off, the batsman flat-bats it to long-off. Not enough power behind that too",
        "arm-ball from on, off and middle, jabbed down to long-off",
        "gives this some air and it is chipped. The ball lands well in front of long-on",
        "flat and hurled in on off, he flips his wrists and shovels it to long-on",
        "full and straighter, whipped away to cow corner",
        "standard line and length, flicked to long-on",
        "full and on off, flat-batted drive to the off side",
        "low full toss on middle and leg, which is picked away to long-on",
        "banged in short and outside off, he swings it in between mid-on and mid-off. His balance was all awry as he attempted the pull",
        "low full toss on the pads, flicked away behind square leg, but there is protection in the deep",
        "darted full on middle, Faulkner backs away and skelps it away to long-off. Sort of flat-batted that",
        "driven to long-off, more off an inside-edge",
        "pushed through on middle and leg, slammed to long-off",
        "pitched up and outside off, driven wide of point, towards the off-side sweeper",
        "drags his length back and delivers a short ball, mis-hit pull towards mid-on",
        "jumps across the leg stump, sets his tent in there, but the bowler smartly follows the batsman with a tight short ball. Squirted away in front of square leg",
        "misses the yorker, has to settle with a full toss, which is slogged away to long-on. The ball bounces in front of an onrushing long-on",
        "back of a length and outside off, he drives it to point, who dives to his left and stops the ball",
        "rides the bounce of this back-of-a-length offering outside off and glides it to third man",
        "on a length and on the stumps, flips his wrists elaborately and whips it over midwicket",
        "back of a length, rears up on an off-stump line to trouble the batsman, who hops up and stabs it away towards third man",
        "fuller and on middle, tucks it away to the leg side for a single",
        "dug in short on off, the batsman swivels on the back foot and pulls it away to deep midwicket, where the sweeper mops it up",
        "leg stump line, fine leg dives to his right and cuts off what could have easily been a boundary.",
        "slid through on off, he drills a drive to long-off",
        "picked away off the hips with a not-so-strong-looking pull",
        "fuller and on middle and leg, clipped away past midwicket",
        "back of a length and outside off, scythed over cover-point",
        "banged in short on off, he hops up and guides it to third man",
        "floated on middle and leg, turned towards long-on",
        "pushed through on middle and leg, wristed through midwicket",
        "straight roller on middle, he stokes it away to long-on off the bottom half of the bat",
        "milked down to long-on",
        "back of a length and outside off, he brings his carving knife and slices it to third man",
        "back of a length and comes in on middle, he hangs back, fiddles with it and gets an inside edge that sneaks to fine leg",
        "straight roller on middle, clubbed away to long-on",
        "shuffles across and nudges it behind square on the leg side",
        "flat on off and middle, drilled to long-off",
        "aha, there comes the slower ball outside off. He waits on it and dabs it down towards third man",
        "banged in short and lifts on the leg stump, pulled away to deep backward square",
        "looks like another of those slippery back-of-the-hand slower ones outside off. Chopped behind point, Karun collects the ball, hits the stumps at the non-striker's end and concedes an overthrow",
        "on a length and on middle and leg, dragged to the leg side off the inside section of the bat",
        "leg-stumpish, that's in the glancing radar of the striker. Semi-glanced, semi-pulled to fine leg",
        "backs away, the bowler follows him with a yorker. Squeezed away to the leg sid",
        "hunts for a yorker, delivers a full toss, which is punched back at the bowler. Gets both hands on it, but can only parry it away over his head. Not harsh to call it a drop",
        "darted full and wide outside off, makes room and squeezes it to the off side",
        "low full toss on middle, squirted over point off a leading edge of sorts",
        "low full toss on middle, chipped over mid-on",
        "marginally back of a length and just a shade outside off, he bunts it to mid-off and sets off for a speedy single. His partner reciprocated well too",
        "yorker length and swerves back in again, no room at all for the batsman, who jabs his bat down and gets an inside edge to short fine",
        "veering onto the pads, whipped away through midwicket",
        "yorker at the base of off, dug out in front of square off an inside edge",
        "gives this some air, full on the stumps, bunted down to long-on",
        "straight roller on middle, he coaxes it in front of mid-on. They get a single by the time the bowler collects the ball",
        "back of a length and around off, dabbed to the left of the covers for a single",
        "short on the leg stump, knocked behind square on the leg side",
        "pitched further up, the batsman hoists it over the covers. Long-off hunts it down",
        "low full toss, driven wide of the covers as the non striker looks on",
        "late dab to short third as the boundary rider comes into the picture. He loses his balance and flings a throw to the keeper. But the non striker is quick ",
        "Raina eases forward and drives this length ball to long-on",
        "slid through on middle, punched off the back foot to long-on",
        "back of a length and on middle, punched in front of mid-on. He calls for a quick single. Mid on comes in and flings a side-armed throw, but does not effect the direct-hit. A run-hustling man, he slides and reaches the safety zone",
        "low full toss as he steps out, toe-ends it down to long-off",
        "steps way outside leg, he is aware of it as he follows the batsman. The striker adjusts and steers it away towards deep cover",
        "fuller and on middle and leg, he shuffles across and nurdles a single through midwicket. Eye-catching wristwork",
        "the bowler pulls his length back to test the batsman. Mistimed pull, dragged towards fine leg",
        "shortish and outside off, he rocks back and cracks it away to long-off",
        "floated on the leg stump, down the track and whippily driven to long-on",
        "straighter in line on middle, the batsman waits on it and dabs it with soft hands to short third man",
        "too full and straight, whipped away through midwicket",
        "good length outside off, driven between the covers and point",
        "pitched up and outside off, the striker opens his bat-face and drives it, but finds point.",
        "banged in short and climbs onto the batsman, who seeks a pull. Gets it high on the bat, the ball lands in front of long-on",
        "might have been the change of pace, as the batsman adjusts and steers it away to deep cover",
        "lowish full toss on the leg stump, glanced away to short fine",
        "dropped, sweeper cover the guilty party. Back of a length and on middle, the batsman backs away and carves it in the air. The fielder rushes in from sweeper cover, dives forward, but can't cling onto it. In and out.",
        "straighter in line, jerked away to the leg side off the inside section of the bat",
        "turned to mid-on for a quick single as this was straighter in line",
        "yorker at the base of off, he toe-ends it to the off side and squeezes it out",
        "dug in short and on middle and leg, turned to short fine.",
        "punched down to long-on",
        "long-hop on the leg stump, he rocks back and pulls it away towards deep midwicket",
        "full and on the pads, whipped away to cow corner",
        "shortish this time, the striker does not get hold of the pull. Sort of drags it to the leg side",
        "Speared in full on the stumps, he jabs it to the covers and speeds off, the non-striker is nearly run out. There is a shy at the stumps in vain. ",
        "on a length, accurate, defended to leg for a single",
        "swing this time, but headed down leg, and clipped away for one",
        "forward-defensive for a single",
        "a length ball, this time pushed wide of mid-off for one",
        "short of a length, on off, drops it at his feet, and rushes through for one",
        "short ball now swinging in, goes on his toes and works it to deep square leg for one",
        "that pull sent the ball in the air but it landed safely. Looks like he was a bit late on the shot, but got enough to send it behind square",
        "tucks the length delivery off the pads easily to midwicket for one",
        "angled away just outside off, looks to drive it late and gets a bottom edge for one",
        "angled in towards the stumps from length, driven down through the legs to mid-on. He tried to get out of the way but got hit",
        "outside leg now and it's easily worked to midwicket for one",
        "starts with a shortish one around middle and off, defends it close to himself to steal a single",
        "run out chance - slashes this one towards point, where the fielder gets a fumble, throws at non-strikers' but the man is safe",
        "some room outside off and he cuts it late to third man for one",
        "angling away from off stump, guides it late to third man for one",
        "inside edge onto the pads, the ball goes behind towards the keeper and the striker makes his partner run for a cheeky single",
        "touch fuller and he makes the early call this time, pushes it down to mid off and sets off for the single straightaway",
        "bit outside off and he guides it nicely to third man for one",
        "angled across the batsman outside off, he runs it down to third man too",
        "some room outside off, Robbie drives it just wide of mid off and gets one",
        "Short ball, pulled it from the middle of the bat and the fielder was waiting at deep midwicket, but the ball simply popped out of his hands. He can't believe it either!",
        "just outside off, pushed down to mid off for one",
        "fullish on the pads, tucked away behind square on leg for one",
        "full outside off stump, driven nicely to sweeper cover for one",
        "short of length on middle, goes back and works it to leg",
        "comes down the track and cuts the ball late to point for a single",
        "tossed up on middle and leg, turned to deep midwicket with the wrists for one",
        "fullish around off, cross-bat slog goes to deep square leg for one",
        "room outside off, clears his front foot and slashes it over point for one",
        "run-out chance! He defends the ball towards the keeper and calls for it, the non-striker responds with a dive at the keeper's end and luckily for him there was no direct hit",
        "leans forward and works the ball from off stump to short fine leg",
        "full on off, driven down to long on easily for one",
        "fullish on the pads, tucked on the leg side behind square for one",
        "bangs in the short ball which he defends on the leg side for a single",
        "looks to guide the short ball outside off to third man, gets a bottom edge and a single",
        "slightly slower outside off, he leans forward and pushes to backward point for one",
        "in the air, and lands safely this time! Short of length towards the batsman, he pulls and finds the gap between deep fine leg and deep backward",
        "sweeps the length delivery from middle against the turn to deep fine leg for one",
        "leans forward and pushes the ball from outside off to backward point for one",
        "on the other side now - sweeps him against the turn to deep fine leg for one",
        "slower delivery coming in from outside off, pushed to point for one",
        " length delivery just outside off, pushed wide of the bowler for a quick single",
        "length delivery around off, punched down to long on for one",
        "tries the yorker and he punches it to long on for one",
        "short of length outside off, he slaps it straight down the ground. There's a fumble. But they get only one",
        "low and wide full toss, he connects hard and it would have beaten third man but the fielder threw himself to his right to save three runs",
        "banged in short, as the batsman controls a pull and sends it over backward square leg",
        "good length and ball and moving away with angle outside off, guided away to third man",
        "back of a length and outside off, forced down the ground, past the dive",
        "short and wide outside off, he camps on the back foot and flashes a cut to the off-side sweeper",
        "picked away off the hips, behind square on the leg side",
        "back of a length and outside off, down the track and slapped away towards deep cover again",
        "on a fuller length and on middle, punched past the outstretched left hand of long-on",
        "fuller and on middle and leg, punched down the ground",
        "he meets this length ball outside off with an open face and dabs it away in front of point",
        "back of a length and rises on off, wants to force it through the off side, but has to settle with an inside edge that sneaks away to the leg side",
        "banged in short and rises on the batsman, who rolls his wrists and controls a pull behind square leg",
        "dug in on a back of a length and outside off, slashed over point. There is protection in the deep, though",
        "fuller on middle and leg, whipped away through midwicket",
        "on a good length and outside off, stops on the striker, who adjusts and taps it down the ground",
        "He meets this back-of-a-length ball with an open face, gets on top of the bounce and nudges it behind point",
        "lands this on off and gets it to move away, dabbed behind point",
        "slid through short on off, semi pulled, semi shovelled to deep midwicket",
        "chipped in front of long-on. They decide not to take on the risk. Only a single",
        "wide line outside off, he reaches out and squeezes it to deep cover",
        "veering onto the pads, glanced to fine leg",
        "slower, back of a length and outside off, flat-batted down the track to long-off",
        "tossed up, he aims for a slog-sweep, gets an inside-edge that sneaks away fine",
        "dragged short and wide outside off, pulled strongly away to the leg side",
        "slow, scuttles low as well. The batsman does well to adjust and punch it to long-off",
        "darted outside leg, helped away backward of square leg with a pull",
        "darted short, half pulled, half worked to the leg side",
        "he goes low and paddles it round the corner for a single",
        "short and wide outside off, slap-pulled down to long-on. Not all that well-timed too",
        "dug in short and rises on middle, stays back and clubs it over to long-on",
        "flat and quick, pulled away to the leg side",
        "on the leg stump, paddled down to short fine",
        "slid through on middle and leg, punched down to long-on, he was cramped for room there.",
        "back of a length and outside off as he moves around the crease. Slapped away through the covers",
        "dug in short and wide outside off as he comes down the track. Sliced towards sweeper cover",
        "fraction back of a length and outside off, steered away to deep third man",
        "slid through on middle and leg, punched down to long-on",
        "pushed through, sliced away over the covers",
        "down the track, the bowler shortens his length. Jerked away to the off-side. He hardly timed that",
        "slower cutter on off, he waits for it to arrive, opens his bat-face and dinks it behind point",
        "fullish and outside off, sliced away to backward point",
        "pitched and outside off, he throws his bat at it and slices it to deep third man",
        "slower yorker from Bravo, jabbed down to long-on",
        "on a back of a length and on off, stops on the batsman. Chipped in front of long-off, who swoops in on the ball like a tiger and keeps it to a single",
        "fuller and on middle and leg, he aims to force it away to the leg side. Only manages an inside edge",
        "lowish full toss outside off, swept away for a single",
        "lower length ball on middle, lashed down to long-off",
        "rides the bounce of this short one outside off and steers it straight to short third",
        "slower short ball on off, does not come onto the striker. Mis-hit pull over midwicket",
        "dug in short and climbs alarmingly, He takes his eyes off the ball and mis-times the pull over square leg",
        "off-speed ball outside off, punched down to long-on, not much power behind that, though",
        "back of a length and outside off, cut late to point",
        "yorker at the base of the leg stump, he backs away and squeezes it out to the off side",
        "another of those slower ones on middle and leg, from the back of the hand, tickled to short fine",
        "backs away a touch, the bowler follows him with tight yorker, which is bunted towards long-off. ",
        "length delivery on middle and leg, worked wide of mid on for one",
        "goes back this time with minimal footwork and pushes it down to mid off for one",
        "shuffles across a bit and helps the ball with the turn to leg for one",
        "bit of flight outside off, it turns away and he pushes it tentatively into the covers",
        "rom outside off, he goes back and jabs it to leg for one",
        "goes back to let it come to him and works to leg for one",
        "hops back for the back of length ball and works it to deep midwicket for one",
        "towards the pads from outside leg, slightly slow, worked towards midwicket for one",
        "full and flat on the stumps, clubbed down the ground for one",
        "flighted on middle, works it to leg with soft hands and he forces his partner for a single",
        "short ball is pulled in the air and it bounces once before reaching deep midwicket",
        "full and wide outside off, driven uppishly and powerfully down to long off for one",
        "oud appeal for lbw as he slog-sweeps and misses but that one pitched outside leg for sure. Good decision. Maybe inside edge too",
        "well outside leg again and this time he works it to midwicket for one",
        "full toss on off stump, punched down the ground and it deflects off his left shoe to long off. For a second it looked like the batsman kicked it away",
        "comes down and slogs the length ball with the turn to deep midwicket",
        "well outside leg and easily helped to midwicket for one",
        "just around leg and worked off the back foot to deep midwicket",
        "comes down and smashes the low full toss to deep midwicket",
        "comes down to smash the full ball but manages to get it only to long on",
        "outside leg, pushed to deep midwicket for one",
        "dropped by the man in the deep, though it was a tough one! Pulled it to deep midwicket, the fielder took some time to react and went forward but couldn't hold on to it",
        "stays back to push the ball from outside off to long off",
        "goes back and works the ball from outside leg to deep midwicket for one",
        "waits for the ball to turn and just beats midwicket with a punch",
        "whips the ball late to deep midwicket",
        "flatter outside off, punched down to long off",
        "hits that one from outside off with some power to sweeper cover for one",
        "stays back and lofts the ball after it turns to deep midwicket",
        "slightly shorter and he pulls it off the back foot to long on",
        "outside off and he plays it away from the body to deep point for one",
        "on middle and leg now, he looks to defend and gets a thick outside edge on off for one",
        "run out chance missed by the fielding team! Sammy helped the ball with the turn to short fine leg and set off for the single, the non-striker started a bit late and the throw was accurate at keeper's end but he didn't collect the ball",
        "wider outside off and he punches it off the back foot to sweeper cover",
        "very flat and quick outside off, muscled down to long off",
        "flat and coming in, worked to the leg side for one",
        "slightly flatter from outside off, pulled to deep midwicket for one",
        "and a drop! He slog swept the fullish ball from middle behind square and the fielder there got to it but could not hold on as he was on the move. Turning point?",
        "fullish outside off and he drives uppishly, gets a leading edge and it beats the man at cover. He gets a single",
        "slightly quicker on the pads, clipped to deep midwicket and he wants two more but won't get more than one",
        "makes room to slash at the ball and finds point, but they take a quick single",
        "back of length towards the batsman now, he gets some bat towards short fine leg for an easy single",
        "",
        "",
        "",
        ""
    ];