/**
 * Created by Kunal Nagpal <kunagpal@gmail.com> on 09-02-2015.
 *  GraVITas Premier League
 *  Copyright (C) 2014  IEEE Computer Society - VIT Student Chapter <ieeecs@vit.ac.in>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
module.exports =
    [
        "",
        "tries to scoop this from way outside off stump, but he edges it into his body instead, scampers a single",
        "cranks up and has a slog, but he can only mishit it tamely through midwicket",
        "slower one picked from outside off and slogged on the bounce to deep midwicket",
        "steps out and heaves, manages a single to long on",
        "comes out, but cannot get under the ball too well, drives it to long off",
        "had walked outside off trying to go leg side, but this was bowled slow and full, and he dabs it to third man",
        "steps out and clips a full delivery to long on",
        "he gives this full delivery everything, but it just rolls across the outfield to long on",
        "goes straight and aerial now, on the bounce to long on who has run across",
        "moves across and whips this full one wide of fine leg, but is getting only one",
        " low full toss, he drives with an open face to the sweeper",
        "length ball worked to deep midwicket",
        "full just outside off now, the batsman looks to drill it over extra cover, but only hits it along the ground  to long off,   he is visibly angry with himself",
        "almost bowled him, full delivery pushed through, the batsman plays it rather uncertainly, and only an inside  edge saves him",
        "charges out, but only manages a thick inside edge to square leg",
        "cut away for a single",
        "comes out again and swings hard, mishits to long on",
        "bowled slower outside off, the batsman slogs, a thick inside edge runs behind square leg",
        "charges out and forces it through extra cover",
        "comes out a tossed up ball, takes it on the full and hits it to long on",
        "dabs a length ball to point and goes for a quick single",
        "that could have been out, back of a length down the pad, and the batsman disdainfully helps it in the air,  but fine leg is in the way",
        "slogs a very full one to deep midwicket, along the ground",
        "follows him with a full one as the batsman makes more room outside leg, but can only dig it out",
        "sitter dropped, a fielder settles under this leading edge at mid on and it goes straight through his hands  to smack him on the face, he indicates he lost it in the lights, the batsman was trying to forcefully whip it over square leg",
        "a chance, the batsman moves down the track and to the leg side, bowler follows him with a slower one, he  pops it back in the air,   but it is just out of teh fielder's reach",
        "short of a length, worked to mid on's right",
        "turned wide of mid on",
        "walks out and dabs a length ball past slip to third man",
        "ull into the pad and turned in front of square leg",
        "opens the face and runs a length ball to third man",
        "tailing in, worked off the pad to fine leg",
        "moving in and rising from back of a length now, the batsman tucks it to fine leg",
        "dropped, he jumps out and slams it into the bowler, and it rolls away into the off side, shout of 'catch it',  that was struck very hard, and slipped through the bowler's fingers",
        "follows him as he makes room outside leg, the batsman lofts the length ball, couple of bounces to long off",
        "slow, short and very wide, he wants to attack it but is done in by the lack of pace",
        "very full and angled in from wide of the crease, driven to long on",
        "almost a run out, a slower length ball is turned through midwicket, he wants the second, but the fielder  releases the ball quickly even as he falls to the ground,   the batsman dives back, direct hit could have meant trouble",
        "moves forward and drives a full one to long off",
        "nudged square on the leg side",
        "full and angled into the pad, turned to deep midwicket",
        "goes across, the bowler pitches it up on off, and the batsman eases it to long on",
        "flicks a full delivery in the air off the pads, mid on runs it down to his right",
        "a slower one into the pads now, it pops up in the air as he nudges it, but falls in the gap at square leg",
        "angled across him now, and he flashes it past point's dive, third man runs across",
        "waits on this length ball now, it holds its line outside off, and he guides it to third man",
        "he thrusts the slog sweep and gets to the other end",
        "he makes plenty of room outside leg, the bowler follows him every inch of the way, and hits him with a short  of a length ball, it pops up towards point, there is a chance for a run out, but the throw misses",
        "short and wide slower one, he mistimes a cut to the sweeper",
        "tries the reverse sweep, not much on it, but enough for a single wide of short third man",
        "squeezed into the off side for a single, could have been tight",
        "down the track and eases it to long on",
        "bowls it full and wide, the batsman is eyeing the leg side but he has to hit it down to long off",
        "taken from well outside off and worked to deep square leg",
        "that looked dead straight, but the umpire spots the inside edge and remains unmoved",
        "takes this from outside off and manages a top edge on the slog sweep, it weakly loops and falls in front of  deep midwicket",
        "shortish outside off stump, he cuts it in the air, in the gap at cover and down to the sweeper",
        "a top edge loops towards short third man as he tries a reverse paddle",
        "punches this one sliding across him to extra cover, he had backed up too much and would have been gone in  case of a direct hit",
        "punches a good length ball to extra cover, he has a go at the non-striker's, and misses",
        "skips out to this tossed up ball and eases it to long on",
        "hits it along the ground and straight to long off",
        "turned off the pad to deep midwicket",
        "taps a length ball to wide mid on and is taking it easy on the single before he realises he has to hurry,   makes it, throw misses anyway",
        "short of a length into the pad and with one leg in the air, he tucks it to fine leg",
        "very tight single, short ball dropped in front of cover, the non-striker was gone in case of a direct hit",
        "and one more in the blockhole, terrific execution from the bowler, the batsman can only squeeze it to the  off side",
        "in the blockhole, dug out into the pitch and over the bowler, he is running back for the second,   but he  is sent back, no way the non-striker was making it back in time",
        "cracks a full ball straight down the ground, long on slides and saves it, but they have taken only one",
        "has a heave at a pitched up ball, which travels high and falls at vacant mid on",
        "cannot get under this full delivery and squeezes it out to the off side instead",
        "well adjusted, he did not have the length or the angle to swing leg side, so he waits and chips it over the  bowler",
        "full toss on middle, the batsman turns it straight to square leg, there is a direct hit here,   but the  batsman has made it back in time, he was a tad slow in turning around",
        "he's charged out but mishit this lofted stroke, a fielder comes forward at long on, he dives in front, but  it bounces ahead of him, nice effort",
        "that did quite a bit, it was angled sharply into the pad initially and seemed to straighten on the batsman,   who defended and accepted the single as it rolled square on the off side",
        "pulled with intent, straight to deep midwicket though",
        "dropped, the batsman checks a pull and hits it high to short midwicket, he gets both hands to the ball as it  comes over his head, parries it over, but falls to the ground and even as he stretches, the ball falls well out of his reach",
        "comes forward and opens the face to pick up an easy single to cover-point region",
        "comes down the crease, the bowler slows it down, and batsman stops and adjusts to knock it to the off side",
        "a good length ball outside off, that is pushed to mid off for one",
        "opens the face and guides a back of a length ball to third man",
        "comes down the track, but is cramped for room by a shortish one, knocks it past the non-striker for one",
        "turns it towards midwicket for a single",
        "ending inches outside off stump after being pushed across on a length, he adjusts to guide it to third man",
        "back of a length, coming in with the angle, worked to midwicket who makes a sliding stop to keep them to one",
        "softly drops a back of a length ball ",
        "moves across to this length ball outside off and square drives towards third man",
        "pushed away on the off side",
        "this back of a length ball is angled in, tucking him up, he squeezes it to the on side and setts off, direct  hit was needed",
        "yorker, dug out to point, they jog through for one. The fielder at long-off, but they don't chance the second",
        "slogs at a length ball, gets an inside edge for one",
        "nearly bowled him. Another variation form the bowler, the batsman gets a bottom edge on the slog sweep, but  it misses the stumps.",
        "the ball is shorter than ideal for such a shot, and he pushes it towards point for one. The fielder swoops in, underarms this towards the stumps, and he would have had his man had he hit. Good effort, though",
        "punched to deep cover",
        "on the pads, gets a single to long-on",
        "long hop, pulled away to deep midwicket for one",
        "drilled to long-on as he pitches this up",
        " into the ribs, tucked away for one",
        "slow through the air again, clipped away for a single to leg",
        "pushed into the leg side for one",
        "short of a length, pretty straight, bunted to leg for one. A collision in the middle as he dashes across to  field.   No unpleasantness between the two, and we seem to have some action off the pitch as well.",
        "goes after it without feet, and edges it over point for one",
        "down the wicket to drill this down straight of long-off, and the flying fielder saves three runs there with  the dive and a quick throw",
        "down the wicket, more in hope than conviction, gets a thick outside edge for one",
        "on a length, outside off, driven to deep cover",
        "steered to third man for one",
        "short of a length, holds its line in front of middle and leg, bunted to leg for one",
        "outside off, punched away, a diving save at cover-point saves three runs",
        "short of a length, just outside off, dropped towards cover for one",
        "short of a length, angling in, gets an inside edge onto the pad for a single",
        "too full, too straight, clipped away for a single",
        "pushed wide of mid-off for one",
        "short of a length, tucked away off the hip",
        "short of a length, angling in, gets off the strike with a bunted single to leg",
        "full in length outside off and he drives him down to deep cover",
        "slower ball and he drives him to cover",
        "he looked to pull that with more force but he held back and softly places it to square leg",
        "bowls it flat and restricts the big hit, goes back and cuts hard to point",
        "flatter one and he mistimes it to the leg side",
        "comes down the track and he drives him to long-on",
        "he rocks back and thumps it down to mid-off",
        "he makes room and looks to cut but gets an outside edge, short third man cuts it off",
        "full, driven to long-off",
        "slower ball and he punches it to the off side",
        "Dropped ! The bowler gives it more air and tempts the batsman to go for the slog, it was hit flat and dipped  towards the man at long-on,   dived forward and couldn't catch it, not the easiest take either",
        "he tucks it away behind square leg",
        "shuffles across early and he mistimes the flick to the leg side",
        "fetches that from the off stump and clips it to the leg side, good use of wrists",
        "good running, he merely pushed it with soft hands towards cover and sets off quickly, the non-striker is  quick to respond",
        " he goes back at the crease and clips it to the on side",
        "just a short arm flick towards midwicket and they complete a single",
        " punched towards mid-off and there's a misfield and that allows a single",
        " fullish on the pads and clipped just wide of mid-on",
        "he bowls it full on the stumps, pushes it just in front of mid-on and sets off",
        " this time he strays on the pads and he clips it away to the leg side",
        " fires this one full outside off and he digs it out to cover",
        "that's a good yorker and he really had to dig that out to the leg side, nearly lost his balance",
        "minimum footwork but those hands are good enough to cut the shortish delivery down to deep third man",
        "tossed up on off stump, defended with soft hands into the covers",
        "dropped and it is the most comical of the lot. The batsman goes for the reverse sweep but this time he gets  it off the shoulder of the bat and it goes straight up.   The short third man lunges at the ball with both hands outstretched, but to no avail.",
        "fired in on middle and off, the batsman closed the face too early and gets a leading edge to long-off",
        "nearly a yorker on middle and leg, dug out to long-on",
        "short and on the pads again, pulled to deep square leg",
        "good length ball on middle and off, he strides forward to push it down the ground to long-on",
        "slower ball on off stump, the batsman isn't fooled as he dabs into the covers and rotates the strike",
        "low full toss outside off, he opens the face and slices it to deep point",
        "finds the yorker outside off and the batsman pushes it down to long-on",
        "flat-batted down the ground as this is shortish and outside off",
        "the batsman rocks back and cuts to the sweeper",
        "length ball outside off, the batsman is balanced at the crease and pulls it to deep midwicket",
        "good length ball on and around off stump, the batsman punches it down to long-off",
        "drags it from well outside off and pulls down to long-on. Short of a good length",
        "good length ball outside off, it was a little slower too and he taps it down to the man at deep cover",
        "fires it in on middle and leg and it's punched down to long-on. Nicely bowled",
        "shortish and on middle, pulled to deep midwicket",
        "stays put to loft the overpitched delivery to long-off. Hit in the air but falls short of the man rushing in",
        "full on middle, clipped away to deep midwicket",
        "goes for the yorker on off stump, the batsman is good enough to dig it out past the bowler's extended left  hand",
        "nice and full outside off as he drags it away wide of long-on",
        "fired in full and outside off, the batsman steers it through point with an open face",
        "backs away and slashes a length ball behind point",
        "thumped down the ground but long-off is on hand to keep it to a single. Doesn't get it quite right",
        "ample opportunity to swing those shoulders and he lashes to the sweeper again",
        "another full toss on middle and leg, the batsman flicks wide of long-on",
        "skips down the track and looks to beat short cover but has to settle for the single after the misfield",
        " round the wicket and fires it on the stumps and he drills it down to long-on",
        "full toss outside off, pushed down the ground to long-off",
        "fullish and outside off, he goes for a hoick to midwicket and gets an inside edge",
        "dances down the track while making room for himself and laces a drive to long-off",
        "pulls all the pace off this ball as he targets the wide line. He reaches out and slashes it over the infield",
        "full and just outside off, he drives all along the ground to deep cover",
        "fired in on middle and leg, the batsman shuffles across and clips it behind square leg",
        "goes shorter and quicker, the batsman works it for a single to midwicket",
        "slower ball angled into him, worked away into the midwicket region",
        "Tighter line on off stump and a fuller length. Pushed to long-on",
        "good length ball cut off the stumps for a single through the covers",
        "stays back and tucks the short of a length ball away into the square leg region",
        "flatter delivery on the stumps, picked away through midwicket",
        "a little slower on off stump, the batsman is wise to it and guides it off the back foot to third man",
        "continues back of a length but this is the slower one, Smith works it into the leg side",
        "full and angled into the pads, he isn't able to whip it away and has to settle for a single",
        "waits on this nicely, stays beside the shortish ball and taps to deep cover",
        "back of a length on middle and leg, he goes back and blocks and manages an inside edge that squirts out into  the on side",
        "the lack of pace surprised him !. Think this held in the pitch a little more, as the batsman who was looking  to drive on the up had to check his shot. Went uppishly but it evaded the cover field",
        "fullish and on the stumps, he pushes it down to mid-on",
        "hustles for a quick single and had the bowler's throw broken the stumps things might have been interesting.   The batsman nudged to the right of the bowler and took off just that smallest bit late",
        "drifting on the pads and the batsman eases it to deep midwicket",
        "shortish and angled in at him, whipped away calmly to deep midwicket",
        "good length ball on middle, the batsman looks to whip it away but there isn't enough pace on it this time",
        "quick, length ball on the pads. Whipped to deep midwicket",
        "his trip down the track ends up being detrimental as he yorks himself. Dug out to cover",
        "The batsman was making room but the bowler follows him. Again hits the bat hard as he runs it down to third  man",
        "good length ball on middle and off, clipped into midwicket",
        "his use of feet turns a shortish ball into a length one which is belted to long-off",
        "neatly clipped into the vacant midwicket region",
        "Drags a short ball from well outside off to deep square leg",
        "Very thick bottom edge and it would have tested a regular keeper as well.",
        "thick outside edge that evades the slips. The batsman was bringing a closed defensive face down on the ball  and is deceived",
        "back of a length and outside off, steered to deep third man",
        "taps and runs to point as he rides the bounce on this shortish ball outside off",
        "widish yorker, nudged into the covers and raced off for the single",
        "stays deep in his crease and late cuts it down to deep third man",
        "low full toss shaping in at off stump, the batsman was forward and punches to long-off",
        "strides down the track and succeeds in getting it to deep midwicket",
        "shortish and outside off, the batsman goes back and cuts to point who misfields and the two batsman hesitate  in the middle of the pitch wondering if they should go for the single.   By the time the ball is taken control of though, they rush through for the single",
        "drills the low full toss to the sweeper.",
        "opens the face to slice this full delivery outside off to deep cover",
        "slower short ball and the batsman was just a little too exuberant. Mistimes the pull and finds deep square  leg",
        "the batsman looks to steer it down to third man but bottom edges it. The non-striker sees the ball going  into a gap behind the wickets and rushes up for a single",
        "nicely done by the batsman. Realised the ball was defended with soft hands, into the off side, just about  enough to sneak a quick single",
        "slower delivery kept right up there on off stump, the batsman is wise to it as he adjusts his stroke and  pushes to mid-off",
        "nudged to mid-on",
        "rips a back of a length delivery right across the batsman. Well-managed in the end as he plays with soft  hands and lets the outside edge run down to third man",
        "dabbed off the back foot to third man as the bowler is persistent with the off stump channel",
        "back of a length on middle, the batsman tucks it into the midwicket region and they race across for a quick  single",
        "the batsman looks to whack it through the covers but doesn't reach the pitch and ends up mistiming it.  Single taken though",
        "goes back, very deep in his crease and dabs it behind point.",
        "cut away, but there is protection at deep square leg. Lunged forward and kept it all along the ground",
        "the bowler saw the batsman charging at him and pulled his length back. The batsman blocks into the off side  and a fielder rushes in from short cover to cut the angle.",
        "shortish and outside off, the batsman goes back and cuts to deep point",
        "tapped to third man as the bowler tightens his line outside off",
        "flicks a good length ball off his knees to the left of short fine leg",
        "makes room outside leg and beats cover with a punch",
        "goes down the track and eases this into the covers. The fielder is vigilant, and had he struck the stumps direct, we would have had a wicket on our hands",
        "full and on the pads again, whiped to deep square leg",
        "slower ball outside off stump, tapped away to point for a single",
        "full length on middle, punched down the ground",
        "full delivery outside off smeared through point",
        "dropped at short fine leg. The batsman was making big-time room outside leg and the bowler followed him with  a full delivery speared in at his pads. He flicks it to gully, where a sitter is dropped",
        "slogged to deep midwicket. Ugly sort of a shot",
        "goes wide of the crease and presents a slower ball outside off, the batsman is out of his crease and pulls  to deep midwicket",
        "the batsman walks across to push this fuller delivery down the ground",
        "low full toss on the pads, glanced it down to long leg",
        "he's gotten away with that. It was a length ball outside off and the batsman can only hit it as far as deep  cover",
        "pulled uppishly, but it bounces short of the man at the long leg boundary. Picked up the short ball on  middle and leg and helped it along, but because of the slower pace the ball went up in the air",
        "this time the pull doesn't quite work, a bottom edge onto the body as he throws his bat at that one",
        "pushed through on off stump as the batsman taps it into the covers and goes to the other end",
        "comes down the track and thumps it into the covers",
        "he almost falls over in his attempt to make room. So much effort into his shots and it only ends up a single  to long-off as he flat-bats the short ball",
        "full toss on off stump, the batsman flicks to deep midwicket. Took the toe end there",
        "skips down the track and thumps it down to long-off. The bat turns in his hands, not exactly the best piece  of timing.",
        "that's a dolly and he's dropped it at short fine leg! Mr fielder, what have you done?! Clipped uppish but  straight to the man, at abound waist high and at a very comfortable pace coming at him. But it pops in and then pops out",
        "bit of room on offer and he essays a late cut to find deep third man",
        "another drop and it's in the square boundary on the off side. Raced down the track and slapped a short ball  hard and flat. the fielder had to run in and come forward but he spills it",
        "whipped away into the leg side as those strong wrists take over",
        "waist-high full toss and he swipes it away to deep square leg",
        " short again but this was just a touch quicker and the batsman pulls to long-on.",
        "slower ball outside off, the batsman waits for it and thumps it to deep cover",
        "overpitched outside off, the batsman's flashing blade gives work for the sweeper",
        "nice length and teasing just outside off. He gets a thick outside edge to deep third man",
        "comes forward and works it to the left of midwicket. Tight single, but well done in the end",
        "back of a length and outside off, De Kock taps to point and seeks a single. But the batsman is wary of agility in that region. Sends him back but the overthrow allows the score to tick",
        "back of a length and keeping him tucked up on middle, he works it down to short fine leg",
        "fullish and outside off, the batsman eases it to the left of mid-off and he sets off for a single. Steyn was moving to back up and in the process cuts the batsman's path and had that hit direct he would have been out. They shake hands after though, so no harm done",
        "gets a thick outside edge that wanders off to deep third man, away swing off the fuller delivery",
        "back of a length and he's beaten for pace as he looks to flick. The batsman pulls him through for the single as the ball lobs over to point",
        "ack of a length and on the body, the batsman works it behind square leg",
        "shortish and just outside off, the batsman drops and runs to point but I suspect had the fielder's underarmed throw hit he would have been short. Dived and threw in one action, that's wonderful work",
        "on leg stump, worked away to the left of mid-on",
        "his is on a good length and is picked away in front of midwicket. THe batsman scurries in from deep midwicket and keeps it to a single. That's incredibly good fielding",
        "ries to open up the off side by making room for himself, but the man at point follows him. Cut through point",
        "shortish on middle, tapped it behind point",
        "shortish and angled into the pads, flicked into midwicket",
        "nice and tight on leg stump, he picks it away to deep midwicket",
        "think this was the other one, nicely tossed up outside off and the batsman opens the face and picks up a single towards point. Soft hands",
        "full and on middle and leg, the batsman works it to deep midwicket",
        "flighted on off stump, the batsman goes back and works through midwicket.",
        "they've decided to play him off the back foot. This was on a fullish length on off stump, punched down to long-on",
        "tossed up outside off, stands deep in the crease and carves it to deep point",
        "teases him with flight outside off, but the batsman hammers it down to long-off",
        "swept off a good length but there is protection at deep square leg",
        "loopy delivery on leg stump, think that was the odd one. The batsman clips to long-on",
        "this was seam-up and bowled from wide of the crease, he lofts it down to long-off",
        "back of a length and it holds in the pitch a bit, he pushes it down the ground for a well-judged single",
        "full and in the block hole, the batsman sets up for the slog but can't get under it enough. Inside edges to short fine leg",
        "clips the good length ball through to deep midwicket",
        "flatter now and tucking him up on middle, worked away through midwicket",
        "he saw the batsman setting up for the reverse sweep and goes for the seam-up yorker. The batsman still manages to lace it to point",
        "on a good length and the batsman nudges it to deep midwicket",
        "lat delivery on middle, he pulls to deep midwicket",
        "fullish on the stumps, flicked away through midwicket",
        "tossed up on off stump, the bowler slips in his follow through and that's a single down to long-off",
        "rilled into the covers to get off the mark. Loads of power in the stroke as he stays leg side and punches the flighted ball",
        "just a little short and the striker cuts behind square. There is a sweeper out there though",
        "good length ball, turns the other way as he clips through midwicket",
        "moves across and sweeps to deep midwicket",
        "pushed down the ground for a single",
        "low full toss, the batsman punches it down the ground",
        "lower ball on middle, the batsman shuffles across and laps it. Doesn't bother keeping it down and it wasn't too far away from the man who was running in from long leg",
        "overpitched just outside off, belted down to long-off",
        "bit of width outside off on this full delivery and the batsman pummels it down the ground. Drops short of long-off",
        "good length ball just outside off, the batsman punches into extra cover and his partner called him through for a suicidal run. Direct hit and he was out, as he had given up",
        "full on off stump, he drills it to the left of mid-off. The fielder dives a little early but he is tall enough to reach his hand out and cut the progress of the ball",
        "good length ball with a hint of away shape, the batsman gets an outside edge that wanders down to third man",
        "flighted outside off, he hacks it away to deep midwicket",
        "steers it behind point for a single",
        "shortish and outside off, the batsman has no intention of getting in line and cuts. Goes aerial and away to the sweeper",
        "that's a terrific ball seeking the base of middle, the batsman clips it through to midwicket",
        "low full toss just outside off, the batsman steers it to extra cover for a single",
        "finds the yorker on leg stump, the batsman was backing away and gets a thick outside edge that goes down to deep third man. They've taken the single.",
        "slower ball well outside off, he reaches out and pushes it into the covers. Had he left that it would have been a wide",
        "comes down again but the low full toss can only be hit down to long-off",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ];