/*
 Created by Kunal Nagpal <kunagpal@gmail.com>
 GraVITas Premier League
 *  Copyright (C) 2014  IEEE Computer Society - VIT Student Chapter <ieeecs@vit.ac.in>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
module.exports =
[
    "Banged in short and outside off, pulled to long-on.",
    "he opens the face of his bat on impact with this shortish ball outside off and glides it to deep third man",
    "full and just a shade outside off, he looks to drive with his feet in cement, gets an inner edge that dribbles" +
    " past the stumps",
    "on a length and outside off, steered past a diving backward point to third man",
    "carved towards deep third man from outside off via a thick edge",
    "leading edge - pops in between covers and the bowler. This one held up in the pitch",
    "pitched up and outside off, the striker is crease-bound as he drives, thick outside edge to third man",
    "he shortens his length and outside off, carved to third man",
    "on a fuller length and outside off, pressed to the covers for a quick single. The fielder had one stump to aim " +
    "at, hits it but the batsman is in",
    "back of a length and on middle, guided to the left of short fine leg",
    "makes room outside leg, the bowler follows him, patted towards mid-off",
    "looped up and spins away, dabbed in front of cover-point",
    "flighted and outside off, sticks in the pitch. Check-driven to long-off",
    "slower ball on off at 126ks, pushed to long-off",
    "on a fuller length and outside off, he chips a drive past the covers",
    "shortish on leg, he does not connect with the pull. Off the shoulder in front of square leg. He may have gotten" +
    " an edge on that, given as a run",
    "slower ball on off, down the track, he adjusts and drags it to deep midwicket",
    "full and outside off, cracked to sweeper cover",
    "picked away to deep midwicket",
    "full and outside off, dragged to mid-on off the inner part of the bat",
    "shortish and rises on off, guided to deep third man",
    "back of a length and outside off, shovelled past midwicket",
    "fractionally short and outside off, camps back and mis-hits a pull over square leg",
    "short and climbs outside off, he rises with it and punches it up and over cover-point",
    "on a back of a length and on off, whipped to midwicket for one",
    "flicked in front of square",
    "fuller and on middle and leg, swept behind square leg",
    "back of a length and on middle, advances and tucks it to leg off the inner part of the bat",
    "takes this short ball from outside off and flat-bats it to long-on, on the bounce",
    "bumpy short ball, gets very big on him, who hops up and possibly gloves it behind square on the off side",
    "back of a length and outside off, cudgelled to sweeper cover",
    "picked away off the pads behind square on the leg side",
    "pitched up and on a fourth-stump line, flits down the track and drives it to long-off",
    "flat on the pads, slog-swept hard to deep square leg",
    "outside off with some extra bounce. Dabbed awkwardly to the right of the keeper",
    "fuller in length, down the track and slashed to third man off a thick outer edge.",
    "on a length and outside off, crashed to long-off",
    "slower ball at 110ks, check-pushed to long-off",
    "fuller and on middle and leg, tucked away backward of square on the leg side",
    "back of a length and on the hips, eased to long leg",
    "low full toss on off, dragged to long-on",
    "swiped to long-on with plenty of bottom hand",
    "banged in short and hurries on, Miller loads up for a pull and gets an edge behind square leg",
    "low full toss on the leg stump, whipped away to deep midwicket. THe non-striker wants two, but is sent back. He" +
    "\ dives and beats the throw from the deep",
    "low full toss on the stumps, dragged to deep midwicket. No mix-ups here",
    "another low full toss, clubbed to deep midwicket. The striker attacks the ball and keeps it to a single.",
    "skips down the track again. He is wary of it as he drags his length back. Punched through cover-point",
    "much better, cramps hi up for room. Tucked in front of square on the leg side for one",
    "fuller and on middle, drilled ram-rod straight, so much so the drive hits the stumps at the non-strikers; and " +
    "runs away towards mid-on. Hendricks did bent low but didn't finger-tip it away",
    "back of a length and outside off, he aims to punch it through the covers. Manages an inside edge that sneaks " +
    "away in front of square on the leg side",
    "looped up slow on middle, flicked towards midwicket for one",
    "much quicker on the leg stump as he steps away, goes low for a sweep. Mistimes it as the ball goes only as far " +
    "as in front of square leg",
    "down the track and punched to long-on. The bowler had shortened his length",
    "back of a length and outside off, punched to the covers, where the fielder dives to his right, tries a direct " +
    "hit and misses. Had ne nailed the stumps down, the striker was a goner",
    "full on the pads, whipped to mid-on",
    "back of a length and outside off, slapped to sweeper cover",
    "drives this full ball outside off to long-off",
    "picked away off the pads through square leg. There is protection in the deep",
    "length, driven to long-on",
    "back of a length and outside off, punched off the back foot to long-off",
    "pushed through on middle, short-arm pulled to long-on",
    "pushed through on off, opens the face at the last instant and guides it to short third",
    "Warner pulls this half-tracker from outside off to long-on",
    "starts off a new spell badly. On a length and outside off, flashed to third man off an outer edge.",
    "shortish and angled in, helped away in front of square leg",
    "fuller length on off, clears his front leg and scythes it over the covers",
    "too full and straight, clipped away to long leg",
    "low full toss on the pads, he gets away. He flicks it to deep square leg",
    "the bowler hunts for a yorker, slips in another low full toss. Driven to long-off after backing away a touch",
    "low full toss again, he camps back and clips it through square leg",
    "Warner steps away outside leg, chases him with a fullish ball, which is punched to long-off.",
    "slid through on middle, backs away and punches it wide of point",
    "darted outside off from round the stumps, drilled to long-off",
    "backs away, takes it from a middle-stump line and chops it towards sweeper",
    "full and outside off, nips down the track and lashes a drive to long-off",
    "slid through outside off, down the track. He seeks to pull and ends up dragging it to long-on",
    "swiped from outside off to long-on",
    "slider on off, dabbed in front of point with soft hands",
    "full toss on middle and leg, hacked away to deep midwicket",
    "fired on the leg stump, whisked to leg",
    "short on the stumps, he hangs back and punches it past a diving bowler to long-on",
    "Slower short ball outside off, he reaches out and chops it towards point",
    "shortish and hurries on off, he manages an inside edge onto the pads. The ball rolls to off and they sneak one",
    "on a length and outside off, laced past the covers. Sweeper tidies up",
    "Warner steps away outside leg and pushes this low full toss to long-off",
    "change of pace outside off, chipped in front of long-off. Fooled by the slower one",
    "veering down leg, helped fine on the leg side. The fielder has it covered in the deep",
    "he steps away outside leg, The bowler follows him with a full toss. Whipped behind square",
    "low full toss on the pads, picked away to long leg",
    "he makes room outside leg, the bowler follows him with a full ball. Struck on the pads and they rush across for" +
    " a leg bye. There is a shy at the stumps but misses the direct it. Given as a run, though",
    "full and outside off, flat-batted thump back to the bowler, who bends down in his follow through and takes some" +
    " pace off it, deflecting it towards long-off. They steal one",
    "low full toss on off, hacked to deep midwicket as the striker yanks his bottom hand off the bat and miscues it",
    "yorker at the base of off, squirted in front of the covers",
    "fullish and angling away outside off, plays away from the body and gets a thick outer edge that dies in front " +
    "of gully. He flings to his left and stops the ball. He recovers, gets on his feet and misses the direct hit. Had " +
    "he nailed the stumps down, the striker would have been out",
    "pushed through on middle and leg, whisked in front of midwicket for one",
    "Baz runs down the track, drags his length back outside off. Lashed over the covers. Off the bottom of the bat, not " +
    "middled",
    "steps away outside leg, he slips in a straight ball, which is chipped over the bowler. He wanted to loft it " +
    "forcefully but did not get enough power",
    "full and on the pads, clipped through midwicket",
    "Darted shortish and outside leg, he steps down the track and drags it to long-on off the inner part of the bat",
    "back of a length on off, punched into the gap at the covers",
    "picked away off the pads in front of square. The batsman is off for one",
    "Raina opens the face of the bat on impact with this length ball outside off and glides it to deep third man. He is " +
    "halfway down for the second. Slips and his partner turns back. He dives and is safe. the fielder involved misses " +
    "the direct hit",
    "back of a length, flicked away behind square",
    "shortish and outside off, he hops up and works it to the left of the bowler, in front of mid-on",
    "slower lifter on off, he can't manufacture his own pace. Pulled backward of square leg",
    "fuller and straight, tucked away through midwicket",
    "pushed in front of point for one",
    "short and cramps him for room, pulled to the right of short midwicket",
    "fuller and around off, shuffles across, takes a step forward and flicks it in front of square on the leg side",
    "134ks length ball on off, knocked in front of point for one",
    "flatter and quicker outside off, camps back and punches it to long-on",
    "down the track and dragged to long-on",
    "quicker one, keeps alarmingly low. He stoops low with it and flicks it tentatively through midwicket",
    "flat and fired on the stumps, jabbed to long-on",
    "shortish and outside off, turning ball, going away outside off flat-batted to long-off",
    "down the track and worked through midwicket",
    "pushed through on off, he advances and flat-bats it to long-off",
    "shortish and gets some assistance from the pitch, cramping the batsman for room. Turned to leg",
    "leg-stump ball, helped to long leg",
    "banged in short and hurries onto him, who plays a reasonably controlled pull to deep midwicket",
    "banged in short and rises on off, he opens the face of the bat and glides it to deep third man",
    "flatter and quicker on leg, whipped through midwicket",
    "looped up outside off, he held this one back. Checks the lofted-drive and chips it over the covers",
    "back of a length and outside of, pushed down to mid-off",
    "comes down the track, the bowler bangs it short. Mishit over the bowler's head",
    "pitched up and outside off, driven in the air. Sliced in front of mid-off. A little fumble there, but no harm done",
    "nips down the track, slower ball. Dragged to long-on",
    "slower ball on off, he pulls all the pace off it again. dabbed behind point",
    "this time he backs away, the bowler follows him. Tapped to backward point",
    "yorker outside leg, jabbed through the covers",
    "dug in shortish and outside off, suspect that was a slower ball, flat-batted to the off-side sweeper",
    "dug in shortish and outside off, dragged to mid-on. Just a single",
    "fired full and outside off, the batsman steps out, edges it to the left of the keeper, who gets a glove, keeping " +
    "it to one",
    "fractionally short and outside off, dragged to long leg off the inner part of the bat",
    "back of a length and on middle, clipped to mid-on for one",
    "fuller and outside off, he shuffles across and helps it to third man",
    "dug in shortish and outside off, slashes and gets a thick outside edge that flies in the air.... Dies in front of " +
    "third man",
    "fullish outside off with a hint of away movement, squirted to third man with an open face",
    "on a length and outside off, dabbed to third man",
    "on a length and swerves in, pushed to the right of mid-on, who gets across and limits it to one",
    "wide line outside off, waits on it before guiding it to third man again",
    "on a length and outside off, this time the striker wants to drive with no feet movement, has to settle with an " +
    "inside snick towards fine leg",
    "length and outside off, steered to third man",
    "quicker on middle, gets an inside edge in front of square on the leg side",
    "flat on middle and leg, squirted to long leg off an inner edge",
    "slid through on off, punched past a diving long-on",
    "quicker on middle and leg, he sinks to one knee and sweeps it behind square on the leg side",
    "slower through the air and full on off, tapped to backward point with an open face",
    "flighted and outside off, driven to long-off",
    "punched down to long-on for one",
    "fullish on the leg stump, bunted to long-on",
    "quick on middle, he backs away and chops it to short third man",
    "picked away off the pads to backward square leg",
    "hurrying ball on middle, punched out towards cow corner",
    "full and on middle, hacked to long-on off the inner part of the bat",
    "drifting onto the pads, helped away to deep backward square leg with a controlled sweep",
    "drifts in on middle and leg, eased to long leg",
    "extra bounce outside off, pushed to the covers",
    "straying on the pads, tucked away through midwicket",
    "much quicker through the air, flatter, dragged to long-on",
    "pitched up on off, driven through the covers with an open face",
    "full toss, bunted down to long-on",
    "drifts on the pads, worked in front of square leg",
    "flatter and on middle, pushed to the covers for one",
    "veering onto the pads, nudged to the right of short midwicket",
    "leg-stump line, turned through midwicket",
    "fullish and on off, nudged in front of square on the leg side",
    "on a length and on middle and leg, punched down to long-on.",
    "back of a length outside off, plays a checked punch towards mid-off",
    "length ball on a tight off-stump line. Stays in the crease and bunts it into the covers with soft hands",
    "full-toss on off stump, pushed to mid-off for a quick single",
    "length ball on off stump. He makes a lot of room and slaps it to cover",
    "down the track now, and tries to smack the wide length ball back down the ground. Inside-edges it instead, sends " +
    "it rolling towards short fine leg",
    "another slower ball, back of a length on off. Maxwell goes back and across and dabs it to third man",
    "much fuller now, and he can't get any elevation as he shapes to play a similar shot, ends up jabbing it along the" +
    " ground, into the covers",
    "shuffles a long way across, and flicks the low full-toss to deep square leg",
    "length ball outside off. He leans back and clubs it towards long-on",
    "full on leg stump, clips it towards short fine leg",
    "back of a length, angling in from wide of the crease, towards off stump. Tucked away towards midwicket",
    "goes on the back foot now, pushed through quicker, and punches into the covers",
    "down the track now, clipped towards backward square leg",
    "length ball, turning sharply into the pads. whips it towards short fine leg",
    "slower ball outside off, slapped towards deep point",
    "slower ball on off stump, comes forward and pushes it to cover",
    "very full close to off stump, can't get any real power on his drive, straight towards cover",
    "another slower ball, wider this time, and he shuffles across and looks to launch down the ground, bounces towards long-on",
    "slower ball, may have been a wide because it seemed to be just outside the tramline outside off, but the batsman " +
    "had moved across and he managed to flat-bat it and drag it down to long-off",
    "full-toss on off stump, angling into the batsman and tucking him up. He looks to swat it leg-side, can only " +
    "inside-edge it into his back pad and send it rolling towards short fine leg",
    "down the track he comes, clips against the turn to deep midwicket",
    "out of his crease again, makes room this time, and lifts the off-stump ball down the ground, to the left of long-off," +
    " who manages to run around and field it",
    "sees him shaping to step down the track and bowls a back-of-a-length ball just outside off. He manages to poke it " +
    "away towards deep point",
    "slower low full-toss outside off, drives but can't beat cover",
    "another low full-toss, a bit of width too, and he can't beat cover with a firmly struck drive",
    "tried to make room to hit through the off side. The bowler banged it in a touch shorter and he toe-ended it towards" +
    " third man",
    "length ball on middle and off. Swiped to deep midwicket, and he has only conceded six off his final over.",
    "slower ball, very full on leg stump, clipped to midwicket",
    "slower ball on off stump. Gayle clears his front leg and swats it to deep square leg",
    "back of a length, straight. Gayle tucks it off his hips through backward square leg",
    "fullish on middle and leg, driven towards long-on",
    "length ball, keeps it close to the body, and he opens up at the hips and swats it towards deep midwicket",
    "slower ball outside off, stands tall and flat-bats it past the diving short extra cover fielder, to the left of " +
    "long-off",
    "slower ball on off stump. He makes a bit of room and flat-bats it to long-off",
    "another slower ball, wide outside off, drags his pull to deep midwicket",
    "full and wide again, and he slices it in the air, one bounce down to sweeper cover",
    "full slower ball outside off. The batsman is down on one knee to drag it to deep midwicket",
    "slower ball again, on a fullish length outside off, swings at it and doesn't connect too cleanly, rolls down to long-on",
    "slower ball, angling in towards off stump. he presses forward and pokes it into the covers to pick up a single",
    "slower ball again, on middle stump. he makes a bit of room and chips it over mid-off",
    "slower ball again, shorter now, angling into the body. AB looks to pull, drags it squarer than he'd like, towards" +
    " deep square leg",
    "full and flat on middle and leg, clipped into the vacant midwicket region, and the bowler sprints to field it",
    "length ball angling into off stump, plays the checked drive to long-off",
    "very full outside off. Makes swinging room and swipes it down to long-on",
    "slower ball on middle stump, angling in and denying the batsman room. Pushed into the covers",
    "low full-toss on middle stump, down on one knee to swing it away to deep midwicket",
    "sees him making room and bowls it flat and straight. Swipes it down to long-on",
    "down the track and he fires it full, angling into the batsman. Jabbed towards square cover",
    "follows the batsman as he comes down the track, moving towards the leg side. Goes for the big hit, drags it in the" +
    " air to the right of deep midwicket, drops well short of him",
    "speared full and flat on off stump, slapped to sweeper cover",
    "shorter now, on off stump, and he clears his front leg and flat-bats it to long-off",
    "he is gifted with a high full-toss, heading towards the right shoulder of the batsman. Takes his eyes off it as he" +
    " half-fends, half-pulls, and it goes off the edge towards short third man. Slipped out of his hand there",
    "fuller now, and this time he connects with the lap from outside off, but hits it straight to backward square leg",
    "another slower ball outside off, clubbed to long-on",
    "full on off stump, driven down to long-off, and they get a single",
    "shot. That's nice and full outside off and he gets a big stride forward to play a firm drive into the ground. " +
    "Bounces over short cover, who jumps in the air to palm it away",
    "length ball on off and middle, tucked away towards deep square leg",
    "length ball on off stump, pushed with a nice straight bat towards mid-off",
    "straighter now, on off and middle, and the striker, who was initially backing away towards the leg side, swipes it" +
    " to mid-on, not quite middling it",
    "back of a length close to off stump. He rides the bounce and drops the ball into the covers with soft hands",
    "back of a length on off stump, whipped wristily to deep square leg",
    "angled into the pads again, clipped towards midwicket",
    "fuller and straighter, swept to deep square leg",
    "dropped! The ball is following the batsman's body here. He pulled a shortish ball from a fair way outside off, " +
    "using his wrists to play the shot in the direction he wanted. He wanted to get it wide of short fine leg, but it " +
    "was close enough to him to dive to his right and get a hand to it, but it didn't stick",
    "tossed up slower outside off, driven to long-off",
    "back of a length on off stump, he lets it come on and guides it towards third man",
    "back of a length outside off, dabbed away to third man",
    "tossed up outside off, pushed to sweeper cover",
    "length ball on off stump. He goes on the back foot to whip to long-on",
    "length ball on middle and leg and he's a touch too early to close his bat face to flick, and it goes off the " +
    "leading edge towards third man",
    "again he goes back to a length ball, this time it's on off stump and he punches it to sweeper cover",
    "pitched from off and going on to middle, the batsman goes on the back foot to work it towards midwicket",
    "down the track and this time he gets to the pitch of the leg-stump ball to drive to long-on",
    "shortish ball close to off stump. He stands tall and drops it into the off side with soft hands to pick up a single",
    "shortish, angling into the body, and the batsman leans backwards at the waist and lets it come on and run off the" +
    " face of his bat to the left of third man",
    "tossed up slow and full on middle stump, worked away to deep midwicket",
    "goes back to a length ball on off stump, not much turn, whips it away to deep midwicket",
    "shortish outside off. He hops in the air to ride the bounce and steer it to third man",
    "slower bouncer outside off, and he gets into an uncomfortable position to play a half-pull, half-whip that just " +
    "eludes short fine leg, running to his left",
    "on the pads now, tucked away to deep square leg",
    "slower short ball and Pollard is through his pull too quick, drags it off the inside edge towards short fine leg",
    "flat and shortish on off stump, stops on the pitch and he can only club it to long-on",
    "back of a length outside off, whipped to long-on",
    "fuller now, still quite flat and quick. Drags it from outside off to drive towards long-on",
    "tossed up a bit slower, angled into off stump. He is on the front foot to push into the covers",
    "short on off stump, pulled to deep square leg",
    "low full-toss on off and middle. He moves away from the line and jabs it down to long-on",
    "back of a length on off stump, turns away and Pollard dabs it delicately to the right of the keeper",
    "length ball outside off, moves away. He goes on the back foot and taps it gently towards backward point",
    "shortish outside off. Pollard lets it come on and picks up a dabbed single to short third man",
    "a bit of extra bounce now, cramps the batter for room as he goes on the back foot. Plays with a straight bat, " +
    "punches to long-off",
    "tossed up slowish outside off. He stretches out and pokes it to backward point",
    "fullish on off stump, whipped to long-on",
    "fuller now, on off stump, driven firmly down the ground and the bowler's right foot gets in the way. If not " +
    "inadvertently, certainly not entirely advertently",
    "down the track now, hits it in the air, with the line, doesn't quite get hold of it, and it drops just short of the" +
    " man diving in from long-on",
    "back of a length, punched to sweeper cover",
    "goes on the back foot looking to make room to hit through the off side. Moves in sharply and tucks him up for room" +
    " and he punches it away towards sweeper cover",
    "fuller now, outside off. Goes deep in his crease to dab it towards short third man",
    "shortish on off stump, pulled along the ground to deep midwicket",
    "slower yorker, angled into the batsman's feet. Swipes at it and it rolls down towards long-on",
    "length ball on off stump. The striker opens up and looks to flat-bat it down the ground, ends up edging it towards" +
    " third man",
    "very full outside off, goes deep in his crease and swats it towards long-off",
    "full and wide, driven straight to extra cover",
    "full-toss on off stump, opens out and swipes it to long-on",
    "length ball on off stump. he gets his front foot across to tuck it towards wide mid-on",
    "shortish on middle and leg, pulled towards deep square leg",
    "slower ball on off stump, comes forward and clips it through midwicket",
    "another slower ball, dips towards the front boot, and he flicks it away to deep square leg",
    "angled into off and middle, tucked away towards deep backward square leg",
    "back of a length on off stump. He lets it come on and dabs it to third man",
    "angled in towards off stump, on a length. he makes room and slaps to point and takes off for a quick single. May " +
    "have been close had the throw hit at the bowler's end",
    "shortish ball rising towards the ribcage. He hops to dab it down in front of him for a quick single. The fielder " +
    "is quick to the ball and tries to slap it onto the stumps at the keeper's end while sprawled on the ground, doesn't" +
    " hit them",
    "short, skiddy ball. The batsman is a bit late on the pull, rolls towards backward square leg",
    "tossed up on middle stump, whipped to deep midwicket",
    "back of a length, angling into the body, tucked away towards backward square leg",
    "back of a length on off stump, pushed towards mid-off",
    "back of a length outside off, dabbed to third man",
    "length ball on off stump, defended towards short cover and they run a quick single",
    "tossed up full on off stump, driven to long-on",
    "tossed up outside off, driven to long-off",
    "down the track, whips it from off stump towards deep midwicket",
    "down the leg side now, I don't know how much bat he got on that sweep, rolls down to short fine leg",
    "back of a length on off stump, makes a bit of room and plays that typically surgical chop down to third man",
    "tossed up fuller, on off stump, worked away wristily through midwicket after taking a big stride forward",
    "back of a length outside off, dabbed towards short third man",
    "uppish, looking to slash at a length ball by making room. Ends up slicing it in the air to the right of point but " +
    "it bounces short of him as he dives to try and catch it",
    "down the track and hits with the turn, in the air but on the bounce to deep midwicket",
    "length ball outside off, stays on the back foot and punches towards deep cover",
    "length ball outside off, stays in his crease and pushes it with soft hands into the off side for a quick single",
    "down the track to a loopy, dipping ball on off stump, drives it to long-on",
    "flat, angling in towards middle and leg. Goes back and across and nudges it into the on side",
    "down the track again, meets the ball with a straight bat to drive to long-on",
    "short and wide again, this time it stops on the pitch and he hits it to sweeper cover",
    "shortish slower ball on off stump, whipped away to deep midwicket",
    "short ball to start the spell, pulled away to deep midwicket",
    "shortish again, pulled towards deep square leg",
    "slower ball on leg stump, tucked away towards short fine leg",
    "low full-toss outside off, sliced away to sweeper cover",
    "slower short ball wide outside off. He reaches out and plays a checked uppercut to land it short of the sweeper " +
    "cover fielder",
    "slower ball, full and wide outside off, driven towards extra cover",
    "slower ball, full and wide, steered towards sweeper cover with an open face",
    "short ball, is too quick to pull, and he's lucky the top-edge fell in no-man's land, a long way to the left of and" +
    " in front of short fine leg",
    "full and wide now, slapped down to long-off",
    "full-toss on off stump, whipped to long-on",
    "short again, angling into the body. He swivels, pulls between long leg and deep square leg",
    "back of a length ball on off stump. Stays in his crease and dabs it softly into the off side for a quick single",
    "shortish, sits up at waist height, and that is superb fielding, sprinting to his right from deep square leg " +
    "and sliding to stop that crisply timed pull. Made the stop look so easy",
    "yorker on middle and leg, clipped to deep midwicket",
    "this time he gets the off-stump yorker right and he can only jab it firmly into the ground and send it " +
    "bouncing over the bowler's head",
    "shortish slower ball on off stump, swiped towards midwicket",
    "shortish and slid down leg, pulled past short fine leg. The batsman wants two, but his partner denies it",
    "back of a length on leg stump, slugged away to deep midwicket. The field can spread",
    "it's a short ball that's sliced to point",
    "down the track, but the bowler flattens his trajectory. Slapped to long-on",
    "down the track and heaves the flat delivery down the ground. It's too quick for him though, it throws him off " +
    "balance and it's got no timing. Long-off keeps it to a single",
    "hits the yorker on middle, nudged to midwicket for a quick single",
    "full on leg stump, whipped through the leg side for only a single",
    "it's a low full toss outside off, the batsman is forward and crouches to lap the ball over to long leg. Could have" +
    " been two, but the captain disagrees. He wants it",
    "back of a length and cramping him up, Warner rolls his wrists to find midwicket",
    "shortish on middle and leg, Warner taps it down to mid-on",
    "goes short and sliding down a touch. He swivels in the crease for a pull. But all he does is spoon the ball towards" +
    " midwicket. Lucky there wasn't anyone around",
    "loads up a full toss, driven with the angled bat to deep point",
    "picked up the slower ball early again, waits for it to reach him and cuts to deep point",
    "a hint of width and the striker looks to exploit it. Goes for a crack through the covers, but the four-man off-side" +
    " ring can't be breached",
    "half-volley outside off, he crunches it to the sweeper",
    "shortish on middle, camps back in his crease and heaves it to deep midwicket",
    "looks for the yorker and lands it quite well. He digs it out into the covers",
    "misses the spot and Warner doesn't manage enough of a connection. Clears the front leg and goes for a slash, ends " +
    "up with an inside edge towards midwicket",
    "another near yorker, he was looking for a slice through the off side. has to accept an inside edge for a single" +
    " to the keeper",
    "saw the batsman running away outside leg again and follows him. Hits the blockhole too, so only a single through " +
    "the covers",
    "goes back and taps a good length ball to long-on",
    "tossed up outside leg, he nudges it to the left of where mid-on would have been. As such, the bowler has to chase" +
    " after the ball himself",
    "down the track, heaves a full toss down the ground to long-off.",
    "whipped off his legs to deep square leg, that's a full toss as well",
    "low full toss on leg stump, thumped down to long-on. So powerfully hit that it's only one. Great work from the " +
    "fielder there too, diving away to his right",
    "full on leg stump, nudged to long-on",
    "shortish and outside off, slashed to the sweeper",
    "dropped! The culprit is at point, coming right at him, doesn't even have to move. It was a fuller ball with some" +
    " width. The batter goes for a slash, but hasn't got the elevation he wants",
    "full on leg stump, squeezed to long-on",
    "tossed up outside leg, lifted to mid-off. That seems something like a knuckle-ball. Pushed through off the front " +
    "of the hand",
    "moves outside leg, the bowler loops it outside off. Ends up a full toss. The striker reaches it and slaps it " +
    "through the covers.",
    "fuller delivery outside off, dabbed into the covers for a single",
    "great work! Dives to full-length to his left to hold a cut down at short third man. The striker had done well too," +
    " to wait for the ball and try and beat the man. Comes out second best though",
    "down the track to push a good length ball to long-off",
    "follows the batsman's move down the leg side, he swipes it away to long leg.",
    "down the track, but he fires the ball at the batsman's legs to cramp him. The man can only push it into the covers" +
    " for a single. Doesn't like that he's been pinned down like that",
    "flat, angling down leg, tickled to short fine leg and they run a quick single",
    "and again, some bounce. He stays next to the line and steers it to third man",
    "again, he's kept it there or thereabouts, in that channel outside off, just back of a length. This one shapes away" +
    " slightly, and he dabs it away to third man",
    "back of a length, gets up to chest height. He rides the bounce and knocks it down to the right of third man",
    "back of a length, angled in from wide of the crease, worked away off the back foot through the leg side",
    "fired in a bit quicker, angling into middle stump. The striker stays in his crease and whips it towards short fine" +
    " leg",
    "slower ball now, back of a length, comes in a touch towards leg stump. He goes back to flick it, ends up inside-edging" +
    " into his thigh pad",
    "length ball outside off, a bit of curve away. He pushes at it with an angled bat and hits it uppishly towards point",
    "off-stump yorker, a bit of wobble, and the batsman jams down on it and steers it towards third man",
    "a bit slower and Maxwell sweeps to deep backward square leg",
    "full outside off. He comes forward to steer towards deep point",
    "length ball on leg stump, tucked away towards deep midwicket",
    "a bit slower and Miller stretches out to lap-sweep to long leg",
    "a bit straighter and he goes on the back foot to tuck it away to deep backward square leg",
    "length ball outside off, pushed towards short cover for a sharp single",
    "a touch shorter and he goes on the back foot to work it against the turn through midwicket",
    "tossed up on off stump, driven to long-off",
    "quickish again and he is on the back foot to a length ball. Pushes hurriedly at it to send it rolling towards long-on",
    "length ball spinning in towards off stump, worked away through square leg",
    "sees him coming down the track and bowls it flatter and a touch shorter. Good use of the wrists to tuck it away " +
    "through square leg",
    "a touch shorter and he has time to let it come on and nurdle it to deep backward square leg",
    "length ball on middle stump, worked away through the leg side",
    "slow again and Miller is in position a long time before he can play a controlled, checked paddle from outside off " +
    "towards square leg",
    "quicker now, goes with the angle into the pads, and he clips it away through square leg",
    "tossed up on off stump, swept to deep square leg",
    "now he is down the track and the bowler bowls it quick and flat. Taps it into the on side to take the single",
    "length ball on the pads, tucked away through backward square leg",
    "short outside off, chopped away to the right of sweeper cover",
    "flatter now, goes with the angle towards off stump. He stays leg side and punches it through cover",
    "down the track now, gets to the pitch of the flighted ball outside off and drives to long-off",
    "full and wide, flat-bat drive to sweeper cover",
    "slower ball outside off. Comes forward, lets it come on, and dabs it towards short third man",
    "back of a length outside off, slapped away to sweeper cover",
    "down the track and Bravo bowls it right up to him, outside off. Jabs it away through midwicket",
    "back of a length on middle and off, worked away towards deep midwicket",
    "slower ball wide outside off, he half-sweeps, half-drives to long-on",
    "tossed up on middle stump, driven to long-on",
    "nice and slow from the bowler, who saw him coming. Doesn't get to the pitch, and it stays with the angle and cramps" +
    " him, and he stabs it away towards point",
    "sweeps now, from outside off to deep backward square leg",
    "low full-toss wide outside off, Axar plays a bottom-handed drive to long-off",
    "down the track again and this time the bowler follows him with the blockhole ball. He clips it to long-on",
    "fuller now and he goes for the big drive, doesn't middle it at all and it slices over mid-off, to his right",
    "slower ball on a good length on off and middle, and he swats it away to deep midwicket",
    "length ball outside off, leans his head over the ball to drive, but ends up slicing it off the outside half of it " +
    "towards third man",
    "length ball on middle stump, defended to short midwicket",
    "back of a length on off stump, pushed into the covers for a quick single",
    "back of a length on off stump, worked away through square leg off the back foot",
    "length ball on off stump. He sits on the back foot to dab it down to third man",
    "back of a length outside off, steered to third man",
    "length ball angling in towards off and middle. Raina shuffles across to clip it through backward square leg",
    "slowish length ball on the pads, tucked away towards deep midwicket",
    "tossed up slow and alluringly, and he comes down the track and it becomes a low full-toss that he whips back " +
    "towards the bowler, who gets down to his right and deflects the ball towards midwicket with his hand",
    "slower ball outside off, dabbed off the front foot towards cover point and they sneak a quick single.",
    "on the pads now, nudged away towards deep square leg",
    "tossed up outside off and he plays the no-look over-the-head lap-scoop to the left of the keeper",
    "back of a length outside off, punched towards point",
    "tossed up outside off, presses forward, lets it spin into him, and dabs it towards short third man",
    "flat, angled into the pads, worked away to deep square leg",
    "loopy delivery outside off, worked with the turn to long-on",
    "a touch short, angling into leg stump, and Faf goes deep in his crease to pull to deep midwicket",
    "length ball on off stump, nudged with the turn to deep square leg",
    "length ball on middle and off, he comes forward to play a defensive push to long-on",
    "slower ball outside off, quite full. He jabs at it with an angled bat to slice it to the left of point, where he " +
    "reaches out with one hand and fails to cut it off",
    "fullish ball outside off, checked drive to long-off",
    "length ball outside off, lets it come on and steers it to deep point",
    "fuller and quicker on off stump, plays a quiet checked drive through the covers",
    "down the track, swipes with the turn from off stump to long-on, all along the ground",
    "skips out of his crease, makes a bit of room to drive inside-out to sweeper cover",
    "full on the pads, clipped to deep midwicket. This is like the middle overs of a 90s ODI",
    "quickish length ball close to off stump. He hangs back and chops it towards point",
    "tossed up slow and loopy on off stump, worked with the turn through square leg",
    "tossed up on leg stump, swept to deep square leg",
    "length ball outside off, whipped away through square leg",
    "length ball on the pads, worked away towards deep square leg",
    "a touch shorter and he goes back in his crease to tuck it away into the leg side and bring up his half-century",
    "down the track and he swats the loopy full-toss to deep midwicket",
    "down the track now, driven to long-off",
    "length ball on off stump, quietly dabbed to the right of backward point",
    "length ball on the pads, tucked away to deep square leg",
    "short slower ball, pulled to deep midwicket",
    "short ball outside off, pulled to wide long-on",
    "full slower ball on off stump, plays a checked drive to sweeper cover",
    "back of a length slower ball wide outside off, steers it to third man",
    "back of a length on off stump, he is watchful as he plays it under his eyes and dabs behind point",
    "shortish and outside off, waits on the back foot and runs it towards third man",
    "short and a touch wide, the bounce on this pitch can be trusted like a best buddy, rides to third man again",
    "good length ball outside off, he steps forward and pushes into the covers. The fielder isn't quick enough to stop " +
    "the single",
    "good length and outside off, slid off the open face to deep third man. Lovely batting from these two. They've " +
    "assessed the situation so early and so well. Not fooled by the grass on the pitch",
    "shortish on off stump, he lets it come on and flicks it behind square leg",
    "good length ball on off stump, softens his grip and defends towards the covers. Quick single, easily taken. No " +
    "surprise there",
    "this is short, and he is too eager on the pull. Punches the bat at the non-strikers' at having secured only a " +
    "single. Bad mis-hit",
    "slower ball outside off, he gets down and runs it through to third man. The fielder keeps it to only a single",
    "shortish on middle and leg, nudged towards midwicket",
    "goes wide of the crease for a shortish delivery on middle and leg, tucked away through midwicket",
    "fullish on leg stump, flicked to the man at deep midwicket",
    "gets down the track to the spinner straight away, nudged to long-on",
    "stays back to a short ball and cuts to the sweeper",
    "shortish and outside off, cracked to the sweeper again",
    "short delivery, he winds up and flat-bats it towards long-on. Only the legs get in the way even as he tries not to." +
    " Hits him despite doing the splits",
    "shortish on middle and leg, defused into the midwicket region",
    "shortish on middle and leg, swivel pulled to deep square leg",
    "full on off stump, pushed to long-off",
    "reaches the pitch after using his feet and drives wide of long-on",
    "shortish and outside off, punched to long-off",
    "holds it back and manages to snag the outside edge as he steps down again. Closed the face too early, and gets a " +
    "single to third man",
    "flicked away through square leg.",
    "shortish and outside off, run towards point and he's snagged another rapid single",
    "stands up tall against a shortish delivery outside off, punched through the covers",
    "full on leg stump, whipped towards long-on. A little way to his right",
    "shortish and outside off, he watches it and taps it on top of the bounce and sends the ball behind square.",
    "steps forward, and a little way outside off. Smeared through the covers",
    "too quick for that kind of shot. He was loading up for a pull, but the short ball skids onto him. Gets an inside " +
    "edge towards midwicket",
    "on off stump, driven through to long-off",
    "set up deep in his crease and slaps the short ball to long-off",
    "tapped down the ground to long-off. He's doing his bit well, rotating strike. but the bowler is bringing things " +
    "back with his changes of pace",
    "fuller delivery on off stump, pushed to long-on",
    "shortish on middle and leg, clipped to deep square leg.",
    "back of a length and outside off, tries to defend and gets an inside edge towards fine leg",
    "just a bit shortish on middle and leg, worked behind square leg",
    "shortish and outside off, slapped to deep point. Slower ball again, but not lobbed up full",
    "overpitched outside off, thumped down the ground. Could have been another boundary but he is prowling that area " +
    "and he slides to his right to save it",
    "full toss on middle, he looks to heave it down to long-on",
    "back of a length and outside off, slapped to the left of long-off",
    "moves away to leg and he follows him again, pushed through the covers",
    "shortish and outside off, goes for a front-foot swipe towards midwicket. But the slower pace beats him. Only gets " +
    "an inside edge to long-on",
    "terrific yorker on the base middle, dug out for only a single into the covers",
    "steps down the track while making room to meet the intended yorker on the full and slices it to deep third man",
    "looks for the yorker on off stump, sliced through the covers",
    "full toss on middle and leg, swiped to long-on",
    "full and outside off, sliced to the sweeper on the off side",
    "flat-bats a shortish delivery down the ground to long-off",
    "fuller and outside off, slugs the slower ball to long-on",
    "cramps him with a quick short ball at the body, swung away towards short fine leg. Inside edge, off the body.",
    "short of length ball around off stump, pushes this towards cover and takes a single",
    "shorter and angling in, he plays it with soft hands, drops the ball to the left of the bowler and zips through for" +
    " a single",
    "starts well, with a short of length ball from over the wicket, defended for a single",
    "short of length and just outside off, he pulls it gently towards midwicket for a single",
    "angling in towards the pads, pushed towards midwicket for a single",
    "similar length, he backs away from the stumps and guides that towards third man",
    "good length ball on leg stump, cramps him for room and taps it to mid-on",
    "shortish on middle, goes for a pull. It's mistimed and shoots towards long leg",
    "shortish on middle, he nudges it in front of square",
    "gets up off his toes and turns a shortish delivery off his hips to long leg",
    "good length ball on middle and leg, turned away to midwicket",
    "backs away to slice a back of a length delivery from well outside leg to point. Good work from the two men there, " +
    "but the throw misses the stumps when the batsmen weren't particularly interested in a run. Overthrows allow them " +
    "the luxury",
    "fuller delivery outside off, gets a toe-end to a swipe and finds a single at long-on",
    "back of a length and on off stump, slid down to deep third man",
    "backs away from a length ball and slashes it through to the sweeper",
    "shortish and on off stump, tapped to long-off. Not timed really",
    "full on middle, whipped to wide long-on",
    "makes a bit of room and cuts a shortish delivery through to deep point",
    "in the slot and it's drilled down the ground to long-on. Good work from the fielder there, running around to his left",
    "good length ball enjoys an outside edge to deep third man. Keep the ball up and it's moving just enough. Can't " +
    "understand their short ball ploy",
    "dropped by the bowler in his follow through! That's a shortish delivery on middle, goes for a heave but he gets it " +
    "off the splice. The bowler sticks his hand out, but that didn't stick. Also, the sightscreen behind him was " +
    "illuminated with an ad. Hard to spot",
    "shortish and outside off, punched behind point",
    "good length ball on off stump, was trying to slide it to third man but it's not possible. Settles for a single to " +
    "point. No room on offer",
    "fuller delivery outside off, hammered to long-on",
    "that time it is full, and it is skewed away towards third man. He rushes in, hoping to take a catch, but the ball " +
    "dies on him. Did well to get his body behind it though",
    "length ball, well wide of off stump, slashed away over the covers",
    "full and outside off, goes for a slash through the covers again. Gets an inside edge onto his pads and he drags " +
    "him through for a single",
    "another slower ball, with a little width, slapped through the covers",
    "back of a length on middle, swiped away to long-on",
    "short on leg stump, tucked away to short fine leg",
    "shortish and outside off, dabbed to deep third mna",
    "a hint of width and it's cut away through to deep point",
    "good length ball outside off, slices it to deep point",
    "backs away against a back of a length ball on leg stump, can't get the power behind a pull. Splices it to long-on",
    "low full toss outside off, driven to the sweeper on the off side",
    "just back of a length and outside off, slapped to long-on",
    "full on off stump, hammered back at the bowler. He just about gets a hand on it and deflects it to long-on",
    "full on off stump, pushed to long-on",
    "length on off stump, slogs away to long-on",
    "full on leg stump, clubbed to long-on",
    "hits the blockhole on off stump, only a single into the covers",
    "low full toss on off stump, thumped to long-off all along the ground",
    "well bowled, spears it into the blockhole and he can only nudge it towards the leg side.",
    "length ball on off stump. he goes back and across and nudges it away for a single behind square leg, reminiscent of" +
    " Graeme Smith",
    "fullish on the pads, a bit of inswing. He works it away towards square leg",
    "back of a length on off stump. He lets it come on and pushes it with soft hands towards point",
    "back of a length on middle and off and he clears his front leg to allow it to swing into him and whips it to square leg",
    "shortish and wide, slashed away to third man",
    "down the track he comes, throws his hands at a wide length ball and slices it in the air, one bounce to third man",
    "back of a length outside off, looked like a slower ball. He waited quite a while before slapping it down to third " +
    "man",
    "back of a length slower ball, angling into off stump. He is back and across even before the bowler has released - " +
    "that seems to be his default trigger movement - and he lets it come on and tucks it with the angle towards midwicket",
    "back of a length on middle stump, looking to tuck the batsman up. He bunts it towards mid-on for another quick single",
    "short outside off and this time he plays a whippy, wristy pull towards deep square leg",
    "slower ball on off and middle, worked away towards square leg",
    "another slower ball, not as full this time. He waits on the back foot and dabs it away to third man",
    "length ball outside off, stays deep in his crease to cut it towards third man",
    "back of a length outside off, another slower ball. Doesn't come on at all as he makes room, ostensibly to slap it " +
    "hard through the off side, and he ends up dragging it towards mid-off with a lot of bottom hand",
    "fullish outside off, poked away towards cover",
    "in the blockhole on middle and off, jams down on it and steers it down to third man",
    "slower ball on off stump, fairly full. He waits deep in his crease and pushes it with soft hands into the covers",
    "back of a length, angling in towards off stump, worked away through square leg",
    "full on off stump, and he stays leg-side of the ball (or comes back to his initial position after threatening to " +
    "shuffle across his stumps) and flat-bats it to the left of sweeper cover",
    "again, really slow on off stump, swiped away to deep midwicket",
    "full on middle stump, driven hard down the ground and AB slides to his left from long-on to save it",
    "shortish on off and middle, pulled to deep square leg",
    "length ball angling into the pads, goes on the back foot to work it into the leg side",
    "back of a length outside off, dabbed down to third man",
    "very full on off stump, swiped away towards deep square leg",
    "shortish outside off, slapped to sweeper cover",
    "full-toss wide outside off, slapped to sweeper cover",
    "slower ball outside off. He looks to slog it across the line, inside-edges into his pads",
    "short ball on leg stump and he doesn't get hold of the pull, goes high in the air and it bounces down towards deep" +
    " midwicket",
    "shortish now, pulled to deep midwicket",
    "shortish outside off, doesn't bounce much at all, he pulls towards deep midwicket",
    "back of a length outside off, punched to long-off",
    "slower ball, short, sits up on middle stump, pulled to deep midwicket",
    "widish length ball, driven towards sweeper cover",
    "slower ball on the pads, whipped to deep midwicket",
    "short outside off, chopped away towards point",
    "length ball angling across towards off stump, worked away through square leg",
    "slower full-toss on off stump, whipped to long-on",
    "tossed up on off stump, worked with the turn towards square leg",
    "full on middle and off, whipped to deep square leg",
    "a touch short, quite a bit of width, and he chops it away towards sweeper cover",
    "slower ball on off stump. He lets it come on and nurdles it towards square leg",
    "back of a length on middle and off. Jumps back and across to work it through midwicket",
    "full outside off, comes forward, plays a checked drive into the covers",
    "full-toss outside off, punched to long-off",
    "short and wide, cut away to the right of sweeper cover",
    "in the blockhole on middle stump, clipped to deep square leg",
    "length ball outside off, flat-batted to long-off",
    "slower bouncer, pulled towards deep backward square leg",
    "in the blockhole now, closer to off stump, driven down the ground to long-on",
    "in the blockhole on middle stump, swiped away towards long leg",
    "another yorker. He makes room, can't force it into the off side, it squeezes off the inside edge into the on side",
    "low full-toss on leg stump, swiped down to long-on",
    "fullish, leg-stump line, comes down the track, makes room. Plays the pick-up shot over backward square leg",
    "fuller and on the stumps, dragged to long-on",
    "low full toss on off, flat-batted to long-off.",
    "yorker tails in, dug out to leg side",
    "low full toss on the pads, worked to the right of short midwicket",
    "yorker at the base of middle and leg. Kept out",
    "slower one on off, he is early into the shot and chips it in the air to the right of the bowler",
    "back of a length and outside off, he kitchen-sinks it to the left of the man at sweeper cover. Diving save",
    "length outside off, slapped to sweeper cover",
    "full toss, which is hacked away to long-on",
    "pitched up on off, driven to long-off",
    "back of a length and on middle, opens his bat face and steers it to short third man",
    "full on middle and leg, clipped away backward of square leg",
    "good length with some away movement, tapped in front of mid-off",
    "well outside off with hardly any swing, guides it to third man for one",
    "swings it from length towards middle stumps, he defends it softly to cover and takes a very quick single",
    "bit too full on the pads, he drives it just wide of mid-on for one more",
    "closer to off stump now, he defends it gently towards mid-off and takes off for one",
    "bit of width outside off, he runs it down to third man for one",
    "bit of inside edge as he looks to push the outswinger towards the off side, but gets a single on leg after the edge",
    "well outside off with some shape, helped to third man for one easily",
    "picked away off the pads to long leg",
    "veering onto the hips, he can't help it on its way. Off the pad for a leg bye. He may have got an inside edge on that",
    "full on off, he shuffles across off and milks a single behind square on the leg side",
    "fetches this from outside off and swat-pulls it to deep midwicket",
    "shortish and outside off, sat up to be hit. Flayed to sweeper cover",
    "pitched up and curling away outside off, mistimed drive to mid-off",
    "opens the face of his bat on impact with this full offering outside off and dabs it behind point",
    "length on off, clipped to long-on for a jogged single",
    "back of a length on off, too close to cut. Yet he goes through with the shot. Chopped in front of the covers",
    "length and outside off, chipped in the gap at the covers",
    "banged in short on off, hangs back and drags a pull through backward square leg",
    "on a length and on middle, punched down to mid-on. They hesitate for a brief while before completing the single",
    "bouncer on off, aims to pull, mishits it behind square on the leg side",
    "worked through midwicket",
    "on a length and outside off, he camps back and steers it to third man",
    "slower ball on off, manipulates it behind square on leg side",
    "looks like a googly, punched down to long-on",
    "full on middle, whippily driven to long-on",
    "low full toss, tucked around the corner on the leg side",
    "Flatter and outside off, chopped through cover-point",
    "googly outside off, dabbed past a diving first slip to short third man",
    "He rocks back, fetches this from outside off and short-arm pulls to mid-on"
];