/*
 Created by Kunal Nagpal <kunagpal@gmail.com>
 GraVITas Premier League
 *  Copyright (C) 2014  IEEE Computer Society - VIT Student Chapter <ieeecs@vit.ac.in>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
module.exports =
[
    "Banged in short and outside off, pulled to long-on.",
    "he opens the face of his bat on impact with this shortish ball outside off and glides it to deep third man",
    "full and just a shade outside off, he looks to drive with his feet in cement, gets an inner edge that dribbles" +
    " past the stumps",
    "on a length and outside off, steered past a diving backward point to third man",
    "carved towards deep third man from outside off via a thick edge",
    "leading edge - pops in between covers and the bowler. This one held up in the pitch",
    "pitched up and outside off, the striker is crease-bound as he drives, thick outside edge to third man",
    "he shortens his length and outside off, carved to third man",
    "on a fuller length and outside off, pressed to the covers for a quick single. The fielder had one stump to aim " +
    "at, hits it but the batsman is in",
    "back of a length and on middle, guided to the left of short fine leg",
    "makes room outside leg, the bowler follows him, patted towards mid-off",
    "looped up and spins away, dabbed in front of cover-point",
    "flighted and outside off, sticks in the pitch. Check-driven to long-off",
    "slower ball on off at 126ks, pushed to long-off",
    "on a fuller length and outside off, he chips a drive past the covers",
    "shortish on leg, he does not connect with the pull. Off the shoulder in front of square leg. He may have gotten" +
    " an edge on that, given as a run",
    "slower ball on off, down the track, he adjusts and drags it to deep midwicket",
    "full and outside off, cracked to sweeper cover",
    "picked away to deep midwicket",
    "full and outside off, dragged to mid-on off the inner part of the bat",
    "shortish and rises on off, guided to deep third man",
    "back of a length and outside off, shovelled past midwicket",
    "fractionally short and outside off, camps back and mis-hits a pull over square leg",
    "short and climbs outside off, he rises with it and punches it up and over cover-point",
    "on a back of a length and on off, whipped to midwicket for one",
    "flicked in front of square",
    "fuller and on middle and leg, swept behind square leg",
    "back of a length and on middle, advances and tucks it to leg off the inner part of the bat",
    "takes this short ball from outside off and flat-bats it to long-on, on the bounce",
    "bumpy short ball, gets very big on him, who hops up and possibly gloves it behind square on the off side",
    "back of a length and outside off, cudgelled to sweeper cover",
    "picked away off the pads behind square on the leg side",
    "pitched up and on a fourth-stump line, flits down the track and drives it to long-off",
    "flat on the pads, slog-swept hard to deep square leg",
    "outside off with some extra bounce. Dabbed awkwardly to the right of the keeper",
    "fuller in length, down the track and slashed to third man off a thick outer edge.",
    "on a length and outside off, crashed to long-off",
    "slower ball at 110ks, check-pushed to long-off",
    "fuller and on middle and leg, tucked away backward of square on the leg side",
    "back of a length and on the hips, eased to long leg",
    "low full toss on off, dragged to long-on",
    "swiped to long-on with plenty of bottom hand",
    "banged in short and hurries on, Miller loads up for a pull and gets an edge behind square leg",
    "low full toss on the leg stump, whipped away to deep midwicket. THe non-striker wants two, but is sent back. He" +
    "\ dives and beats the throw from the deep",
    "low full toss on the stumps, dragged to deep midwicket. No mix-ups here",
    "another low full toss, clubbed to deep midwicket. The striker attacks the ball and keeps it to a single.",
    "skips down the track again. He is wary of it as he drags his length back. Punched through cover-point",
    "much better, cramps hi up for room. Tucked in front of square on the leg side for one",
    "fuller and on middle, drilled ram-rod straight, so much so the drive hits the stumps at the non-strikers; and " +
    "runs away towards mid-on. Hendricks did bent low but didn't finger-tip it away",
    "back of a length and outside off, he aims to punch it through the covers. Manages an inside edge that sneaks " +
    "away in front of square on the leg side",
    "looped up slow on middle, flicked towards midwicket for one",
    "much quicker on the leg stump as he steps away, goes low for a sweep. Mistimes it as the ball goes only as far " +
    "as in front of square leg",
    "down the track and punched to long-on. The bowler had shortened his length",
    "back of a length and outside off, punched to the covers, where the fielder dives to his right, tries a direct " +
    "hit and misses. Had ne nailed the stumps down, the striker was a goner",
    "full on the pads, whipped to mid-on",
    "back of a length and outside off, slapped to sweeper cover",
    "drives this full ball outside off to long-off",
    "picked away off the pads through square leg. There is protection in the deep",
    "length, driven to long-on",
    "back of a length and outside off, punched off the back foot to long-off",
    "pushed through on middle, short-arm pulled to long-on",
    "pushed through on off, opens the face at the last instant and guides it to short third",
    "Warner pulls this half-tracker from outside off to long-on",
    "starts off a new spell badly. On a length and outside off, flashed to third man off an outer edge.",
    "shortish and angled in, helped away in front of square leg",
    "fuller length on off, clears his front leg and scythes it over the covers",
    "too full and straight, clipped away to long leg",
    "low full toss on the pads, he gets away. He flicks it to deep square leg",
    "the bowler hunts for a yorker, slips in another low full toss. Driven to long-off after backing away a touch",
    "low full toss again, he camps back and clips it through square leg",
    "Warner steps away outside leg, chases him with a fullish ball, which is punched to long-off.",
    "slid through on middle, backs away and punches it wide of point",
    "darted outside off from round the stumps, drilled to long-off",
    "backs away, takes it from a middle-stump line and chops it towards sweeper",
    "full and outside off, nips down the track and lashes a drive to long-off",
    "slid through outside off, down the track. He seeks to pull and ends up dragging it to long-on",
    "swiped from outside off to long-on",
    "slider on off, dabbed in front of point with soft hands",
    "full toss on middle and leg, hacked away to deep midwicket",
    "fired on the leg stump, whisked to leg",
    "short on the stumps, he hangs back and punches it past a diving bowler to long-on",
    "Slower short ball outside off, he reaches out and chops it towards point",
    "shortish and hurries on off, he manages an inside edge onto the pads. The ball rolls to off and they sneak one",
    "on a length and outside off, laced past the covers. Sweeper tidies up",
    "Warner steps away outside leg and pushes this low full toss to long-off",
    "change of pace outside off, chipped in front of long-off. Fooled by the slower one",
    "veering down leg, helped fine on the leg side. The fielder has it covered in the deep",
    "he steps away outside leg, The bowler follows him with a full toss. Whipped behind square",
    "low full toss on the pads, picked away to long leg",
    "he makes room outside leg, the bowler follows him with a full ball. Struck on the pads and they rush across for" +
    " a leg bye. There is a shy at the stumps but misses the direct it. Given as a run, though",
    "full and outside off, flat-batted thump back to the bowler, who bends down in his follow through and takes some" +
    " pace off it, deflecting it towards long-off. They steal one",
    "low full toss on off, hacked to deep midwicket as the striker yanks his bottom hand off the bat and miscues it",
    "yorker at the base of off, squirted in front of the covers",
    "fullish and angling away outside off, plays away from the body and gets a thick outer edge that dies in front " +
    "of gully. He flings to his left and stops the ball. He recovers, gets on his feet and misses the direct hit. Had " +
    "he nailed the stumps down, the striker would have been out",
    "pushed through on middle and leg, whisked in front of midwicket for one",
    "Baz runs down the track, drags his length back outside off. Lashed over the covers. Off the bottom of the bat, not " +
    "middled",
    "steps away outside leg, he slips in a straight ball, which is chipped over the bowler. He wanted to loft it " +
    "forcefully but did not get enough power",
    "full and on the pads, clipped through midwicket",
    "Darted shortish and outside leg, he steps down the track and drags it to long-on off the inner part of the bat",
    "back of a length on off, punched into the gap at the covers",
    "picked away off the pads in front of square. The batsman is off for one",
    "Raina opens the face of the bat on impact with this length ball outside off and glides it to deep third man. He is " +
    "halfway down for the second. Slips and his partner turns back. He dives and is safe. the fielder involved misses " +
    "the direct hit",
    "back of a length, flicked away behind square",
    "shortish and outside off, he hops up and works it to the left of the bowler, in front of mid-on",
    "slower lifter on off, he can't manufacture his own pace. Pulled backward of square leg",
    "fuller and straight, tucked away through midwicket",
    "pushed in front of point for one",
    "short and cramps him for room, pulled to the right of short midwicket",
    "fuller and around off, shuffles across, takes a step forward and flicks it in front of square on the leg side",
    "134ks length ball on off, knocked in front of point for one",
    "flatter and quicker outside off, camps back and punches it to long-on",
    "down the track and dragged to long-on",
    "quicker one, keeps alarmingly low. He stoops low with it and flicks it tentatively through midwicket",
    "flat and fired on the stumps, jabbed to long-on",
    "shortish and outside off, turning ball, going away outside off flat-batted to long-off",
    "down the track and worked through midwicket",
    "pushed through on off, he advances and flat-bats it to long-off",
    "shortish and gets some assistance from the pitch, cramping the batsman for room. Turned to leg",
    "leg-stump ball, helped to long leg",
    "banged in short and hurries onto him, who plays a reasonably controlled pull to deep midwicket",
    "banged in short and rises on off, he opens the face of the bat and glides it to deep third man",
    "flatter and quicker on leg, whipped through midwicket",
    "looped up outside off, he held this one back. Checks the lofted-drive and chips it over the covers",
    "back of a length and outside of, pushed down to mid-off",
    "comes down the track, the bowler bangs it short. Mishit over the bowler's head",
    "pitched up and outside off, driven in the air. Sliced in front of mid-off. A little fumble there, but no harm done",
    "nips down the track, slower ball. Dragged to long-on",
    "slower ball on off, he pulls all the pace off it again. dabbed behind point",
    "this time he backs away, the bowler follows him. Tapped to backward point",
    "yorker outside leg, jabbed through the covers",
    "dug in shortish and outside off, suspect that was a slower ball, flat-batted to the off-side sweeper",
    "dug in shortish and outside off, dragged to mid-on. Just a single",
    "fired full and outside off, the batsman steps out, edges it to the left of the keeper, who gets a glove, keeping " +
    "it to one",
    "fractionally short and outside off, dragged to long leg off the inner part of the bat",
    "back of a length and on middle, clipped to mid-on for one",
    "fuller and outside off, he shuffles across and helps it to third man",
    "dug in shortish and outside off, slashes and gets a thick outside edge that flies in the air.... Dies in front of " +
    "third man",
    "fullish outside off with a hint of away movement, squirted to third man with an open face",
    "on a length and outside off, dabbed to third man",
    "on a length and swerves in, pushed to the right of mid-on, who gets across and limits it to one",
    "wide line outside off, waits on it before guiding it to third man again",
    "on a length and outside off, this time the striker wants to drive with no feet movement, has to settle with an " +
    "inside snick towards fine leg",
    "length and outside off, steered to third man",
    "quicker on middle, gets an inside edge in front of square on the leg side",
    "flat on middle and leg, squirted to long leg off an inner edge",
    "slid through on off, punched past a diving long-on",
    "quicker on middle and leg, he sinks to one knee and sweeps it behind square on the leg side",
    "slower through the air and full on off, tapped to backward point with an open face",
    "flighted and outside off, driven to long-off",
    "punched down to long-on for one",
    "fullish on the leg stump, bunted to long-on",
    "quick on middle, he backs away and chops it to short third man",
    "picked away off the pads to backward square leg",
    "hurrying ball on middle, punched out towards cow corner",
    "full and on middle, hacked to long-on off the inner part of the bat",
    "drifting onto the pads, helped away to deep backward square leg with a controlled sweep",
    "drifts in on middle and leg, eased to long leg",
    "extra bounce outside off, pushed to the covers",
    "straying on the pads, tucked away through midwicket",
    "much quicker through the air, flatter, dragged to long-on",
    "pitched up on off, driven through the covers with an open face",
    "full toss, bunted down to long-on",
    "drifts on the pads, worked in front of square leg",
    "flatter and on middle, pushed to the covers for one",
    "veering onto the pads, nudged to the right of short midwicket",
    "leg-stump line, turned through midwicket",
    "fullish and on off, nudged in front of square on the leg side",
    "on a length and on middle and leg, punched down to long-on.",
    "back of a length outside off, plays a checked punch towards mid-off",
    "length ball on a tight off-stump line. Stays in the crease and bunts it into the covers with soft hands",
    "full-toss on off stump, pushed to mid-off for a quick single",
    "length ball on off stump. He makes a lot of room and slaps it to cover",
    "down the track now, and tries to smack the wide length ball back down the ground. Inside-edges it instead, sends " +
    "it rolling towards short fine leg",
    "another slower ball, back of a length on off. Maxwell goes back and across and dabs it to third man",
    "much fuller now, and he can't get any elevation as he shapes to play a similar shot, ends up jabbing it along the" +
    " ground, into the covers",
    "shuffles a long way across, and flicks the low full-toss to deep square leg",
    "length ball outside off. He leans back and clubs it towards long-on",
    "full on leg stump, clips it towards short fine leg",
    "back of a length, angling in from wide of the crease, towards off stump. Tucked away towards midwicket",
    "goes on the back foot now, pushed through quicker, and punches into the covers",
    "down the track now, clipped towards backward square leg",
    "length ball, turning sharply into the pads. whips it towards short fine leg",
    "slower ball outside off, slapped towards deep point",
    "slower ball on off stump, comes forward and pushes it to cover",
    "very full close to off stump, can't get any real power on his drive, straight towards cover",
    "another slower ball, wider this time, and he shuffles across and looks to launch down the ground, bounces towards long-on",
    "slower ball, may have been a wide because it seemed to be just outside the tramline outside off, but the batsman " +
    "had moved across and he managed to flat-bat it and drag it down to long-off",
    "full-toss on off stump, angling into the batsman and tucking him up. He looks to swat it leg-side, can only " +
    "inside-edge it into his back pad and send it rolling towards short fine leg",
    "down the track he comes, clips against the turn to deep midwicket",
    "out of his crease again, makes room this time, and lifts the off-stump ball down the ground, to the left of long-off," +
    " who manages to run around and field it",
    "sees him shaping to step down the track and bowls a back-of-a-length ball just outside off. He manages to poke it " +
    "away towards deep point",
    "slower low full-toss outside off, drives but can't beat cover",
    "another low full-toss, a bit of width too, and he can't beat cover with a firmly struck drive",
    "tried to make room to hit through the off side. The bowler banged it in a touch shorter and he toe-ended it towards" +
    " third man",
    "length ball on middle and off. Swiped to deep midwicket, and he has only conceded six off his final over.",
    "slower ball, very full on leg stump, clipped to midwicket",
    "slower ball on off stump. Gayle clears his front leg and swats it to deep square leg",
    "back of a length, straight. Gayle tucks it off his hips through backward square leg",
    "fullish on middle and leg, driven towards long-on",
    "length ball, keeps it close to the body, and he opens up at the hips and swats it towards deep midwicket",
    "slower ball outside off, stands tall and flat-bats it past the diving short extra cover fielder, to the left of " +
    "long-off",
    "slower ball on off stump. He makes a bit of room and flat-bats it to long-off",
    "another slower ball, wide outside off, drags his pull to deep midwicket",
    "full and wide again, and he slices it in the air, one bounce down to sweeper cover",
    "full slower ball outside off. The batsman is down on one knee to drag it to deep midwicket",
    "slower ball again, on a fullish length outside off, swings at it and doesn't connect too cleanly, rolls down to long-on",
    "slower ball, angling in towards off stump. he presses forward and pokes it into the covers to pick up a single",
    "slower ball again, on middle stump. he makes a bit of room and chips it over mid-off",
    "slower ball again, shorter now, angling into the body. AB looks to pull, drags it squarer than he'd like, towards" +
    " deep square leg",
    "full and flat on middle and leg, clipped into the vacant midwicket region, and the bowler sprints to field it",
    "length ball angling into off stump, plays the checked drive to long-off",
    "very full outside off. Makes swinging room and swipes it down to long-on",
    "slower ball on middle stump, angling in and denying the batsman room. Pushed into the covers",
    "low full-toss on middle stump, down on one knee to swing it away to deep midwicket",
    "sees him making room and bowls it flat and straight. Swipes it down to long-on",
    "down the track and he fires it full, angling into the batsman. Jabbed towards square cover",
    "follows the batsman as he comes down the track, moving towards the leg side. Goes for the big hit, drags it in the" +
    " air to the right of deep midwicket, drops well short of him",
    "speared full and flat on off stump, slapped to sweeper cover",
    "shorter now, on off stump, and he clears his front leg and flat-bats it to long-off",
    "he is gifted with a high full-toss, heading towards the right shoulder of the batsman. Takes his eyes off it as he" +
    " half-fends, half-pulls, and it goes off the edge towards short third man. Slipped out of his hand there",
    "fuller now, and this time he connects with the lap from outside off, but hits it straight to backward square leg",
    "another slower ball outside off, clubbed to long-on",
    "full on off stump, driven down to long-off, and they get a single",
    "shot. That's nice and full outside off and he gets a big stride forward to play a firm drive into the ground. " +
    "Bounces over short cover, who jumps in the air to palm it away",
    "length ball on off and middle, tucked away towards deep square leg",
    "length ball on off stump, pushed with a nice straight bat towards mid-off",
    "straighter now, on off and middle, and the striker, who was initially backing away towards the leg side, swipes it" +
    " to mid-on, not quite middling it",
    "back of a length close to off stump. He rides the bounce and drops the ball into the covers with soft hands",
    "back of a length on off stump, whipped wristily to deep square leg",
    "angled into the pads again, clipped towards midwicket",
    "fuller and straighter, swept to deep square leg",
    "dropped! The ball is following the batsman's body here. He pulled a shortish ball from a fair way outside off, " +
    "using his wrists to play the shot in the direction he wanted. He wanted to get it wide of short fine leg, but it " +
    "was close enough to him to dive to his right and get a hand to it, but it didn't stick",
    "tossed up slower outside off, driven to long-off",
    "back of a length on off stump, he lets it come on and guides it towards third man",
    "back of a length outside off, dabbed away to third man",
    "tossed up outside off, pushed to sweeper cover",
    "length ball on off stump. He goes on the back foot to whip to long-on",
    "length ball on middle and leg and he's a touch too early to close his bat face to flick, and it goes off the " +
    "leading edge towards third man",
    "again he goes back to a length ball, this time it's on off stump and he punches it to sweeper cover",
    "pitched from off and going on to middle, the batsman goes on the back foot to work it towards midwicket",
    "down the track and this time he gets to the pitch of the leg-stump ball to drive to long-on",
    "shortish ball close to off stump. He stands tall and drops it into the off side with soft hands to pick up a single",
    "shortish, angling into the body, and the batsman leans backwards at the waist and lets it come on and run off the" +
    " face of his bat to the left of third man",
    "tossed up slow and full on middle stump, worked away to deep midwicket",
    "goes back to a length ball on off stump, not much turn, whips it away to deep midwicket",
    "shortish outside off. He hops in the air to ride the bounce and steer it to third man",
    "slower bouncer outside off, and he gets into an uncomfortable position to play a half-pull, half-whip that just " +
    "eludes short fine leg, running to his left",
    "on the pads now, tucked away to deep square leg",
    "slower short ball and Pollard is through his pull too quick, drags it off the inside edge towards short fine leg",
    "flat and shortish on off stump, stops on the pitch and he can only club it to long-on",
    "back of a length outside off, whipped to long-on",
    "fuller now, still quite flat and quick. Drags it from outside off to drive towards long-on",
    "tossed up a bit slower, angled into off stump. He is on the front foot to push into the covers",
    "short on off stump, pulled to deep square leg",
    "low full-toss on off and middle. He moves away from the line and jabs it down to long-on",
    "back of a length on off stump, turns away and Pollard dabs it delicately to the right of the keeper",
    "length ball outside off, moves away. He goes on the back foot and taps it gently towards backward point",
    "shortish outside off. Pollard lets it come on and picks up a dabbed single to short third man",
    "a bit of extra bounce now, cramps the batter for room as he goes on the back foot. Plays with a straight bat, " +
    "punches to long-off",
    "tossed up slowish outside off. He stretches out and pokes it to backward point",
    "fullish on off stump, whipped to long-on",
    "fuller now, on off stump, driven firmly down the ground and the bowler's right foot gets in the way. If not " +
    "inadvertently, certainly not entirely advertently",
    "down the track now, hits it in the air, with the line, doesn't quite get hold of it, and it drops just short of the" +
    " man diving in from long-on",
    "back of a length, punched to sweeper cover",
    "goes on the back foot looking to make room to hit through the off side. Moves in sharply and tucks him up for room" +
    " and he punches it away towards sweeper cover",
    "fuller now, outside off. Goes deep in his crease to dab it towards short third man",
    "shortish on off stump, pulled along the ground to deep midwicket",
    "slower yorker, angled into the batsman's feet. Swipes at it and it rolls down towards long-on",
    "length ball on off stump. The striker opens up and looks to flat-bat it down the ground, ends up edging it towards" +
    " third man",
    "very full outside off, goes deep in his crease and swats it towards long-off",
    "full and wide, driven straight to extra cover",
    "full-toss on off stump, opens out and swipes it to long-on",
    "length ball on off stump. he gets his front foot across to tuck it towards wide mid-on",
    "shortish on middle and leg, pulled towards deep square leg",
    "slower ball on off stump, comes forward and clips it through midwicket",
    "another slower ball, dips towards the front boot, and he flicks it away to deep square leg",
    "angled into off and middle, tucked away towards deep backward square leg",
    "back of a length on off stump. He lets it come on and dabs it to third man",
    "angled in towards off stump, on a length. he makes room and slaps to point and takes off for a quick single. May " +
    "have been close had the throw hit at the bowler's end",
    "shortish ball rising towards the ribcage. He hops to dab it down in front of him for a quick single. The fielder " +
    "is quick to the ball and tries to slap it onto the stumps at the keeper's end while sprawled on the ground, doesn't" +
    " hit them",
    "short, skiddy ball. The batsman is a bit late on the pull, rolls towards backward square leg",
    "tossed up on middle stump, whipped to deep midwicket",
    "back of a length, angling into the body, tucked away towards backward square leg",
    "back of a length on off stump, pushed towards mid-off",
    "back of a length outside off, dabbed to third man",
    "length ball on off stump, defended towards short cover and they run a quick single",
    "tossed up full on off stump, driven to long-on",
    "tossed up outside off, driven to long-off",
    "down the track, whips it from off stump towards deep midwicket",
    "down the leg side now, I don't know how much bat he got on that sweep, rolls down to short fine leg",
    "back of a length on off stump, makes a bit of room and plays that typically surgical chop down to third man",
    "tossed up fuller, on off stump, worked away wristily through midwicket after taking a big stride forward",
    "back of a length outside off, dabbed towards short third man",
    "uppish, looking to slash at a length ball by making room. Ends up slicing it in the air to the right of point but " +
    "it bounces short of him as he dives to try and catch it",
    "down the track and hits with the turn, in the air but on the bounce to deep midwicket",
    "length ball outside off, stays on the back foot and punches towards deep cover",
    "length ball outside off, stays in his crease and pushes it with soft hands into the off side for a quick single",
    "down the track to a loopy, dipping ball on off stump, drives it to long-on",
    "flat, angling in towards middle and leg. Goes back and across and nudges it into the on side",
    "down the track again, meets the ball with a straight bat to drive to long-on",
    "short and wide again, this time it stops on the pitch and he hits it to sweeper cover",
    "shortish slower ball on off stump, whipped away to deep midwicket",
    "short ball to start the spell, pulled away to deep midwicket",
    "shortish again, pulled towards deep square leg",
    "slower ball on leg stump, tucked away towards short fine leg",
    "low full-toss outside off, sliced away to sweeper cover",
    "slower short ball wide outside off. He reaches out and plays a checked uppercut to land it short of the sweeper " +
    "cover fielder",
    "slower ball, full and wide outside off, driven towards extra cover",
    "slower ball, full and wide, steered towards sweeper cover with an open face",
    "short ball, is too quick to pull, and he's lucky the top-edge fell in no-man's land, a long way to the left of and" +
    " in front of short fine leg",
    "full and wide now, slapped down to long-off",
    "full-toss on off stump, whipped to long-on",
    "short again, angling into the body. He swivels, pulls between long leg and deep square leg",
    "back of a length ball on off stump. Stays in his crease and dabs it softly into the off side for a quick single",
    "shortish, sits up at waist height, and that is superb fielding, sprinting to his right from deep square leg " +
    "and sliding to stop that crisply timed pull. Made the stop look so easy",
    "yorker on middle and leg, clipped to deep midwicket",
    "this time he gets the off-stump yorker right and he can only jab it firmly into the ground and send it " +
    "bouncing over the bowler's head",
    "shortish slower ball on off stump, swiped towards midwicket",
    "shortish and slid down leg, pulled past short fine leg. The batsman wants two, but his partner denies it",
    "back of a length on leg stump, slugged away to deep midwicket. The field can spread",
    "it's a short ball that's sliced to point",
    "down the track, but the bowler flattens his trajectory. Slapped to long-on",
    "down the track and heaves the flat delivery down the ground. It's too quick for him though, it throws him off " +
    "balance and it's got no timing. Long-off keeps it to a single",
    "hits the yorker on middle, nudged to midwicket for a quick single",
    "full on leg stump, whipped through the leg side for only a single",
    "it's a low full toss outside off, the batsman is forward and crouches to lap the ball over to long leg. Could have" +
    " been two, but the captain disagrees. He wants it",
    "back of a length and cramping him up, Warner rolls his wrists to find midwicket",
    "shortish on middle and leg, Warner taps it down to mid-on",
    "goes short and sliding down a touch. He swivels in the crease for a pull. But all he does is spoon the ball towards" +
    " midwicket. Lucky there wasn't anyone around",
    "loads up a full toss, driven with the angled bat to deep point",
    "picked up the slower ball early again, waits for it to reach him and cuts to deep point",
    "a hint of width and the striker looks to exploit it. Goes for a crack through the covers, but the four-man off-side" +
    " ring can't be breached",
    "half-volley outside off, he crunches it to the sweeper",
    "shortish on middle, camps back in his crease and heaves it to deep midwicket",
    "looks for the yorker and lands it quite well. He digs it out into the covers",
    "misses the spot and Warner doesn't manage enough of a connection. Clears the front leg and goes for a slash, ends " +
    "up with an inside edge towards midwicket",
    "another near yorker, he was looking for a slice through the off side. has to accept an inside edge for a single" +
    " to the keeper",
    "saw the batsman running away outside leg again and follows him. Hits the blockhole too, so only a single through " +
    "the covers",
    "goes back and taps a good length ball to long-on",
    "tossed up outside leg, he nudges it to the left of where mid-on would have been. As such, the bowler has to chase" +
    " after the ball himself",
    "down the track, heaves a full toss down the ground to long-off.",
    "whipped off his legs to deep square leg, that's a full toss as well",
    "low full toss on leg stump, thumped down to long-on. So powerfully hit that it's only one. Great work from the " +
    "fielder there too, diving away to his right",
    "full on leg stump, nudged to long-on",
    "shortish and outside off, slashed to the sweeper",
    "dropped! The culprit is at point, coming right at him, doesn't even have to move. It was a fuller ball with some" +
    " width. The batter goes for a slash, but hasn't got the elevation he wants",
    "full on leg stump, squeezed to long-on",
    "tossed up outside leg, lifted to mid-off. That seems something like a knuckle-ball. Pushed through off the front " +
    "of the hand",
    "moves outside leg, the bowler loops it outside off. Ends up a full toss. The striker reaches it and slaps it " +
    "through the covers.",
    "fuller delivery outside off, dabbed into the covers for a single",
    "great work! Dives to full-length to his left to hold a cut down at short third man. The striker had done well too," +
    " to wait for the ball and try and beat the man. Comes out second best though",
    "down the track to push a good length ball to long-off",
    "follows the batsman's move down the leg side, he swipes it away to long leg.",
    "down the track, but he fires the ball at the batsman's legs to cramp him. The man can only push it into the covers" +
    " for a single. Doesn't like that he's been pinned down like that"
];