/**
 * Created by Kunal Nagpal <kunagpal@gmail.com> on 09-02-2015.
 *  GraVITas Premier League
 *  Copyright (C) 2014  IEEE Computer Society - VIT Student Chapter <ieeecs@vit.ac.in>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
module.exports =
    [
        "",
        "oops! The yorker ends up a full toss and he has mauled it over cow corner. ",
        "switch hit alert! This was a low full toss on off stump, the batsman changed his grip and swept it right-handed over  short fine leg, which was short third man until a second ago",
        "low full toss outside off, the batsman does what he has been doing so often. Backs away and hammers it over the  boundary. This time the crowd over extra cover scurries to return the ball",
        "this time he misses his length and the batsman has swept him mightily into the stands behind square leg. Sunk down  into his knees and swung the arms quite freely. That was massive",
        "slower ball, picked up and hoisted over long-on. Bent his knees and slogged it away cleanly",
        "The bowler saw him making room outside leg and fired it wide outside off. But he reaches out, the bottom hand comes  off the bat and yet he blasts it over extra cover",
        "That's emphatic! Chips down the track and drops this into the second tier behind long-on. Reached the pitch and  punished it",
        "that's over the ropes! It was length and sliding down leg, the batsman was on his front foot and swiveled to help it  on it's way.",
        "over midwicket and into the stands",
        "nicely done, the batsman moves to off stump, and creates space to whip this back of a length ball with the angle,  it is timed so well it goes all the way",
        "short ball, he swivels for a pull, and the top edge flies high over short fine leg",
        "slog sweep this time. Gets this on the middle off the bat and whacks it deep over square leg",
        "this is painful for the bowler! The batsman goes back and whacks the flatter delivery to deep midwicket, where the  batsman lines himself up, but as he completes the catch, he touches the ropes.. He has not only given the batsman a life, he is given away six runs..",
        "goes down on his knee, this is whacked high and handsome over deep square leg for another biggie",
        "The batsman was waiting for the bowler too as he goes down on his knee and launches it over midwicket.. this is high  and long and hits the giant TV screen which is showing a picture of .. the bowler..",
        "ball on leg stump and the batsman has pummeled this over square leg. The captain is in deep conversation with his  bowler. That was such a powerful strike. Not to mention a pretty poor ball from the bowler",
        "that's what they want. Got under it nicely and though he had to hit against the turn it was in the slot to cart over  to the midwicket boundary and that's exactly what he does",
        "that's smashed out of here! Comes down the track to launch the flatter ball into the sight screen",
        "skips down the track and reaches the pitch and once that's done he smacks it straight down the ground. Clears long-on easily",
        "length again and he has sent it into orbit! Planting his front leg down the ground and slapping it through the line  and into the stands behind long-on.",
        "the bowler looks for the change of pace and the batsman picked it up early, backed away and pounded it over long-on.  He sure can hit it long",
        "has mauled it into the stands behind cow corner. Flat, hard, murderous. That's an emphatic shot",
        "smack! The ball goes wide of the crease but makes the fatal error of providing an overpitched delivery outside off.  He is on the front foot and pummels it flat over the long-off boundary",
        "in the arc: check, batsman ready: check, bat swing: plenty, result: massive sixer. He could have hit that with his  eyes closed.",
        "that was in the slot and he has taken ample toll. Length ball on off stump and a free swing of his strong arms sends  crashing into the sight screen",
        "he gets under this one just outside off and lift it cleanly onto the roof of the stadium way past the long on  boundary",
        "overpitched and he slog-sweeps it just over the man at long on",
        "fuller this time, and he steps forward and lifts it straight with a smooth follow through",
        "fast full toss, the batsman plants front foot out and pummels it into the sight screen",
        "full and slow outside off, he waits and pummels it into the upper tier beyond long on",
        "he was already shuffling across, the bowler gives him a high full toss, and the batsman whips it right into the deep  backward square leg rope",
        "long off in business again at long off, the batsman has made room outside leg and gone off side now, the fielder  sets himself up at the rope, but this goes just over him",
        "eases smoothly down the track, gets to the pitch and lifts it into the sight screen",
        "carts it way over the deep midwicket boundary with a fearsome connection on the slog sweep",
        "slower length ball sits up, the batsman cranks up and smashes a pull over deep midwicket",
        "slog-sweeps powerfully over deep square leg",
        "the batsman waits and wallops it straight and high, the fielder in the deep fancies a chance at long off, he finds  himself outside the rope, and gets out of the way to avoid being hit by the ball as it comes down",
        "he knows fine leg is up, this is short, and he swivels sharply to send it soaring over the fine leg boundary",
        "shortish on the pads, and he is on one leg as he swats it flat over deep backward square leg",
        "this was pitched up outside off and he picked the length and slammed it over long-on",
        "this is bad bowling, nobody patrolling the deep on the off side and he bowls it short and wide outside off, the  batsman goes airborne as he slaps it flat over deep point",
        "clears the long boundary! This was short of a length and the batsman was in position early for the pull, picked the  length and clubbed it over deep midwicket",
        " and distance! That kept going and going....the batsman was down the track to a length ball and he slammed that into  orbit over long-on, went several miles up in the air",
        "that was clean! Tossed up by the bowler and the batsman went down the track and took it downtown, the ball clears  the straight boundary",
        "he gets low and slices it over cover this time",
        "the bowler tries a slower one, the batsman takes it from just outside off, and swats it in front of square leg",
        "another maximum, one more full toss from teh bowler, the batsman crashes it over extra cover",
        "low full toss, around off, he steps forward and launches it over long on",
        "goes back and flat-bats it into the sight screen",
        "slower length ball down the pad, the batsman bends his knee and smacks it in front of square",
        "full, slow and on the stumps, he is backing away to leg, and has carted it high over long off",
        "goes off side this time, this is short and leaving him on the angle, he takes a couple of steps out, and forehands  it over backward point",
        "a full toss, the batsman uses his wrists and swats it over deep square leg",
        "picked cleanly over deep square leg, full into his pads, and the batsman sends it soaring",
        " pings it back of a length outside off",
        "steps out now, is not to the pitch, but goes through with a mighty loft, and clears wide long off",
        "a full toss angled in, he wallops it high over deep midwicket",
        "this is overpitched on middle and leg, all he has to do is clear his front leg and smack it high and straight",
        "overpitched straighter now, and the batsman cracks it over the bowler",
        "this is overpitched on the stumps, and he's gone dead straight over the bowler, and over the rope",
        "this one will go, he tosses it up just outside off this time, the batsman makes some room outside leg, and lofts,  very cleanly once more, over extra cover",
        "this has been picked up from just back of a length and dispatched with disdain over the deep midwicket boundary",
        "the batsman tees off now, picks this from a length and sends it soaring over the long on boundary",
        "mid off is up, this is pitched up, outside off, and the batsman lifts it calmly over the fielder",
        "he swings a quick delivery way over the deep backward square leg boundary, that is into the upper tier",
        "a full toss outside off, the batsman walks across and laps it miles over short fine leg, and over the rope too",
        "that's been swiped over deep square leg for six, short of a length, just above waist height for the him, and he  attacks it eagerly, as if he was waiting for the length", "gets one away, jumps out, reaches this widish one and smashes it high over long off",
        "swiped this with a massive top edge off his pad, the tall fielder is there at fine leg, but this is too big a task  for him as well",
        "clears front leg and lofts this length delivery cleanly over mid off",
        "shortish, the batsman bends, gets under it and hits it high in the air, clears the deep square leg boundary",
        "lashed over wide long off, the batsman gets a length ball, steps forward, bends a knee and hammers it high",
        "some much needed catching practice for the spectators...",
        "down the track, gets under the ball and wallops it high over deep midwicket",
        "that gets the crowd going! This was banged in a on a good length, the batsman was back at the crease and pulled it  in front of square over deep midwicket",
        "the big hit! Tossed up on middle and leg, the batsman was on his knee and slogged it high over deep midwicket",
        "over long-off this time. Another little trip down the track and though it hit the bottom of the bat, it had enough  to clear the fielder in the deep",
        "offers length and the batsman has pounced. He was down the track and belts it way into the crowd behind long-on",
        "short ball on off stump, he rocks back and smashes it way into the grass banks at cow corner",
        "lovely footwork as he leaves the crease to reach the pitch and a full swing of the arms brings up another straight  six",
        "full tos outside off and he has crashed it over the man at deep cover. ",
        "again offers him room and the length to get under and the batsman needs no second invitation",
        "the batsman saw it early and hammers it over the square leg boundary.",
        "pummeled into the grass banks! It's short, it's on the leg stump and it's been pulled with the utmost authority.  No point keeping it down when you can hit it that far",
        "Soars straight over the bowler's head as he gets forward to the overpitched delivery and just extends the arms from  a forward defensive",
        "that's more like it! Shimmies down the track to get under the ball and launches it into the crowd behind long-on",
        "effortless swipe over the midwicket boundary",
        "goes fuller with that slower ball and he was expecting it this time. Stays still at the crease and whacks it over  deep square leg",
        "picked it up and swats it over the deep midwicket boundary! It was length and he kept his front foot out of the way  and muscled it.",
        "swiped into the crowd behind square leg! This was drifting into the pads and he gets down on one-knee and slog swept  it powerfully",
        "Ensured his front foot was not in the way and an effortless whip of the wrists sends the ball beyond the square leg  boundary",
        "peppers the sight screen after skipping down the track.",
        "That has been launched into orbit ! We might as well bring a new ball right now...",
        "misses the mark with his length and the batsman gets under it and smacks it beyond the long-off boundary. Clean as  a whistle",
        "mauled into the crowd behind deep midwicket! It was the slower ball and he'd picked it early and though the bat  turned in his hands, it sailed past the ropes",
        "magnificent ! That ball had six written all over it !",
        "the bowler bowls a terrible long hop and the striker shuffles across and mauls it miles into the square leg boundary.  Surely he would have enjoyed that. ",
        "away the ball goes goes. Flat, hard and just over the ropes. On leg stump and he swung for the fences",
        "Overpitched outside off and he waded into the shot and timed it perfectly",
        "outside leg stump and he's helped it on its way. Lands among the his teammates in the dug out and he has a big smile  on his face while punching gloves with his non-striker",
        "and he's sent packing over long-on. Races down and gets to the pitch. Doesn't bother about where it's going and just  launches it into the night sky",
        "a glorious shot over extra cover. Didn't get to the pitch as much as he would have liked, and had to sort of reach  for it, but his timing was still top-notch",
        "long-on watches it clear his head and thud into the advertising boards. Pitches it up in his arc and a big back lift  comes down in a thunderous swing",
        "terrible line from the bowler. On the pads and he's been swept miles into the boundary behind square leg. A batsman  of such class against this kind of bowling is no contest at all.",
        "what a strike! It was short and afforded him enough room to upper cut it and he's put enough muscle into it to clear  the ropes",
        "into orbit! Races down the track to pick it up off a length and deposit well into the crowd behind long-on. The  batsman has done away with defensive strokes",
        "did that go all the way? This was bowled short and sat up nicely for the batsman to biff it over midwicket, the  question was whether the ball hit the boundary cushion on the full or on the half volley, the on-field umpire asks the third umpire and after studying a few replays he calls it a six"

    ];