/*
 Created by Kunal Nagpal <kunagpal@gmail.com>
 GraVITas Premier League <gravitaspremierleague@gmail.com>
 *  Copyright (C) 2014  IEEE Computer Society - VIT Student Chapter <ieeecs@vit.ac.in>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
module.exports =
    [
        "low full toss on middle, whipped to midwicket on the edge of the circle",
        "there's the one he wants. The yorker a shade outside off, jammed back at the bowler amid great applause. That " +
        "delivery deserved every bit of it",
        "play and miss, is that the first? This was a back of a length delivery seaming away from his down the track smash",
        "another slower ball a shade outside off, looks for a slash but he doesn't beat the field at cover.",
        "saw the batsman running outside leg and flings down a widish yorker. But manages to stay inside the wide line. " +
        "Great presence of mind",
        "full on leg stump, nudged towards mid-on",
        "pulls the pace off, good intuition as he hurries down the track and is beaten.",
        "slower ball and it's away from the batsman's reach outside off. Goes for a slog and misses",
        "wanders away outside leg and he bends his back to beat him with a shortish delivery angled across",
        "it's the offcutter and he's beaten the batsman. His own fault for complicating matters by jumping away from the " +
        "ball. In the end, he can't reach the good length ball angled across him",
        "chance! chance.... not converted! goes for the yorker, keeps the striker quiet. Well, almost. the batsman wants a " +
        "single. There is none on offer because the ball has barely moved away from the pitch. A fielder races up, picks up" +
        " the ball, has ample time for the underarm throw. The batsman is well outside his ground.... but the throw misses." +
        " The simplest throw. The skipper is guffawing, the batsmen are livid. He could have run up and kicked the stumps " +
        "off",
        "gets down the track, and slips in his eagerness. Thumped back at the bowler",
        "yorker on middle, the batsman can't do anything about it. Jams his bat down and protects his stumps",
        "back of a length outside off, slapped to point",
        "a bit slower and a bit of air, he steps out and drives inside-out to cover",
        "length ball outside off, driven to cover",
        "fullish on off stump, clipped to mid-on",
        "back of a length outside off, gets on his toes to push that towards point",
        "back of a length, close to off stump, a bit of bounce on this occasion. Gets back and across and dabs it behind " +
        "square and sets off for a single but his partner sends him back",
        "short again, a bit of width too. Cuts hard but straight to point",
        "length ball outside off, He plays a good-looking on-the-up punch towards backward point, where it hits him in the " +
        "knee as he bends to field it",
        "slower ball outside off. He pokes at it with no footwork, is beaten. May have moved away a touch",
        "in the blockhole on off stump, jabbed down towards midwicket",
        "another lovely delivery, finds that in-between length and the angle away beats the ever uncertain push",
        "fullish on middle and off, defended towards short cover",
        "shortish outside off, slashes and misses",
        "short ball angling into off and middle. He hops in the air to block it back to the bowler",
        "back of a length outside off, poked away to point",
        "length ball, fairly flat on a tight off-stump line. Maxwell blocks it back to the bowler",
        "a bit more air this time, slow, and a fair amount of zip from outside off. He tucks it carefully to short midwicket",
        "down the track now and he bowls it quicker, hurrying him into a defensive push towards midwicket",
        "flat and full just outside off. Looked like the one going away, and the batsman defends with a straight bat back " +
        "towards the bowler",
        "length ball on middle stump, defended to mid-off",
        "length ball on off stump, comes forward to push towards point",
        "lovely length in the corridor, angling away to beat the batsman. The footwork isn't up to it, and he pokes at it " +
        "with an angled bat",
        "slower ball angling away, the batsman looks to steer it to third man and doesn't get any bat on it",
        "lovely trajectory from th bowler, dips on the batsman as he stretches out to defend, moves in sharply and pops up " +
        "off his pad and he makes a polite appeal for caught behind",
        "flat, angled in towards off and middle. Defended into the on side",
        "quickish length ball on off stump, defended off the inside half of the bat",
        "back of a length, turns in from outside off, defended into the on side",
        "looks for the reverse-sweep immediately. The shot was on, but he's through it too quick and it pops down softly off" +
        " the back of the bat",
        "and again. This time the line is straighter and it hits him on the pad. Muted lbw appeal from the bowler",
        "tossed up nice and slow outside off. He stretches forward to block into the off side",
        "nice flight on off stump. Comes forward, lets it spin, and defends with soft hands towards slip",
        "this one's a bit quicker, and he is hurried into a defensive poke, and the ball turns and hits the shoulder of his" +
        " bat and rolls into the off side",
        "on the back foot now, it's a length ball on a tight off-stump line. Defended carefully into the on side",
        "slower now, on off stump. He is on the front foot but he has to wait for the ball to come on before he can push it" +
        " into the covers",
        "stumping appeal! Quick hands from him behind the stumps. That was tossed up invitingly outside off and the batsman " +
        "stretched out to drive, didn't get to the pitch, and it moved away from him and beat his bat. His foot was in the " +
        "air momentarily but he brought it down before the keeper could flick the bails off",
        "tossed up on middle and leg, defended towards short midwicket",
        "flat on leg stump, straightens after angling in sharply, and he stays back, defends with the angle into the off " +
        "side",
        "length ball turning in towards leg stump. he looks to make room, is cramped up, and ends up defending softly into " +
        "the off side",
        "a bit of flight now, outside off, and he stretches out to play a checked drive to mid-off",
        "tossed up outside off, driven to extra cover",
        "slow and a bit of flight outside off. He presses forward and pushes it towards backward point",
        "fullish, angled in towards off stump. He defends with the turn towards backward point",
        "tossed up outside off, slapped hard through cover but he dives to his right from extra cover to stop it",
        "down the track now and Bravo beats him with a very full, wide ball slanted a long way across him",
        "back of a length in the corridor, angling in. Looks to dab it to third man, doesn't get any bat on it",
        "bouncer now, well directed. May have seen the batsman stepping away to make room and followed him, and his attempt" +
        " at a swatted pull comes to nothing",
        "sees him making room again and bowls a yorker right by his feet. He can only push it to mid-off",
        "back of a length, a bit of movement to cramp the batsman, who's looking to cut. Ends up chopping it down towards " +
        "backward point",
        "length ball on off stump. He is a bit early on the attempted cover drive and it rolls off the inside half of his " +
        "bat towards midwicket",
        "bouncer angled across him, who sways his upper body out of the way",
        "full outside off and Raina presses forward and plays a firm, pleasing, high-elbow drive to cover",
        "length ball outside off, moves away, who ignores it through to the keeper",
        "fullish on middle stump, whipped to short midwicket",
        "back of a length on off stump, hops in the air to defend towards short cover",
        "back of a length on off stump, no room this time, defended carefully to short cover",
        "tossed up on off and middle, defended to mid-on",
        "back of a length outside off, punched towards short cover",
        "length ball on off stump, pushed to mid-off",
        "another slower ball, looks to pull, doesn't middle it, goes off the inside half of the bat to short midwicket",
        "dropped! That was a shortish ball that stopped on the pitch, as he popped the back-foot punch in the air to the " +
        "right of the bowler, who stuck his hand out but couldn't grab on to the ball",
        "tossed up outside off, comes forward to stab it away towards point",
        "length ball close to off stump. Raina presses forward, lets it come on, and dabs it towards backward point",
        "fires it into the blockhole as he leaves his crease, and he clips it to midwicket",
        "shortish outside off, slapped to backward point",
        "quickish length ball on off stump. He dabs it towards backward point, wants a single, the non-striker sends him back",
        "flat, round-arm ball on middle stump. Faf hangs back, making a bit of room, punches to extra cover",
        "back of a length on off stump, chopped towards point",
        "sees him coming again and bowls it quick and flat at his feet. Pokes it away towards extra cover",
        "tossed up outside off, too wide for him to work into the leg side and it turns in and hits his front pad",
        "full on the stumps, turned around the corner towards square leg",
        "low full-toss on off stump, pushed to mid-off",
        "back of a length on off stump, jumps in the air to defend into the on side with a turn of his wrists",
        "back of a length outside off, poked away to the right of point",
        "in the blockhole on middle stump, jabbed back to the bowler",
        "length ball outside off, and he goes back and across to poke it to point",
        "shortish slower ball outside off, plays what you could term a defensive pull to midwicket",
        "back of a length on off stump, jumps back to whip to midwicket with a lot of bottom hand",
        "slower ball, back of a length outside off, defended towards point off the back foot",
        "keeps it tight on middle, he is happy to block it down the pitch",
        "tests him on the off-stump corridor, he doesn't bother with it. Just checking if the ball is swinging. Not quite",
        "hits the back of a length again and keeps Watson quiet",
        "stays back and slices the shortish delivery towards point. Angled bat again",
        "a shade shortish and wider, and slower too perhaps, judging from the striker going for the cut too early and " +
        "failing to adjust. Beaten. Only a subtle change of pace though",
        "full on middle and leg, he is caught in the crease and plays an uncertain prod. Like he was going for a flick and" +
        " then decided he needed to use a straighter bat. Ends up with possibly an inside edge onto pad to ruin the appeal",
        "fuller delivery on off stump, pushes down the pitch",
        "back of a length on off stump, defended",
        "a bit short and Watson backs away to cut into the covers",
        "flighted on middle, driven smartly to mid-off",
        "looks for the fuller ball on off stump, dug out into the covers",
        "gets forward towards the pitch of the ball and blocks",
        "stays back to a reasonably fuller ball - playing the flat trajectory - and cuts into the covers",
        "gets up off his toes to block a short ball rising above his stomach",
        "good length ball draws Smith to play away from the body, pushed into the covers",
        "good length ball outside off, he cleared his front leg for a big slog through midwicket. Only gets an inside edge " +
        "onto his pads",
        "flighted on middle, defended after he tries to make some room and decides not to take advantage of it",
        "down the track, but he can't reach the pitch. Lovely bowling from the bowler, pulling the length back and curtailing" +
        " the batsman.",
        "flighted down the leg side, goes for a sweep and misses. No point in appealing, but the bowler and keeper still do",
        "darted in on middle and leg, he backs away and punches with the horizontal bat",
        "waits on the back foot for a shortish delivery and tucks it towards midwicket",
        "back of a length and outside off, left quite well alone. And that's also the time out",
        "floated on middle, pushes it back at the bowler",
        "another short ball, but this one rises a bit higher and he doesn't want to meddle with it. Good zip from the bowler," +
        " and he had a deep midwicket around as well",
        "good length ball on off stump, lots of pace behind it as well. The batsman blocks",
        "shortish and outside off, another slash, another miss.",
        "dropped by mid-off! Came straight at him as he picked up an overpitched delivery and drilled it down the ground. " +
        "Doesn't get the elevation. The fielder had to move to his right a bit and dive forward, but this really should have" +
        " been taken",
        "has managed to dupe the batsman with the slower ball. Heaves a sigh of relief, as the batsman goes for a slog to " +
        "the fuller ball outside off and misses",
        "runs at the bowler to swing blindly. Back of a length delivery outside off beats him. The batsman and bowler have a" +
        " little chat.",
        "that is a beauty first up from the bowler, the ball swerves away after angling in, hit the back of a length and " +
        "cut away to beat the outside edge",
        "length ball just outside leg stump, he looks to tuck that away but can't get bat on ball",
        "shorter this time, he pulls, not with any authority, the ball rolls towards midwicket",
        "shortish once more, moves in a touch, he was down the track and looking to make room, wanted to cut that through " +
        "cover, but the ball gave him no room, so he can't get much power",
        "pitched up and outside off, driven crisply towards cover, the fielder dives to his right to cut that off",
        "angling in, short of length ball, he is rapped on the pads",
        "shortish and outside off, slapped towards mid-off",
        "shortish on middle, pushes him off his feet for a flick to midwicket",
        "leaps away from the outside edge of the poke. Back of a length and outside off, moves away off the seam",
        "fuller delivery curves away from the front foot drive through the covers. He is getting the ball to talk just enough",
        "back of a length and outside off, pushed into the covers",
        "straightens! But he is solidly behind it. Keeps to his crease for a good length ball that he jags away towards off stump",
        "good length and outside off, pushed to long-off",
        "lovely seam position, curved towards the slips, if they had been there. Hits a good length and swings away past " +
        "the outside edge of the slash",
        "back of a length and outside off, he is lead-footed as he pokes with an angled bat. Beaten on the away swing",
        "goes short on middle and leg, quite short that time, he is happy to duck under it",
        "good length ball, straightening a touch. He dabs it into the leg side for a single. But the fielder cuts across " +
        "and keeps it to nothing",
        "bowl it full and he gets beaten! No bat involved as he goes for a flick absent footwork. Lovely movement",
        "goes for a slash and miss",
        "fuller and wider outside off, he was going for another smear over the covers. Misses",
        "good length ball on off stump, defended",
        "shortish and outside off, he is rooted to his crease as he goes for a slash and misses",
        "stays a little too far way on leg stump to reach the short delivery outside off with the horizontal bat",
        "that time he gets the wide yorker perfectly right. The batsman merely watches it pass",
        "back of a length and outside off, plays an iffy sort of dab towards third man. Misses",
        "back of a length and outside off, pushes it to point",
        "manages to hit the wide yorker well. Jams the bat down to try and slice it towards point. Only gets an inside edge" +
        " to the keeper",
        "hits the fuller ball on off stump, drilled back at the bowler",
        "slower ball outside off, he was looking at third man but his slice doesn't connect",
        "fuller delivery outside off, but just inside that wide line. One of the few. Slashes and a miss",
        "yorker on off stump, dug out",
        "misses a full toss outside off",
        "fuller and wide of off stump, the keeper goes up in appeal to try and ward the umpire away from calling a wide. But" +
        " that was inside the tram lines",
        "length ball outside off, a bit of width. Comes forward and plays a sliced drive to backward point",
        "shortish ball just outside off, hurries onto him with a bit of bounce. He plays a half-hearted pull, and inside-edges" +
        " it into his body",
        "length ball on a fourth-stump line, a bit of movement away from the batsman, who plays defensively into the off " +
        "side without too much footwork",
        "back of a length outside off, rides the bounce and dabs it to backward point",
        "back of a length outside off, angling away further, and still the bowler appeals for lbw when he shuffles across " +
        "and fails to connect with a whip-pull",
        "shortish, some angle away from him. There's plenty of width already, so maybe making extra room was a bit " +
        "counter-productive, and he ends up flashing and missing without a stable base",
        "slower ball outside off, angling away. He tries to angle his bat and steer it to third man, doesn't make contact",
        "length ball angling into leg stump, following the striker who was looking to stay leg-side of the ball. Tries to " +
        "punch towards mid-on, ends up inside-edging into his pads",
        "slower ball, nice and full outside off. He looks to whip it into the leg side, closes his bat face too early, and " +
        "it runs away towards point off the leading edge",
        "excellent delivery, angling across him on a good length, a tiny bit of movement away to accentuate the angle, and" +
        " he pushes at it without too much footwork and doesn't make contact",
        "full on middle stump, and he clears his front leg and swipes it to square leg",
        "back of a length, angling away from off stump. flays it hard to point",
        "slower short ball outside off, doesn't really get hold of the pull, rolls his wrists over, keeps it down in front " +
        "of midwicket",
        "lbw appeal, run-out chance, nothing. Didn't turn at all as he looked to work him across the line and hit his front " +
        "pad. Was going down leg. It ricocheted into the off side, the non-striker wanted the single, he sent him back, and" +
        " there was a bit of confusion but the throw was sufficiently wide to keep him safe",
        "skips down the pitch, doesn't get to the pitch of it, pokes it back towards the bowler. He's bowling really slow" +
        " here",
        "slow, short, too wide to cut but not wide enough for the umpire to signal wide",
        "another slower ball outside off, better length this time. He looks to flat-bat it through the off side, " +
        "inside-edges into his body, and it nearly rolls onto the stumps",
        "down the track and he sees him coming. Bowls it slower and shorter and it moves in and smacks him on the pad as he" +
        " pushes at the ball, searching for it",
        "quickish length ball outside off. He stays deep in his crease and defends",
        "full outside off, can't beat cover with his drive. That was right up, didn't give him too much scope to hit with " +
        "power",
        "slower bouncer wide outside off, loops through to the keeper after he leaves, realising it's too wide and too high" +
        " to slash at safely",
        "loopy full-toss wide outside off, driven straight to cover",
        "down the track he comes, it's floated up outside off and he can't beat cover with his drive",
        "right up there on leg stump. He misses the flick, it hits him on the foot",
        "slower ball, full and just outside off, sneaks under his bat as he looks to launch that over long-on",
        "swing and a miss to a back-of-a-length slower ball outside off",
        "shortish and outside off, flat-batted to the covers",
        "length and outside off, he plays a defence, a la gully cricket with no back lift at all. He has a smile on his face.",
        "straight slow ball on middle, gently defended in front of the bowler",
        "pitched up on off, blocked in front of the bowler. Looked like a slower one",
        "shortish and on off, he rides it in front of point",
        "beautiful delivery outside off, drags the batsman into a feeble push. Beaten emphatically",
        "fullish on off, forward and pushed to mid-off",
        "belated appeal for caught behind. Not given. On a length and nips away off the seam, shaves past the groping bat",
        "and again! Pitched up and outside off, he is dragged into a drive and is beaten again",
        "shapes it away nicely just a bit from outside off, pushed down to mid-off",
        "back of length and swinging away again, driven off the back foot to cover",
        "banana movement from outside off, the batsman detects it quite early, covers his stumps and defends it back",
        "not much swing this time, not much room either and it's pushed towards point",
        "yorker well outside off, he gets a bottom edge to the keeper",
        "bouncer on the leg stump and the batsman sways away from it",
        "swinging in on the pads, he does not get hold of the glance, rolls off the pad to the keeper",
        "on a length and outside off, he loads up for an off-drive, gets an inner edge to leg",
        "on a length and outside off, punched to the covers",
        "pitched up and outside off from round the stumps, sliced towards cover point",
        "low full toss, dips in on off. Pushed to mid-on",
        "the batsman flits around in the crease. Too full and outside off, he adjusts and squeezes it to short third man " +
        "with an angled bat",
        "length ball on off, slower in pace. Pushed back to the bowler off the inner part of the bat. He was early into the" +
        " shot",
        "full and outside off, mishit drive to mid-off",
        "back of a length and on middle and leg. He is cramped for room. He defends it awkwardly",
        "too full and straight, he should have picked that away. Misses out on the flick off the back foot",
        "slower ball on off, he waits on it and pats it to leg. The non-striker wants a single but is sent back",
        "full and outside off, he drives it hard off the front foot, it just lands in front of one of the two fielders.",
        "looped up and jags away outside off, the line drags the batter forward, he loses his balance and falls over as he " +
        "misses the flick. The keeper fluffs a stumping chance. The bowler has a facepalm moment.",
        "straight roller, defended",
        "short and wide outside off, slapped to the covers",
        "pitched up and outside off, drilled to the covers, where the patrolling fielder makes a diving save",
        "back of a length and comes in on off, pushed back to the bowler",
        "lifter from the bowler, the batsman half-ducks out of the way",
        "on a length and on off, dabbed to point with an open face",
        "he makes room outside leg, the bowler follows him. He manages a toe-ends it, the ball rolls back to the bowler",
        "backs away, the bowler nails a yorker, right in the blockhole. The former jabs his bat down and keeps it out",
        "good length, holds the line just outside off stump, defended watchfully",
        "fuller on the stumps, he calmly pushes it down the track, he bowler cannot stop it, mid on does",
        "shortens the length, it comes slowly off the track as he rolls the fingers over it, pushed to the off side",
        "stands on the crease and tries to punch on the up, but mistimes the length ball to mid off",
        "wants to dab this short of a length ball and run, but chops it too close to the keeper",
        "that bounced and zipped past the outside edge, he felt for this length ball leaving him with the angle outside off",
        "pitched up just outside off and again he finds the field on the off side with a checked drive",
        "comes down and slogs on the leg side, misses this time as the ball misses the leg stump",
        "this one swings away from well outside off, Faf pokes and misses again",
        "much fuller outside off, he nudges it straight to point",
        "bangs in the bouncer outside off, he lets it go",
        "length delivery outside off, pushed into the covers and Raina screams no!",
        "full toss just outside off, the batsman drives but gets an inside edge on leg",
        "full on the off stumps, and he pushes it back to the bowler",
        "slower than usual, just outside off, pushed back to the non-striker's end",
        "goes in the crease and works the ball to midwicket",
        "turns it away a bit from well outside off, left alone",
        "dropped by the bowler himself! Short and flat with some bounce, he went back in the crease and slapped it back to " +
        "the bowler, who got both hands to it over his left shoulder but the ball popped out. It wasn't a touch chance at " +
        "all",
        "leans forward and blocks the length delivery into the covers",
        "slower length delivery on middle stump, he defends it on off",
        "short ball turning towards the leg side, worked straight to midwicket",
        "straighter one outside off, he cuts it straight to short third man",
        "some turn for the length delivery going away from middle, defends it towards point",
        "makes room and dabs the turning ball to short third man. No time for a run",
        "length delivery on the stumps, leans forward and blocks it",
        "this one goes the other way as he opens up by going back to pull but takes it on the pad",
        "bit of flight outside off, he comes forward and drives towards mid-off",
        "length delivery just outside off, he cuts it late to point but there's no time for a run",
        "superb delivery to start but that's going down leg! Inbound ball around leg stump and the batsman had no room to " +
        "flick it on the leg side. He tried but was struck on the pads",
        "in the block hole outside off, he chases without any footwork and misses it",
        "room on offer outside off, it's on length, and he hammers it down straight to mid-off",
        "short ball angling away from outside off, Simmons turns on his back foot and pulls to midwicket",
        "no room as it's a back of length ball on off stump, pushes it off the back foot towards cover point",
        "slower through the air and turning into the batsman, he works it to midwicket",
        "flighted length delivery towards leg as he makes room again, but can only manage to push it back",
        "drives the ball late from outside off to point",
        "he comes down the track, the bowler bangs it in just outside leg and he chose to sway out of the way",
        "straight and on the stumps, he defends it back to Nehra",
        "inner edge this time as he looks to swish at it outside off and finds point",
        "slightly straighter one outside off, swatted to midwicket",
        "touch fuller and turning in towards middle and leg, he opens up and pushes to cover",
        "much slower and turning in, leans forward and defends with an inner edge",
        "length delivery outside the off stump, driven into the covers by the batsman",
        "he makes a lot of room and the bowler lands in a perfect yorker well outside leg which the striker misses, no wide.",
        "sliding in almost towards off stump, slices it to backward point",
        "sliding towards middle and leg, comes forward and blocks",
        "works the ball from outside off towards point",
        "much shorter outside off and it's sliced towards backward point where a dive saves a few runs",
        "hammers that full delivery back to the bowler, very quick and low catch to the right but he can't hold on to it",
        "nice length delivery just outside off, he looks to work it fine but misses",
        "makes some room to target the off side but gets an inside edge on the leg side",
        "wide well outside off, he slashes it straight to point",
        "makes room and only manages to push the ball to cover",
        "low full toss on the stumps, driven straight to cover",
        "flattish towards leg stump, taken on the pads as he looks to work it to leg",
        "length delivery on the stumps and he pushes it back",
        "accurate length delivery on off stump, he defends it back",
        "swing and a miss outside off! Length delivery swinging away past the batsman as he drives but misses",
        "pushes the length delivery to cover, comes out of his crease but is sent back and has to dive to make his ground. " +
        "Not a direct hit, though",
        "quicker outside off with some movement, he swings hard and misses!",
        "swing straightaway! Full and swinging in on the pads, flicked to short midwicket, who makes a sharp diving save",
        "fuller, tight line, close to off now, he opts for caution and shoulders arms",
        "on a length and outside off, Gayle throws his bat at it, flat-batting it ram-rod straight, so much so it hits the" +
        " stumps at the non-strikers'. Nor much power behind that",
        "fraction short and outside off, he swat-pulls it back to the bowler. Not well-timed again",
        "back of a length and outside off, flat-batted to mid-off. Smith runs across and keeps it to a dot",
        "good length and on off, camps back and defends it in front of point",
        "similar length on middle and leg, he hacks and drags it to mid-on off the inner part of the bat",
        "nips down the track, the bowler pulls his length back. He swings and does not connect. Nice TV-friendly carry " +
        "through to the keeper",
        "length on off, pushed back to the bowler",
        "this does not bounce at all! Full and curves away outside off, he wafts and gets beaten",
        "full and attacking the stumps, blocked back to the bowler",
        "length on middle and leg, tucking up the batsman for room. Some inward movement here as well. Pushed quietly back" +
        " to the bowler",
        "pitched up and teasing him outside off. He swishes his bat out of the way",
        "full and straight, clipped to midwicket",
        "on a length and outside off, right in the hitting zone. He loads up for a lusty club over midwicket but only " +
        "connects with thin air",
        "back of a length and on off, he solidly blocks it to the covers",
        "pitched up and on off, presses forward and pushes it back to the bowler",
        "looped up on off, patted into the covers",
        "slid through quicker outside leg, he misses the glance and takes it on the pad",
        "fired wide outside off, he reaches out and flashes it to point",
        "he flits down the track, looks to go over the covers and misses. The bowler pulls his length back outside off. " +
        "Loads of bounce and zipping through outside off",
        "back of a length and outside off, left alone",
        "similar length and outside off, he aims to force it through the covers. Mishits it to the fielder",
        "on a length and comes in on middle, worked to the right of short midwicket",
        "on a length and outside off at 129ks, AB waits on it before dabbing it to the right of the keeper",
        "length and outside off, ventures down the track. Swats and can't connect",
        "back of a length and close to off, he does not have enough room. Plays a jabbing punch to the covers",
        "back of a length and outside off, moves away further. He slashes and gets beaten",
        "he nearly nicked this off! Fuller and swerves away outside off, he pokes and watches the ball skim past the outer " +
        "edge",
        "on a length and outside off, he camps back and plays it to point with an open face",
        "very full and on middle and off, AB is cramped for room, pushing it back to the bowler",
        "slid through on off, pushed back to the bowler, who dives to his left and stops the ball",
        "darted flat and wide outside off, he lets it pass. Just inside the tram-line",
        "AB steps down the track and drills it back at the bowler, who sticks his left hand out and intercepts the ball. " +
        "They go to the TV umpire for a return catch. Strange, since they did not claim the catch. Replays show that it had" +
        " bounced in front of him. Bump ball, good judgement",
        "length ball on off, dabbed to point",
        "good length and curves away with some extra bounce outside off. He swishes and only connects with thin air",
        "the bowler has his hands on his head. Might have been a slower ball. The batsman is early into the slog and misses" +
        " it. The ball misses the leg stump by a whisker",
        "length on off, he loads up and plays a flat-batted push back to the non-striker's end",
        "he fires in a yorker at the base of off, jammed back at the bowler",
        "on a length and outside off, he swings wildly and does not connect",
        "on a length and angling away outside off at some pace, played defensively to point",
        "drifting onto the hips, does not get hold of the flick",
        "full and angling away wide outside off, he is caught on a fishing expedition. Beaten",
        "pitched up and moves away outside off, keeps low and beats the feeble little push",
        "pitched up and outside off, driven to backward point, who dives to his right and makes a sharp stop before getting" +
        " up and thumping his chest",
        "much fuller on off, draws the batsman into a forward-defensive push to point",
        "back of a length and on off, jabbing punch to mid-off after pressing forward",
        "back of a length and on off, too close to cut. He ends up chopping it to the covers",
        "back of a length and outside off, Smith shuffles across, gets on top of the bounce and punches it to the covers",
        "pitched up and outside off, he lays into another cover-drive. This time he finds the fielder",
        "flighted and on off, down the track. He does not meet the pitch of the ball and takes it on the pad",
        "slid through outside off, punched to backward point, diving stop from the fielder there",
        "fuller and outside off, dabbed to backward point",
        "back of a length and zipping through outside off, he is beaten all ends up, prodding and missing",
        "fuller and outside off, knocked towards backward point with an open face",
        "pitched up and outside off, he held this one back. Chipped in front of a diving mid-on",
        "full and on middle and leg, worked to midwicket",
        "back of a length and on middle and off, he is cramped for room. Defensively pushed back to the bowler.",
        "dropped shortish and outside off, flat-batted back to the batsman without much timing",
        "lifter climbs on the leg stump, he pulls and does not connect",
        "back of a length and on middle and leg, he camps back and pushes it back to the bowler",
        "back of a length, defended back to the bowler off the inner part of the bat",
        "good length on off, defended tentatively",
        "back of a length and outside off, he shoulders arms",
        "bouncer, sails over to the keeper, after beating the batsman on the hook",
        "hoodwinked by the change-up. Outside off, a poke and a miss",
        "loopy delivery, grips in the surface and moves away. Diffused in front of the covers",
        "fuller on middle and leg, clipped to the right of the bowler, who dives and intercepts the ball",
        "banged in short on off, fends it to the right of the keeper",
        "back of a length and sliding away outside off. He has a crude swipe at it, does not connect",
        "push and a miss to a length ball angling away outside off",
        "on a length and outside off, pushed to backward point with an open face",
        "back of a length and on off, defended",
        "Morris steps out, makes room. Swings and misses a shortish ball",
        "short and wide outside off, stabbed to backward point",
        "pitched up and angled in on off, he covers his stumps and shuts it down to the off side",
        "lowish full toss outside off, he pushes and misses. The ball was not far away from the off stump",
        "good length on off, pressed to the covers",
        "short and wide outside off, even with the cross batted shot he can't slice it away",
        "length and angling away outside off, he pokes limply and gets beaten",
        "comes in on off. Defensively pushed to the covers",
        "back of a length and zipping through outside off, moves away late as the batsman flails and misses. Excellent " +
        "carry through to the keeper",
        "back of a length and curls away outside off, he wafts and gets beaten as the ball skims past the outside edge. No " +
        "feet movement",
        "shortish and holds its line on off, dabbed in front of point",
        "on a length and outside off, he presses forward and pushes it to cover-point",
        "back of a length and on off, hangs back and defends",
        "full and straight, flicked out to midwicket",
        "back of length and on middle and leg, strikes Faf on the thigh",
        "good length ball, pushed back to the bowler",
        "on a length and angling away, he has a crack at it and misses. He is beaten soundly",
        "low full toss dips just a shade outside off, pushes at it and the ball slips underneath his bat. This was the " +
        "slower one",
        "back of a length and outside off, punched out to the covers off the back foot",
        "pitched up and on off, slow in pace. Tapped in front of point",
        "fuller and on off, looks to drive but drags it to mid-on off the inner part of the bat",
        "good length ball on middle, worked to the leg side",
        "back of a length and on off, punched to the covers, straight to the fielder",
        "on a length and outside off, pushed to point. He comes halfway down the pitch in search of a single but is sent " +
        "back",
        "slid through quicker, looked slower in the air. The batsman keeps it out",
        "back of a length and outside off, not all that short. He cuts and does not connect",
        "flatter and on middle, whipped to short midwicket",
        "floated up and spins away outside off, rips past the groping bat",
        "full and outside off, pushes it to point with firm hands",
        "short and rises on middle, blocked back to the bowler",
        "too full and outside off, mishit drive to the covers",
        "canny slower bouncer outside off, dupes the batsman, who is early into a pull and fails to connect",
        "banged in short and rises, the batsman goes for a pull and misses. Takes it on the body",
        "low full toss on middle, bunted to short midwicket, where he dives to his right and makes a sharp save",
        "pushed through, moves inward. Poked out to the leg side",
        "flat and on the leg stump, nudged to the leg side",
        "flatter and quicker, moves away outside off. Pushed to the covers",
        "full on off, down the track and dragged to short midwicket off the inner part of the bat. He dives to his left and" +
        " makes a smart stop",
        "good length on middle, pushed back to the bowler",
        "banged in short and outside off, he seeks to pull and manages an inside edge to the leg side off the pad",
        "pitched up and the bowler knocks on the doors of the channel of uncertainty, he hangs back and swishes his bat out" +
        " of the way",
        "even fuller and outside off, he leaves it alone",
        "back of a length and angled in close to off, he is cautious as he ignores it",
        "shortish and width outside off, he winds up for a massive blow and toe-ends it onto his pads. Ouch, he hops " +
        "around in a bit of pain",
        "back of a length and outside off, he jabs it defensively to the covers",
        "looped up on off and turns away, he stays back and ignores it",
        "flat and turning away outside off, slapped to the covers, where the batsman takes it on his knee",
        "slid through on the pads, worked to the left of short midwicket",
        "lobbed up on off and turns away, plays for the straighter one and pokes it out behind point",
        "full and straight, tucked to midwicket, straight to the fielder",
        "back of a length and on middle, worked to midwicket again",
        "good length ball on off, dabbed with soft hands in front of point. He aims for a speedy single but has to retreat",
        "back of a length and on off, bunts it to the off side",
        "looped up generously and away outside off. Thi one draws him forward and beats his feeble little waft",
        "shortens his length, punched back at the bowler",
        "fullish and on middle, patted back to the bowler",
        "he lines up for a swat, he is wary of it as he fires it outside off. Eventually opts to shoulder arms",
        "goes up for a big lbw appeal. This was back of a length around off, strikes him on the front pad just above the " +
        "knee-roll. Height is an issue. Impact may have also been outside off",
        "shortish and comes back into the batsman, cramping the batsman for room. He can only defend it back to the bowler",
        "tossed up on middle, pushed back to the bowler",
        "flatter and on off, defended back to the bowler",
        "tossed up, he misses the defensive push and takes it on the pad",
        "back of a length and on off, knocked in front of short cover",
        "good length ball on middle, he is forward and across to defend it",
        "back of a length and on a fourth-stump line, he camps back and punchily defends it back to the bowler",
        "tossed up, hanging in the air and spins in to strike him on the pad. Hit outside the line of off",
        "pitched up and outside off, pressed to the covers",
        "pushed through on the pads, glanced to the leg side",
        "fullish and outside off, another leave from him",
        "good length and just a shade outside off, ignores another one",
        "back of a length and just outside off, punched to backward point off the back foot",
        "fuller and pushed through on middle, defended off the back foot",
        "fullish and on off, down the track and flicked to mid-on",
        "pitched up and on off, pushed back to the bowler. He is struggling for timing and power",
        "back of a length and outside off, stops on Gayle. He seeks to cut and chops it to backward point",
        "fuller length on middle, driven to the covers",
        "loopy slower ball on off, he is early into the drive and has to settle with an inside edge onto the pad",
        "another slower ball outside off, grips in the pitch and has some extra bounce on it. He seeks to turn to leg and " +
        "is beaten",
        "width on offer outside off, forces it to short third man",
        "flighted and held this one outside off, chipped in front of covers",
        "fuller and straighter, worked to leg",
        "gives this more air on middle, blocked to the right of the bowler",
        "the batter steps away outside leg and the bowler is wary of it as he follows him. Quietly defended",
        "banged in short and hurries on off, he looks for a pull and gets an inside edge onto the thigh",
        "back of a length and on the leg stump as he steps away and makes room. He checks his drive and sends it to short " +
        "cover. He is halfway down the pitch in pursuit of a quick single. The fielder does not throw the stumps down at the" +
        " non-strikers'. The bowler runs in, looks to whip the bails off but misses. A direct hit would have consumed a " +
        "victim..",
        "fuller and outside off, he wants to launch it out of Vellore but does not connect",
        "on a length, shapes back in towards off, defended to mid-off by Simmons",
        "another half-volley, but it is moving away from the batsman, who pushes this back to the bowler",
        "short of a length, punched crisply, but they have the square field on the off side packed. They know he loves that" +
        " area",
        "a length ball angles across him, and he leaves alone. Superb bowling",
        "short of a length, outside off, sits up a little, which means he hasn't timed the punch well, and finds the man at" +
        " short cover anyway",
        "short of a length, outside off, punched square on the off side, finds cover-point this time",
        "solid front-foot defence as he gets the ball to swing back in a touch",
        "slower in the air, dips on him, creates the distance between the bat and the pitch of the ball, beats the inside " +
        "edge, but is headed down leg",
        "fired into the pads, beats the inside edge again, and draws another dot",
        "short, and he gets away with it as the striker has punched this straight to cover-point",
        "Simmons gives him the charge again, and he slips in a yorker under his bat",
        "Simmons is premeditating a lot. He rocks back early and has made up his mind to pull this no matter the length. " +
        "Eventually this is not short enough to be pulled and squeezes under his bat",
        "a bit round arm, defended in front of the pad",
        "fired in, defended again",
        "totally round arm this time, Defended back",
        "fired into the pads, he is almost at leg slip moving with the angle of the ball, and still appeals for lbw. ",
        "fires one into the pads, and draws a dot",
        "looks to make room, is beaten by an and hit on the pad outside leg",
        "bowls the straighter one, pitches leg and goes with the angle. He is looking for the bounce, and has to defend it " +
        "as he reads it off the pitch",
        "flighted on off, pushed with an open face to cover-point",
        "driven on the up but straight to cover",
        "accurate length ball, cramps Simmons up, defended back to him",
        "pushed back to the bowler and he throws the ball back at the non-striker who has not even left the crease for a " +
        "millisecond",
        "short of a length, angling in, defended back to the bowler",
        "wide length ball, goes for the drive, plays down the wrong line, and is beaten",
        "short of a length, holds its line, is a bit quick too. Beats the edge as he looks to open the face of the bat",
        "bouncer firs6 ball, and Pollard lets it go through to the keeper",
        "on a length, angling in, hit straight to midwicket. He is looking to make a good mini comeback here",
        "short of a length, excellently concealed slower ball. He doesn't pick it, there is no room available, and he gets " +
        "an inside edge onto the pad",
        "and good to see him go back to the yorker. Dug out back to him.",
        "picks the slower ball a touch late, looks for the sweep, and it squeezes under his bat for a dot",
        "a length ball whizzes past the open face this time. No change of pace here",
        "wide length ball, and he is lucky again as he misses out on the extra-cover drive.",
        "Bravo goes wide on the crease, and fires in a yorker that goes. Dit ball",
        "yorker, accurate, no room, can't get under it, and has hit this straight back to the bowler for a dot",
        "starts with a ball that lasers in towards the batsman's toes, he gets his feet out of the way and defends that from" +
        " within the crease, superb riposte",
        "length ball swerving away just outside off, there's a typical GPL slog, meets thin air",
        "length ball on middle and leg, cramps up the batsman, he blocks it towards mid-on",
        "slingy full ball from the bowler, punched back towards the bowler who takes the sting out of that shot with an " +
        "outstretched right hand",
        "swing and a miss from the batsman, pitching on a length and angling across past the outside edge beyond off",
        "back of a length ball on middle and leg, sliced towards point, can't get it past the fielder there",
        "a touch short, a bit of width, slapped towards backward point, where the fielder stationed dives to his left to " +
        "cut that off",
        "goes for a pull as he sees the ball a bit short, he misses",
        "back of a length ball on off stump, defended back towards the bowler",
        "full toss outside off, looks to steer that through the covers, can't find the gap",
        "slower length ball, on middle stump, patted back towards the bowler",
        "short of a length, on off, opens the face but doesn't get a single",
        "length ball outside off, angling away, squeezes under the bat as he looks to drive. Low bounce there",
        "and he is struggling to lay bat on ball. Beaten third time in a row on the drive as a length ball angles across him",
        "and beaten on another cover drive. This time on the inside edge as the ball holds its line as opposed to going " +
        "with the angle",
        "heavy ball, on a length, middle and off. Hits the bat as opposed to the other way around. The leading edge goes to" +
        " cover-point",
        "short of a length, extra bounce, the bowler is giving this everything. Beats the attempted cut with the bounce",
        "a sharp mean bouncer. He is not looking at the ball, throwing his hands up in defence like Mayweather against " +
        "Pacquiao.",
        "short of a length, punched straight to extra cover",
        "Smith is just swinging and hoping for the best. This short-of-a-length delivery stays a little low, moves back in " +
        "a touch, and beats the slog",
        "another slog, and this one skids through to hit him on the pad",
        "short of a length, middle and leg, angles away and stays low to beat the outside edge",
        "short of a length, outside off, moves in a little beats the inside edge as he looks to work this to leg",
        "short of a length, wide outside off, but it shoots through to beat the bottom edge",
        "short of a length, swerves in to beat the cut",
        "short of a length, and beats Smith as he backs away",
        "short of a length, seams in a touch, beats the inside edge, hits the pad, draws another dot",
        "big shout. This is short of a length, outside off, and skids through and seams in to hit him dead in front. The " +
        "umpire doesn't give him. He thinks it is too high as this has hit him on the knee roll, but his leg is " +
        "bent and he is deep in the crease. Awfully close, this. Hitting the top of middle, show the reviews",
        "flighted outside off, looks for the slog sweep and is beaten comprehensively",
        "looks for the reverse-sweep, gets an edge that falls short of short third man. He has not only played an ordinary " +
        "shot but is also caught sleeping. Sends his partner back even though this is the non-striker's call and he would " +
        "have made the run easily. Ball-watching",
        "and for the umpteenth time, he is caught ball-watching. There is a big lbw shout here, but the ball has clearly " +
        "pitched outside leg. " +
        "He wants a leg-bye to short third man but he hasn't moved. raina is nearly run out but the fielder misses on the " +
        "direct hit",
        "short of a length, outside off, beats the punch",
        "short of a length again, and beats him for pace again. Hits his thigh pad as he looks to work this to leg",
        "tossed up outside off, driven but straight to cover-point",
        "lovely bowling. Slow through the air, dipping on him, goes straight on, beats the outside edge",
        "on a length, middle and leg, beats him with the angle here",
        "short of a length, and he fails to get the ball off the square again. The leading edge reaches mid-off on the " +
        "bounce",
        "short of a length, on off, gets extra bounce, beats the edge as the asking rate crosses three a ball",
        "wide length ball, it shapes away to beat the drive",
        "another slower ball, he has no clue about it, and edges it to Patel on the bounce",
        "full and wide, angling away, beats the outside edge as he looks to steer this square",
        "sharp bouncer, beats the attempted pull"
    ];