/**
 * Created by kunal on 15-08-2014.
 */

dot=
[
    "",
    "short ball and a slower one, he softly pulls it to short fine leg",
    "this was jammed full outside off, looks to dig it out",
    "drifting down the leg side and nearly clipped the leg stump on the way through",
    "that's the line! The bowler bowls it on the corridor outside off and the ball shapes away late, fizzes past the edge",
    "this one skidded through quickly and hit the back pad, looked like drifting down leg",
    "missed out, he drills it back to the bowler",
    "a bit too short and he finds cover",
    "makes a bit of room and looks to smash that over the off side and he's beaten",
    "makes a hint of room and the bowler follows him by drifting on the pads, he can only drive back to the bowler",
    "the batsman seems happy to defend",
    "missed out, this was short and Smith could only smack this back to the bowler",
    "can only mistime it to short midwicket",
    "doesn't give him much room as he steers it to point",
    "keeps it nice and straight, goes back and defends",
    "squares him up with beautiful away movement, this moves away late and the batsman was chasing it",
    "he fires that full outside the off stump and he looks to jam it out but misses",
    "drops a sitter! It was length ball and the batsman chips it ever so tamely to short cover, for a moment, the fielder had it covered, don't know how that slipped out",
    "he tamely pushes it to the off side",
    "full and straying on the pads, clips the pads as he looks to flick it away",
    "this one moves away and he pokes at it, nearly edges it",
    "decent shout for an lbw? Straightens and hits him on the top flap as he stays on the back foot, looked close though, appeal turned down",
    " tossed up and he pushes it back to the bowler",
    "he rocks back and cuts but can't beat extra cover",
    "very low and wide full toss, slips under the bat swing",
    "skidding across him from a length and he cannot do anything with it",
    "tries to launch this length ball over midwicket, inside edges onto pad",
    "cuts across the left-hander from back of a length, is pushed back",
    "tries to square drive a full and widish one but is beaten",
    "well bowled, he angles it full and wide of the batsman this time",
    "sharp stop from the keeper, this was a wide away swinging full toss and he got a thick edge to it, it was travelling but the keeper reacted in time",
    "he tries to slog to leg, and the slower one keeps very low to beat him, that was very close to leg stump too",
    "he steps out looking to go over square leg but is hit on the pad",
    "full and quicker on the pad, he tries to whip it square but misses",
    "angled flat into the pad, the batsman misses as he goes down on a knee",
    "comes down the track and flashes it straight back to the bowler",
    "lovely delivery, angled in just outside off, makes him play, and straightens and kicks past the edge",
    "slower and fuller, he taps it to extra cover",
    "tries a cut but is done in by the extra bounce",
    "tries to whack a length ball down the ground but it moves away and beats him",
    "moving away outside off, left alone",
    "flashes at a wide delivery that ws going away and misses it",
    "this does not come in and goes past the outside edge as Pujara pushes forward to defend",
    "ending around off this time, he goes on his toes and keeps it down",
    "a wide yorker, the batsman misses it",
    "full and wide once more, but fortunately for the bowler, it is driven straight to backward point",
    "a full delivery driven to mid off",
    "tries to make room and upper cut, but is beaten by the bounce on this back of a length ball",
    "cracks this overpitched ball for extra cover",
    "slower length ball on off, knocked back down the track",
    "slower outside off, flashed to backward point",
    "goes hard, but now he finds the bowler",
    "smacks a pull to midwicket",
    "overpitched outside off now, and he has slammed it straight to extra cover",
    "looks to step out, the bowler shortens it, and the batsman defends it square on off",
    "pitched up and angled into middle and leg, defended",
    "a touch fuller and square driven to backward point",
    "appeal for leg-before as he pushes forward, but this was doing too much with the angle",
    "pitched up and angled into middle and leg, defended",
    "a touch fuller and square driven to backward point",
    "goes back to punch it to the bowler",
    "full on leg again, Samson clips it straight to midwicket",
    "he tries to pull this too hard, but mishits it, couple of bounces to mid on",
    "calmly moves forward and pushes a good length ball to extra cover",
    "jumps out of the crease now, bowler shortens the length, and the batsman knocks it back",
    "comes in with the angle and is pushed down the track",
    "defends a good length ball on off",
    "mistimes a forcing stroke in front of square on the leg side",
    "tries to force this good length ball from just outside off, but turns it straight to mid on",
    "moves across to off stump, pushes forward and defends this length delivery to covers",
    "gentle length ball on the pad, nudged away",
    "beaten on the sweep",
    "now this one straightens, and almost hits the off stump, missed by inches, the batsman had no idea this time",
    "no clue about this one as it rips across him to beat a waft",
    "wants to slog this over midwicket but fails to connect to the length ball just outside off",
    "he fires the next one in, it moves away from the batsman and beats him",
    "a full ball pushed to extra cover",
    "goes back to a pitched up ball and pushes it to extra cover",
    "tries to dab this length ball to third man but it kicks sharply and beats him",
    "opens the face to this one climbing around off, finds backward point",
    "takes a step across and lets this go with the angle, he is expecting a wide call, but is not getting one",
    "bowled full at the stumps and blocked back calmly",
    "beaten on the cut, this was fullish outside off",
    "tapped to backward point",
    "goes across the this time, and the batsman misses the sweep, had his foot grounded even as the keeper took the bails off",
    "goes after a widish one, but under edges it on the bounce to the keeper",
    "diving stop from at short extra cover saves some runs",
    "goes back to a good length, defends it late, down the track",
    "leans into a push but it goes off the inner part of the blade for midwicket to make a diving stop",
    "bowled slowly again, he pushes it to backward point, sets off, but there is no single there, and he gets back just in time",
    "waits on this one outside off and decides to cut quite late, hits it to backward point",
    "squeezes a good length ball to covers",
    "punches this good length ball to the bowler who parries it behind him",
    "walks out to a good length ball, is too close to it, and can only knock it to point",
    "short and climbing outside off, left alone",
    "they are running away to nowhere, the batsman goes through with another punchy drive in the air, mid off is there, and had he hit, the non striker would have been out, he had wandered that far out",
    "lunges forward and has a heave but is beaten by this pitched up ball",
    "a nothing shot, tries to belatedly guide it towards point, beaten by the pace and bounce",
    "finds the radar now, hits his favoured back of a length, and it rears up at the striker, who is fortunate not to edge it",
    "good one, this one goes away after drawing the batsman into a forward push, beaten by some margin",
    "he tries some kind of a reverse scoop, but this is shortish and bounces past",
    "top stuff from the bowler, first he pings it into the blockhole, the batsman knocks it to his left, and the bowler goes flying like a goalkeeper to pouch it",
    "walks far across but fails to get bat on this delivery that goes past leg stump",
    "makes room outside leg, this one is on middle and staying a bit low, he toe-ends it to the bowler",
    "bowls it around off, the batsman tries to dab it away, but cannot get much purchase on it",
    "comes out again, the bowler pings it full into the pad, the batsman adjusts to nudge it square",
    "he comes forward and runs it to point, not getting anything for that",
    "pushes forward, and it is a bit of a leading edge down the track",
    "dances down and goes through with an elegant attempted loft down the ground, but misses the ball entirely",
    "now he bowls a conventional delivery, it is defended towards cover, non-striker wants non-existent singles, but escapes as the throw is weak, and bowler is standing too far behind the stumps expecting a stronger one",
    "flying stop by the man at point, as the batsman guides this slowish length ball to his right",
    "it just isn't happening for the batsman at the moment, he tries to make some room and manufacture a cut, but is beaten by some extra bounce",
    "the batsman is cramped for room this time, plays it back",
    "beaten on the pull now, it is a slower delivery, and the batsman played too early",
    "too good for him again as he fails to get bat on ball this time",
    "length ball just outside off, and the batsman plays a nothing shot, opening the face and ultimately pushing well inside the line",
    "he walks across the stumps, but the bowler gets one to nip in and hurry on into the pads, too high, though",
    "the batsman is looking clueless at the moment against this aggresive burst from the opposition, another one comes in, cramps him for room and he does not help himself by hopping and getting into a tangle",
    "now this one comes in a long way after pitching, thick inside edge on to pad flap as the batsman hops again",
    "pitched up for the drive outside off, left alone",
    "beaten, as he follows this length ball which bounces and moves away sharply",
    "holds the line and zips through past the right-hander from a good length outside off, batsman pulls his bat inside the line late",
    "going across him, played out towards point",
    "produces a beauty first up, bangs it in shortish, angles it in, then gets it to move away just outside off, the batsman is off balance, he is jumping, and even as he tries to leave it half-heartedly, it pings the bat, but falls short of slip",
    "the batsman lifts his bat to let it pass",
    "super, had the batsman beaten first up, this pitches short of a length around middle and leg and moves away as the batsman tentatively pushes at it",
    "he reverts to the line just outside off, this one goes straightish, and the batsman comes out of his crease and lets it be",
    "that's a good ball, really full and difficult to get away",
    "a full ball on the stumps and he drills it to cover",
    "stays back and chops it to point, not quite in his hitting length",
    "drifts down the leg side and he clips it towards short fine leg",
    "bowls that full on the stumps and he digs it out back to the bowler",
    "close shout for an lbw, across the line and may have missed the stumps",
    "he looks to cut but misses",
    "plays this ball back to the bowler",
    "big swing and a miss, the frustration getting to him? Outside off and he misses it completely",
    "drives square on the front foot and backward point does well to stop it",
    "skids on the pads and he looks to work it to the leg side but the ball rolls to the off side",
    "This time, he makes him play again and he defends this to the off side",
    "bowls it straight and he stands back and defends",
    "this was still a bit short and he went back and chopped it to extra cover",
    "this was angled wider across the batsman and he flashed at it, smart bowling",
    "tucked him up for room there, he went back to defend and the ball nearly rolled over to the stumps",
    "this was full on the off stump and he pushes it wide of mid-off",
    "kept him quiet there by bowling it dead straight, on middle and skidded through, he defends",
    "Dropped! This was coming straight at his face, slower ball and the batsman was looking to drive straight and it was chipped back at the fielder, he cupped his hands in front of his face, slipped and couldn't hang on",
    "This one just managed to evade the batsman's slashing flick and the stumps en route to the keeper",
    "full and speared in on the pads, the batsman looks to swipe it away but gets struck on the pads. No appeal, would have gone well down leg",
    "on the pads, nudged into midwicket",
    "He changed his stance, but not the grip on his bat as he reverse swept to third man",
    "back of a good length and outside off, he slashes and misses.",
    "The batsman gets gets a life now ! It was flighted outside off and he thumps it into the covers. The fielder dives full length to his right and almost hand it but it popped out",
    " back of a length and he was setting up for the front foot pull, doesn't succeed",
    " charges at him but as he finds the length is a little shorter he settles for a nudge through square leg",
    " has trouble beating that man at midwicket as the bowler continues darting in length balls on the stumps",
    " shortish delivery on leg stump, worked to midwikcet",
    "fired in on the pads, the batsman can't put it away with the flick. Shakes his head",
    "comes forward and pushes at the length ball on off stump. Gets an inside edge to mid-on",
    "shortish on off stump, the batsman punches it back to the bowler",
    " pushed through quicker on off stump, he goes for the sweep but gets an inside edge",
    " slower ball accompanied by a big grunt. The batsmanwas on the front foot and goes for that pull again, but the ball just scuttles underneath his bat",
    "charges down the track and the room he's made for himself allows the carve into the covers but the fielder dives to his right and keeps it to none",
    "pitched up on middle and leg, the batsman plays across the line and is struck on the knee-roll. Big shout from the bowler again but this time the umpire doesn't agree. It was tight",
    "a little more effort behind this delivery and the bounce beats the batsman's cut",
    "short but not quite wide enough, the batsman flat bats it down to mid-off.",
    "full and outside off, the batsman looks to blast it through the covers but mistimes it. The fielder cuts the angle and dives to his right to keep it to none",
    "hint of inward dip to start off, the batsman negotiates it well by coming forward and presenting a straight bat",
    "That was a brilliant piece of bowling ! He must be rewarded with a wicket soon !",
    "Defended off the front foot, the bowler is keen to give the batsman a piece of his mind.",
    "Where did that come from ? The bowler has managed to bowl an absolute beauty out of nowhere!",
    "The batsman was into the shot early, the ball drops just short of square leg. Sheepish smiles all around.",
    "That was a whisker away from off stump, dangerous leave there by the batsman",
    "What a terrible delivery, the bowler is lucky to have been let off this time",
    "And we have a comedy of errors here ! The batsman pulls away from a half hearted attempt, the ball hits the bat nevetheless, a needless run is called for. A better throw from point would have the non striker out nine times out of ten, but this time the ball just pops up to the man backing up, no run taken.",
    "A hint of movement, but the batsman strides forward to block.",
    "Play and a miss ! The bowler has his head in his hands.",
    "Played on the up, but the fileding captain has done his homework",
    "The intent was there, but the connection wasn't, the ball sails through to the keeper.",
    "he's struck on the front pad and he seemed pretty adjacent too! But the ball might just have gone over the stumps. He was walking across and the bowler responded with a slower delivery just back of a length. Deceived the batsman as it darted back in at him and his guide to third man was nowhere close to it",
    "just outside off, pushed back to the bowler.",
    "fires a low full toss on leg stump and the batsman goes for the flick a little too early, resulting in a leading edge back to the bowler.",
    "good length ball outside off and the batsman goes for the booming drive through the covers but there is no timing on the shot",
    "slower ball outside off and the batsman is flummoxed by it. Goes for a slog-sweep and misses",
    "searing delivery fired in down the leg side and the batsman cannot get bat to it",
    "crisply punched into the covers as he leans forward to the fuller delivery angled across him",
    "dug in short on middle, defended",
    "The batsman leaves it watchfully",
    "strides forward and defends to point.",
    "how close was that! It was a shorter ball and he looked to dab it in front of point for a quick single. The fielder swoops on the ball and sends in the throw in one motion. The non-striker has to pull out a full-length dive as well and it saves him, just about",
    " the bowler has a giant smile on his face after executing the perfect wide yorker to keep the batsman quiet",
    "cramps up the batsman, back of length once more, squirted that away to the leg side",
    "beaten outside off, great line there, bounce as well as he drops it a touch shorter",
    "Was that low or what ? The batsman gets his bat down in time to keep that one out",
    "he was moving outside off again and Nadeem follows him with a fuller delivery. The slash doesn't beat point",
    "shimmies down the pitch but he pulls the length back and the batsman can only nudge it to square leg",
    " rock-solid forward defensive from the batsmen at the striker's end",
    "fullish on off stump, he goes forward and blocks into the covers. Searches for the single but the non-striker says no",
    "comes down the track and carves a full and wide delivery to point",
    "skips down the track but the ball seems to stop on the pitch before reaching him. Gets hit high on the bat as he pushes into the covers. Fell not too far away from the fielder either",
    "outside edge off the slower ball outside off. Tries to steer it down to third man but it bounces short of the keeper",
    "spears it in on middle and he was looking to clip to midwicket. Gets a leading edge to point."
];
one=
[
    "",
    "tries to scoop this from way outside off stump, but he edges it into his body instead, scampers a single",
    "cranks up and has a slog, but he can only mishit it tamely through midwicket",
    "slower one picked from outside off and slogged on the bounce to deep midwicket",
    "steps out and heaves, manages a single to long on",
    "comes out, but cannot get under the ball too well, drives it to long off",
    "had walked outside off trying to go leg side, but this was bowled slow and full, and he dabs it to third man",
    "steps out and clips a full delivery to long on",
    "he gives this full delivery everything, but it just rolls across the outfield to long on",
    "goes straight and aerial now, on the bounce to long on who has run across",
    "moves across and whips this full one wide of fine leg, but is getting only one",
    " low full toss, he drives with an open face to the sweeper",
    "length ball worked to deep midwicket",
    "full just outside off now, the batsman looks to drill it over extra cover, but only hits it along the ground to long off, he is visibly angry with himself",
    "almost bowled him, full delivery pushed through, the batsman plays it rather uncertainly, and only an inside edge saves him",
    "charges out, but only manages a thick inside edge to square leg",
    "cut away for a single",
    "comes out again and swings hard, mishits to long on",
    "bowled slower outside off, the batsman slogs, a thick inside edge runs behind square leg",
    "charges out and forces it through extra cover",
    "comes out a tossed up ball, takes it on the full and hits it to long on",
    "dabs a length ball to point and goes for a quick single",
    "that could have been out, back of a length down the pad, and the batsman disdainfully helps it in the air, but fine leg is in the way",
    "slogs a very full one to deep midwicket, along the ground",
    "follows him with a full one as the batsman makes more room outside leg, but can only dig it out",
    "sitter dropped, a fielder settles under this leading edge at mid on and it goes straight through his hands to smack him on the face, he indicates he lost it in the lights, the batsman was trying to forcefully whip it over square leg",
    "a chance, the batsman moves down the track and to the leg side, bowler follows him with a slower one, he pops it back in the air, but it is just out of teh fielder's reach",
    "short of a length, worked to mid on's right",
    "turned wide of mid on",
    "walks out and dabs a length ball past slip to third man",
    "ull into the pad and turned in front of square leg",
    "opens the face and runs a length ball to third man",
    "tailing in, worked off the pad to fine leg",
    "moving in and rising from back of a length now, the batsman tucks it to fine leg",
    "dropped, he jumps out and slams it into the bowler, and it rolls away into the off side, shout of 'catch it', that was struck very hard, and slipped through the bowler's fingers",
    "follows him as he makes room outside leg, the batsman lofts the length ball, couple of bounces to long off",
    "slow, short and very wide, he wants to attack it but is done in by the lack of pace",
    "very full and angled in from wide of the crease, driven to long on",
    "almost a run out, a slower length ball is turned through midwicket, he wants the second, but the fielder releases the ball quickly even as he falls to the ground, the batsman dives back, direct hit could have meant trouble",
    "moves forward and drives a full one to long off",
    "nudged square on the leg side",
    "full and angled into the pad, turned to deep midwicket",
    "goes across, the bowler pitches it up on off, and the batsman eases it to long on",
    "flicks a full delivery in the air off the pads, mid on runs it down to his right",
    "a slower one into the pads now, it pops up in the air as he nudges it, but falls in the gap at square leg",
    "angled across him now, and he flashes it past point's dive, third man runs across",
    "waits on this length ball now, it holds its line outside off, and he guides it to third man",
    "he thrusts the slog sweep and gets to the other end",
    "he makes plenty of room outside leg, the bowler follows him every inch of the way, and hits him with a short of a length ball, it pops up towards point, there is a chance for a run out, but the throw misses",
    "short and wide slower one, he mistimes a cut to the sweeper",
    "tries the reverse sweep, not much on it, but enough for a single wide of short third man",
    "squeezed into the off side for a single, could have been tight",
    "down the track and eases it to long on",
    "bowls it full and wide, the batsman is eyeing the leg side but he has to hit it down to long off",
    "taken from well outside off and worked to deep square leg",
    "that looked dead straight, but the umpire spots the inside edge and remains unmoved",
    "takes this from outside off and manages a top edge on the slog sweep, it weakly loops and falls in front of deep midwicket",
    "shortish outside off stump, he cuts it in the air, in the gap at cover and down to the sweeper",
    "a top edge loops towards short third man as he tries a reverse paddle",
    "punches this one sliding across him to extra cover, he had backed up too much and would have been gone in case of a direct hit",
    "punches a good length ball to extra cover, he has a go at the non-striker's, and misses",
    "skips out to this tossed up ball and eases it to long on",
    "hits it along the ground and straight to long off",
    "turned off the pad to deep midwicket",
    "taps a length ball to wide mid on and is taking it easy on the single before he realises he has to hurry, makes it, throw misses anyway",
    "short of a length into the pad and with one leg in the air, he tucks it to fine leg",
    "very tight single, short ball dropped in front of cover, the non-striker was gone in case of a direct hit",
    "and one more in the blockhole, terrific execution from the bowler, the batsman can only squeeze it to the off side",
    "in the blockhole, dug out into the pitch and over the bowler, Shakib is running back for the second, but he is sent back, no way the non-striker was making it back in time",
    "cracks a full ball straight down the ground, long on slides and saves it, but they have taken only one",
    "has a heave at a pitched up ball, which travels high and falls at vacant mid on",
    "cannot get under this full delivery and squeezes it out to the off side instead",
    "well adjusted, he did not have the length or the angle to swing leg side, so he waits and chips it over the bowler",
    "full toss on middle, the batsman turns it straight to square leg, there is a direct hit here, but the batsman has made it back in time, he was a tad slow in turning around",
    "he's charged out but mishit this lofted stroke, a fielder comes forward at long on, he dives in front, but it bounces ahead of him, nice effort",
    "that did quite a bit, it was angled sharply into the pad initially and seemed to straighten on the batsman, who defended and accepted the single as it rolled square on the off side",
    "pulled with intent, straight to deep midwicket though",
    "dropped, the batsman checks a pull and hits it high to short midwicket, he gets both hands to the ball as it comes over his head, parries it over, but falls to the ground and even as he stretches, the ball falls well out of his reach",
    "comes forward and opens the face to pick up an easy single to cover-point region",
    "comes down the crease, the bowler slows it down, and batsman stops and adjusts to knock it to the off side",
    "a good length ball outside off, that is pushed to mid off for one",
    "opens the face and guides a back of a length ball to third man",
    "comes down the track, but is cramped for room by a shortish one, knocks it past the non-striker for one",
    "turns it towards midwicket for a single",
    "ending inches outside off stump after being pushed across on a length, he adjusts to guide it to third man",
    "back of a length, coming in with the angle, worked to midwicket who makes a sliding stop to keep them to one",
    "softly drops a back of a length ball ",
    "moves across to this length ball outside off and square drives towards third man",
    "pushed away on the off side",
    "this back of a length ball is angled in, tucking him up, he squeezes it to the on side and setts off, direct hit was needed",
    "yorker, dug out to point, they jog through for one. The fielder at long-off, but they don't chance the second",
    "slogs at a length ball, gets an inside edge for one",
    "nearly bowled him. Another variation form the bowler, the batsman gets a bottom edge on the slog sweep, but it misses the stumps.",
    "the ball is shorter than ideal for such a shot, and he pushes it towards point for one. The fielder swoops in, underarms this towards the stumps, and he would have had his man had he hit. Good effort, though",
    "punched to deep cover",
    "on the pads, gets a single to long-on",
    "long hop, pulled away to deep midwicket for one",
    "drilled to long-on as he pitches this up",
    " into the ribs, tucked away for one",
    "slow through the air again, clipped away for a single to leg",
    "pushed into the leg side for one",
    "short of a length, pretty straight, bunted to leg for one. A collision in the middle as he dashes across to field. No unpleasantness between the two, and we seem to have some action off the pitch as well.",
    "goes after it without feet, and edges it over point for one",
    "down the wicket to drill this down straight of long-off, and the flying fielder saves three runs there with the dive and a quick throw",
    "down the wicket, more in hope than conviction, gets a thick outside edge for one",
    "on a length, outside off, driven to deep cover",
    "steered to third man for one",
    "short of a length, holds its line in front of middle and leg, bunted to leg for one",
    "outside off, punched away, a diving save at cover-point saves three runs",
    "short of a length, just outside off, dropped towards cover for one",
    "short of a length, angling in, gets an inside edge onto the pad for a single",
    "too full, too straight, clipped away for a single",
    "pushed wide of mid-off for one",
    "short of a length, tucked away off the hip",
    "short of a length, angling in, gets off the strike with a bunted single to leg",
    "full in length outside off and he drives him down to deep cover",
    "slower ball and he drives him to cover",
    "he looked to pull that with more force but he held back and softly places it to square leg",
    "bowls it flat and restricts the big hit, goes back and cuts hard to point",
    "flatter one and he mistimes it to the leg side",
    "comes down the track and he drives him to long-on",
    "he rocks back and thumps it down to mid-off",
    "he makes room and looks to cut but gets an outside edge, short third man cuts it off",
    "full, driven to long-off",
    "slower ball and he punches it to the off side",
    "Dropped ! The bowler gives it more air and tempts the batsman to go for the slog, it was hit flat and dipped towards the man at long-on, dived forward and couldn't catch it, not the easiest take either",
    "he tucks it away behind square leg",
    "shuffles across early and he mistimes the flick to the leg side",
    "fetches that from the off stump and clips it to the leg side, good use of wrists",
    "good running, he merely pushed it with soft hands towards cover and sets off quickly, the non-striker is quick to respond",
    " he goes back at the crease and clips it to the on side",
    "just a short arm flick towards midwicket and they complete a single",
    " punched towards mid-off and there's a misfield and that allows a single",
    " fullish on the pads and clipped just wide of mid-on",
    "he bowls it full on the stumps, pushes it just in front of mid-on and sets off",
    " this time he strays on the pads and he clips it away to the leg side",
    " fires this one full outside off and he digs it out to cover",
    "that's a good yorker and Dhawan really had to dig that out to the leg side, nearly lost his balance",
    "minimum footwork but those hands are good enough to cut the shortish delivery down to deep third man",
    "tossed up on off stump, defended with soft hands into the covers",
    "dropped and it is the most comical of the lot. The batsman goes for the reverse sweep but this time he gets it off the shoulder of the bat and it goes straight up. The short third man lunges at the ball with both hands outstretched, but to no avail.",
    "fired in on middle and off, the batsman closed the face too early and gets a leading edge to long-off",
    "nearly a yorker on middle and leg, dug out to long-on",
    "short and on the pads again, pulled to deep square leg",
    "good length ball on middle and off, he strides forward to push it down the ground to long-on",
    "slower ball on off stump, the batsman isn't fooled as he dabs into the covers and rotates the strike",
    "low full toss outside off, he opens the face and slices it to deep point",
    "finds the yorker outside off and the batsman pushes it down to long-on",
    "flat-batted down the ground as this is shortish and outside off",
    "the batsman rocks back and cuts to the sweeper",
    "length ball outside off, the batsman is balanced at the crease and pulls it to deep midwicket",
    "good length ball on and around off stump, the batsman punches it down to long-off",
    "drags it from well outside off and pulls down to long-on. Short of a good length",
    "good length ball outside off, it was a little slower too and he taps it down to the man at deep cover",
    "fires it in on middle and leg and it's punched down to long-on. Nicely bowled",
    "shortish and on middle, pulled to deep midwicket",
    "stays put to loft the overpitched delivery to long-off. Hit in the air but falls short of the man rushing in",
    "full on middle, clipped away to deep midwicket",
    "goes for the yorker on off stump, the batsman is good enough to dig it out past the bowler's extended left hand",
    "nice and full outside off as he drags it away wide of long-on",
    "fired in full and outside off, the batsman steers it through point with an open face",
    "backs away and slashes a length ball behind point",
    "thumped down the ground but long-off is on hand to keep it to a single. Doesn't get it quite right",
    "ample opportunity to swing those shoulders and he lashes to the sweeper again",
    "another full toss on middle and leg, the batsman flicks wide of long-on",
    "skips down the track and looks to beat short cover but has to settle for the single after the misfield",
    " round the wicket and fires it on the stumps and he drills it down to long-on",
    "full toss outside off, pushed down the ground to long-off",
    "fullish and outside off, he goes for a hoick to midwicket and gets an inside edge",
    "dances down the track while making room for himself and laces a drive to long-off",
    "pulls all the pace off this ball as he targets the wide line. He reaches out and slashes it over the infield",
    "full and just outside off, he drives all along the ground to deep cover",
    "fired in on middle and leg, the batsman shuffles across and clips it behind square leg",
    "goes shorter and quicker, the batsman works it for a single to midwicket",
    "slower ball angled into him, worked away into the midwicket region",
    "Tighter line on off stump and a fuller length. Pushed to long-on",
    "good length ball cut off the stumps for a single through the covers",
    "stays back and tucks the short of a length ball away into the square leg region",
    "flatter delivery on the stumps, picked away through midwicket",
    "a little slower on off stump, the batsman is wise to it and guides it off the back foot to third man",
    "continues back of a length but this is the slower one, Smith works it into the leg side",
    "full and angled into the pads, he isn't able to whip it away and has to settle for a single",
    "waits on this nicely, stays beside the shortish ball and taps to deep cover",
    "back of a length on middle and leg, he goes back and blocks and manages an inside edge that squirts out into the on side",
    "the lack of pace surprised him !. Think this held in the pitch a little more, as the batsman who was looking to drive on the up had to check his shot. Went uppishly but it evaded the cover field",
    "fullish and on the stumps, he pushes it down to mid-on",
    "hustles for a quick single and had the bowler's throw broken the stumps things might have been interesting. The batsman nudged to the right of the bowler and took off just that smallest bit late",
    "drifting on the pads and the batsman eases it to deep midwicket",
    "shortish and angled in at him, whipped away calmly to deep midwicket",
    "good length ball on middle, the abtsman looks to whip it away but there isn't enough pace on it this time",
    "quick, length ball on the pads. Whipped to deep midwicket",
    "his trip down the track ends up being detrimental as he yorks himself. Dug out to cover",
    "The batsman was making room but the bowler follows him. Again hits the bat hard as he runs it down to third man",
    "good length ball on middle and off, clipped into midwicket",
    "his use of feet turns a shortish ball into a length one which is belted to long-off",
    "neatly clipped into the vacant midwicket region",
    "Drags a short ball from well outside off to deep square leg",
    "Very thick bottom edge and it would have tested a regular keeper as well.",
    "thick outside edge that evades the slips. The batsman was bringing a closed defensive face down on the ball and is deceived",
    "back of a length and outside off, steered to deep third man",
    "taps and runs to point as he rides the bounce on this shortish ball outside off",
    "widish yorker, nudged into the covers and raced off for the single",
    "stays deep in his crease and late cuts it down to deep third man",
    "low full toss shaping in at off stump, the batsman was forward and punches to long-off",
    "strides down the track and succeeds in getting it to deep midwicket",
    "shortish and outside off, the batsman goes back and cuts to point who misfields and the two batsman hesitate in the middle of the pitch wondering if they should go for the single. By the time the ball is taken control of though, they rush through for the single",
    "drills the low full toss to the sweeper.",
    "opens the face to slice this full delivery outside off to deep cover",
    "slower short ball and the batsman was just a little too exuberant. Mistimes the pull and finds deep square leg",
    "the batsman looks to steer it down to third man but bottom edges it. The non-striker sees the ball going into a gap behind the wickets and rushes up for a single",
    "nicely done by the batsman. Realised the ball was defended with soft hands, into the off side, just about enough to sneak a quick single",
    "slower delivery kept right up there on off stump, the batsman is wise to it as he adjusts his stroke and pushes to mid-off",
    "nudged to mid-on",
    "rips a back of a length delivery right across the batsman. Well-managed in the end as he plays with soft hands and lets the outside edge run down to third man",
    "dabbed off the back foot to third man as the bowler is persistent with the off stump channel",
    "back of a length on middle, the batsman tucks it into the midwicket region and they race across for a quick single",
    "the batsman looks to whack it through the covers but doesn't reach the pitch and ends up mistiming it. Single taken though",
    "goes back, very deep in his crease and dabs it behind point.",
    "cut away, but there is protection at deep square leg. Lunged forward and kept it all along the ground",
    "the bowler saw the batsman charging at him and pulled his length back. The batsman blocks into the off side and a fielder rushes in from short cover to cut the angle.",
    "shortish and outside off, the batsman goes back and cuts to deep point",
    "tapped to third man as the bowler tightens his line outside off",
    "flicks a good length ball off his knees to the left of short fine leg",
    "makes room outside leg and beats cover with a punch",
    "goes down the track and eases this into the covers. The fielder is vigilant, and had he struck the stumps direct, we would have had a wicket on our hands",
    "full and on the pads again, whiped to deep square leg",
    "slower ball outside off stump, tapped away to point for a single",
    "full length on middle, punched down the ground",
    "full delivery outside off smeared through point",
    "dropped at short fine leg. The batsman was making big-time room outside leg and the bowler followed him with a full delivery speared in at his pads. He flicks it to gully, where a sitter is dropped",
    "slogged to deep midwicket. Ugly sort of a shot",
    "goes wide of the crease and presents a slower ball outside off, the batsman is out of his crease and pulls to deep mdiwicket",
    "the batsman walks across to push this fuller delivery down the ground",
    "low full toss on the pads, glanced it down to long leg",
    "he's gotten away with that. It was a length ball outside off and the batsman can only hit it as far as deep cover",
    "pulled uppishly, but it bounces short of the man at the long leg boundary. Picked up the short ball on middle and leg and helped it along, but because of the slower pace the ball went up in the air",
    "this time the pull doesn't quite work, a bottom edge onto the body as he throws his bat at that one",
    "pushed through on off stump as the batsman taps it into the covers and goes to the other end",
    "comes down the track and thumps it into the covers",
    "he almost falls over in his attempt to make room. So much effort into his shots and it only ends up a single to long-off as he flat-bats the short ball",
    "full toss on off stump, the batsman flicks to deep midwicket. Took the toe end there",
    "skips down the track and thumps it down to long-off. The bat turns in his hands, not exactly the best piece of timing.",
    "that's a dolly and he's dropped it at short fine leg! Mr fielder, what have you done?! Clipped uppishly but straight to the man, at abound waist high and at a very comfortable pace coming at him. But it pops in and then pops out",
    "bit of room on offer and he essays a late cut to find deep third man",
    "another drop and it's in the square boundary on the off side. Raced down the track and slapped a short ball hard and flat. the fielder had to run in and come forward but he spills it",
    "whipped away into the leg side as those strong wrists take over",
    "waist-high full toss and he swipes it away to deep square leg",
    " short again but this was just a touch quicker and the batsman pulls to long-on.",
    "slower ball outside off, the batsman waits for it and thumps it to deep cover",
    "overpitched outside off, the batsman's flashing blade gives work for the sweeper"
];
two=
[
    "",
    "fuller ball and he drills it down the ground, the batsman did well to push for the second",
    "slower ball and he drills it down the track and wide of mid-on",
    "punches it towards point and the fielder needlessly fires the throw towards the stumps, it was wide and nobody was backing up",
    "good running, the batsman stays back and clips it wide of midwicket and charges off aiming to take a couple, the fielder does the chasing and the throw was wide at the batsman's end",
    "he had to hurry there, cut wide of cover and the batsman had to scamper the second, throw just wide of the bowler's end",
    "stays beside the line and he steers it to third man, who slips",
    "down leg and swept fine.",
    "fired full on the pads and he whips it to deep square leg and the fielder dives and does well to save the boundary, he too looks to have hurt himself",
    "he stays back and knocks it to the off side",
    "full outside the off stump and he squirts it wide of point",
    "he drills it down to long-on",
    "tossed up on the pads and the batsman gets on his knee early and slogs him behind square, deep square leg picks up",
    "he comes down the track and lofts over extra cover",
    "on the pads and he works it wide of midwicket",
    "this was shorter and he swivels to pull but doesn't force it away, places it wide of square leg",
    "this was drifting on the pads, he clips it away wide of short fine leg, the striker slips as he completes the first run",
    "fuller and towards the stumps and he whips it away wide of square leg",
    "wide low full toss, placed it in the air through the covers, and comes back for two more",
    "slower length ball, the batsman waits and pulls it wide of deep midwicket for a couple",
    "full and wide, smeared through extra cover, a fielder throws himself to his left at sweeper cover and saves the boundary",
    "length on the pads, turned in front of square leg for two",
    "full delivery hit wide of long on for two more",
    "manages to force one straight down the ground as he charges out, a fielder comes racing from long on, dives across and stops it a few inches from the rope",
    "waits and places this full delivery wide of long off for a couple",
    "slogs a length ball, hasn't got hold of it, but it clears midwicket",
    " wristily turns this length ball from middle and leg to deep square",
    "full and wide, hit through cover, two fielders converge on the ball, one picks it up, the other avoids dashing into the first.",
    "swings hard again but toe-ends it to extra cover this time",
    "swept hard off middle, deep square leg will get to it with a run to his right",
    "full outside off now, the batsman smears it over extra cover, work for the sweeper, he nearly overruns it, but manages to save the boundary",
    "has a go at this full delivery but mishits it through midwicket, will pick up two",
    "tries to deposit this delivery over deep midwicket, but he gets too much underneath this length ball and it sails high before plonking down well inside the rope",
    "gets one away, shuffles across and swings hard through square leg, it is cut off by the deep fielder running from fine leg",
    "he tries to go over short fine leg again, but hits this full delivery straight over the keeper instead, the fielder runs around from third man to stop it",
    "The batsman loses his bat as he reaches out to dab this yorker wide of third man, where the man throws himself to the ground to save the boundary",
    "makes room and tries to go over extra cover, toe-ends it over the infield for a couple",
    "misfield by hort third man, the batsman opened the face and guided this fine, but it should have been stopped really",
    "worked in front of square leg and they will come back for the second",
    "rides the bounce on this back of a length ball and guides it past point",
    "now he moves across the stumps, and works this off the pad and wide of fine leg",
    "width outside off, it is guided to third man's right, who scrambles to stop it",
    "cannot get under this full ball around off, but they will benefit from the mistiming to steal two at vacant midwicket",
    "goes inside out over extra cover, the fielder in business again with a run from long off, dives and parries it away from the rope",
    "he moves a tad towards the leg side and crashes this pitched up ball through extra cover, long off gets to it",
    "goes hard at a full delivery but it does not have enough in it to split long on and long off",
    "moves across outside off and tries to slog it, but it is too full, and he mishits it to deep midwicket, had the throw hit, he was gone by miles",
    "shortish from the bowler, and the batsmen fancies a pull, does not get hold of it this time but will pick up two through midwicket",
    "this one is pitched full just outside off, and the batsmen, to his credit, does not go hard at it in desperation, he eases it into the gap at extra cover",
    "nicely done, he walks out, take this a bit high on the bat but goes through with the shot, timing it past point, third man is around, though",
    "on a length, angling in, mis-hit wide of long-on, where the fielder does well again to save two runs",
    "a touch too short, punched away between two men deep on the off side",
    "pushed wide of long-on this time, and the come back for the second",
    "The batsman looks to drag it from outside off, and gets a top edge that clears mid-on",
    "too straight this time, clipped away past square leg for two",
    " pushes it down to long-on and they manage a couple",
    " fielding blooper there from the man at cover, the ball was driven to him but he was very slow to react, he moved to his right while the ball was to his left, realised a bit too late, the captain has goofed up, they can only smile",
    "hammered down the ground and he nearly claimed the non striker, long-off does well to cut it off",
    "this was banged in short and he hooks it to fine leg",
    "he opens the face and steers it to the off side",
    "gets on his knee and fetches it from the off stump and looks to slog and it is in the air and drops short of long-on",
    "keeps it nice and straight and the batsman gets on the backfoot and works it wide of midwicket, does well to run two",
    "he flicks it to the leg side and sets off quickly",
    "gives width outside off and he cuts wide of point, it looks like going all the way to the rope but the fielder does well to slide and cut it off",
    "he gives him a bit of width this time and he chops it just wide of cover",
    "whipped away as he meets the ball in front of his pad and picks up a couple to deep square leg",
    "The fielder races back, keeping his eyes on the ball over his shoulder and flings both hands out in front of him but the ball doesn't stay inside. How costly will that drop be? It was full and the batsman shoveled it straight over the top with very little timing.",
    "opens the face to dab this back of a length delivery behind point",
    "lovely timing! Stood up tall and punches this shortish ball through point. Rode the bounce and he found the gap to the left of the fielder there",
    "cuts behind point after shimmying down and meeting the shortish delivery with an angled blade",
    "picked away through midwicket as this was a length ball on middle, good hustle between the wickets",
    "Manages an awkward looking reverse sweep and they take two as the quicker length ball goes off his gloves",
    "Moved his front leg away to make room for the swing of the bat",
    "full and wide outside off, looks to heave it over the covers but gets a leading edge that evades the fielder running back",
    "punched through the covers as this is a length ball fired in on off stump",
    "slower length ball outside off, the batsman looks to slog over deep midwicket but gets a bottom edge to deep third man. The bowler is aghast",
    "excellent work from the man at the third man boundary! Short and wide outside off as he threw his bat at it. Gets a thick outside edge that seemed set for four, but he hunted it down well",
    "drilled past the man at mid-off but he gives chase and keeps it to a couple",
    "drops it shorter, defended for a single, and there is a misfield as there's some awkward bounce for the bowler ",
    "this one doesn't rise and Parthiv latches onto a pull to deep midwicket",
    "a little too straight with a good length ball and the batsman clips it away to long leg",
    " ball pitching outside leg, the batsman was setting up to launch it over cow corner but the length was too full. Squirts it away to deep square leg",
    " backs away and drives past the man at extra cover",
    "fullish and outside off, he pushes it down to long-on",
    "clipped away neatly off his legs",
    " darted in on leg stump, the batsman swivels on the back foot and sweeps it down to long leg",
    " good length ball on middle and leg, turned away to deep square leg for a couple",
    "good length ball which grips the pitch and darts outside off, the batsman muscles a mistimed pull through midwicket"
];
three=
[
    "clips it to the leg side and it was racing away to long leg and Sharma did a fine job sliding to cut that off",
    "fuller ball and he makes room and places it wide of long-off, where the fielder does really well to slide and cut it off",
    "flays a back of a length ball high over extra cover, hasn't timed it, and sweeper keeps it inside with a dive",
    "now he leans into a length ball going across him, hasn't timed it that well, and it slows down as it approaches the deep extra cover boundary, and is pulled back",
    "tries a huge slog sweep to one bowled outside leg, outside edge flies to short third man's left, he messes up the stop",
    "mis-hit falls safe. Another good bouncer, the batsman looks to pull, ends up to-ending it, and the edge lands smack in between long-on and long-off",
    "We could have had a run out here. The batsman continues to live on an edge, jumps out of the crease, gets a thick edge. it flies over cover, chased it down well, keeps it in, relays it to a fielder, who slips and relays it to another, who spears the throw in, and the keeper messes the run-out up by flicking the bails without collecting the ball",
    "the batsman is late into the pull again, and this time the top edge evades fine leg."
];
four=
[
    "he gives him width and he chops it wide of backward point and they take three",
    "tossed up on middle and leg and he slogs him over midwicket",
    "nicely played, the keeper was up, a hint of width, no slip and he gently steered this down to third man",
    "that was a gift, friendly full toss on the pads, all he had to do was shuffle slightly and work it wide of the keeper",
    "crashed that past the gap! This was on a good length wide outside off, slapped that wide if backward point",
    "lovely use of the wrists! This was a half volley on the stumps, shuffles across the stumps, works the wrists and places it wide of midwicket",
    "drops it short, the batsman lifts that on the up, good contact to launch that over cover, a couple of bounces before reaching the boundary",
    " makes room and caves a full ball over point to finish the innings with a boundary",
    "falls inches short of the rope, this was too short and wide outside off, the batsman hops and upper cuts it down to third man, a little more power and it would have gone all the way",
    "That was smashed with such force and the bowler did well to get his head out of the way, full ball and the batsman made room and smashed that down the ground",
    "this time he fires it full on the stumps, the batsman drives firmly wide of extra cover, the field was up",
    "too good for the boundary rider! This was too full and wide outside off, the batsman shuffled a long way to meet the ball, placed wide of cover and the sweeper couldn't stop it",
    "strays down leg, fine leg leg was up, he sweeps fine and it's an easy boundary",
    "picks the vacant area, this was drifting on the pads, the batsman shuffled across early and neatly chipped it over short fine leg",
    "this was dropped fractionally short, he read the length early and pulled him flat over square leg, one bounce and over",
    "this was pitched up wide outside off, in the hitting zone, lofts through the line and clears cover, long-on cannot cut it off",
    "invites the batsman to use his feet, comes down the pitch and lofts him over mid-off",
    "sped away quickly, this was too full and wide outside off, the batsman gets across and smashes it along the turf wide of cover",
    "this was the right length for the batsman to pull, length ball a touch wide outside off, he fetches that and pulls along the ground wide of midwicket",
    "out of nowhere, he has connected with a scoop, he goes outside off, bends the knee and turns this length ball to the fine leg rope",
    "swings at a full delivery, and a thick inside edge runs fine down the leg side",
    "opens the face and drives through the covers for four more, he is toying with the field",
    "there is no width here, full and on middle stump, but the batsman has opened the face and timed it in the gap past extra cover",
    "third man is up, this is short and wide, and he hops to cut it miles over the man",
    "this time he goes way in front of square, dragging the full delivery over the infield, no chance for the sweeper",
    "reverse sweep that clears point very comfortably",
    "he sets himself up for the reverse sweep even as the bowler is about to release the ball, and connects the low full toss to beat short third man",
    "he goes over mid on, goes back and to the leg side, and swings it over the infield",
    "played with lots of aggression, width outside off, and he cuts hard behind point",
    "the bowler staying wide outside off and the batsman going off this time, a full toss is lifted easily over extra cover",
    "a wide yorker now, but in vain, third man is up and he squeezes it wide of the fielder",
    "a full toss outside off is smashed back down the ground, and beats long on and long off",
    "full into the pad, he shuffles a bit, and manages to run it fine",
    "he uses his reach, reaches the pitch of this one outside off and swats it straight down the ground",
    "picks the gap at deep midwicket, this is full and angled in, and he clears front leg to swing it away",
    " lofts this pitched up ball over extra cover now, stretches forward and powers it away",
    "he carts this full delivery to long who drops it, and it runs behind him into the boundary",
    "tries to mow his big slog sweep, manages only an inside edge that somehow eludes his stumps and trickles away to the ropes",
    "he goes back, has some width this time, and cuts hard to the third man rope with the man up in the ring",
    "makes good use of the poor delivery, goes back in the crease and slogs hard over midwicket",
    "hammered down the ground, the umpire stretches his right hand to signal no-ball and at the same time, also gets out of the way as the batsman cracks this pitched up ball straight back",
    "some hitting from the batsman, this is not short at all, but he's picked it up so cleanly, it flies to the deep midwicket rope",
    "he's leaned into this drive, timed it on the up, and placed it past short extra cover's dive",
    "he swivels to pull it in the air to the deep backward square leg boundary",
    "steps out, stretches a bit, and lifts it flat over extra cover",
    "outside edge, there is no slip, and these are four fortunate runs, came forward to defend, but this was the one that went the other way",
    "that is would have pierced the bowler right in half, it's hit hard down to him at long off, couple of bounces, the bowler bends and cups his wrists to stop the ball, but it goes through",
    "what a shot, he's walked out, and his momentum has given this lofted push so much distance, it's almost gone over the deep extra cover rope, it is in the gap anyway",
    "scooped fine over the keeper, the batsman comes across, bends and gets enough bat on this length ball",
    "length ball angled in to the pad, and the batsmans tucks it very fine",
    "now the cut, width provided, and the batsman capitalises with a sharp cut",
    "the slog sweep, an almighty top edge of a slog sweep, no one at deep square leg, and it plonks down near the rope and rolls into it",
    "that is as clean a hit as any, the batsman has made some room outside leg stump, and blitzed this length delivery over mid off with a straight, high followthrough",
    "too short, too wide, he intentionally flays it in the air and comfortably clears cover",
    "connects well, slightly fuller, the batsman comes forward and lifts it over covers",
    "length in to the pad now, and the batsman steps down the track and turn it neatly through midwicket",
    "shot, gets on his toes and punches this back of a length ball in the air just past point",
    "madness out there, he turns it to midwicket, he wants the single for about a few steps, then he doesn't, his partner wants it some more, then he hesitates, decides to go for it, Agarwal has no choice, the captain has made it for him, the throw is way off target at the keeper's end, the man backing up follows up with a worse one at the bowler's end, and it runs all the way to the straight boundary",
    "keeps eyes on the ball and twists his wrists very late to send the ball to the rope",
    "this is a very high full toss, and the batsman has sent it screaming over short third man with a neat reverse paddle even as he swivels away to avoid getting hit",
    "poor line to given the situation, good length down the pads, and he swipes it to the deep backward square boundary",
    "and finds the boundary this ball, whips a full ball angled in, beats midwicket's jump, and also a sliding attempt in the deep",
    "neatly done, very full outside off, not too much width, but the batsman opens the face and times it to deep backward point rope",
    "he's swung a boundary to deep square leg, reached forward and mowed it in the air",
    "down the pads, swept hard, and well wide of short fine leg",
    "the batsman trying to assert his flow, on the leg side now, this is shortish, be swings it off the front foot and times it to the deep square leg rope",
    "he wants a single after pushing to the leg side, non-striker is not interested, is half way down when he turns, he should have no chance, but he will instead get bonus runs, as the throw is nowhere near the keeper, let alone the stumps",
    "he reverse sweeps a full ball from around off, and beats short third man with a crisp connection",
    "a really clean hit, the bowler continues to push it towards leg stump, and the batsman carts it in front of square leg once more",
    "sees him coming out, pushes it quick into the pad, the batsman swings in front of square and beats the man in the deep",
    "this has been cracked through extra cover, the batsman walks across to a full and wide one, and clobbers it",
    "short again, but in striking range this time, and he slams a pull in the air, to the deep midwicket boundary",
    "connects for some returns, the bowler digs in the short offcutter, and the batsman is waiting to pull it hard to the deep midwicket rope",
    "the batsman forehands it over mid-off for four. Not clean connection, but the man is up in the circle",
    "No energy behind this bowling. Gentle, on a length, wide, and the batsman rashes it over cover for four",
    "no sting behind it, and he has been dismissed through midwicket region. This is a slower bouncer.",
    "down the wicket, takes a length ball, swipes it through midwicket for four",
    "lovely square push drive. Full outside off, the batsman presses forward, covers the swing, and meets it with an open face. Bisects square cover and cover",
    "short and wide, outside off, the batsman might as well celebrate his birthday right now.",
    "this time it's a low full toss and he makes room and places it down to the vacant deep point region",
    "he doesn't need a sighter! This was too full and wide outside off, Faulkner made room and smashed it wide of cover, the sweeper can't cut it off",
    " he makes room to a length ball and cuts him hard and fast past backward point, big gap there",
    "he whips a full delivery on middle and leg with such force that the ball blazes away wide of midwicket",
    "a pressure-relieving boundary, this was flighted on the pads, he was on his knee early and swept it firmly to fine leg",
    "this was nicely punched down the ground wide of mid-off off a full delivery",
    "outside edge but no slip, this was full and swinging away, he drove hard at it and the edge flew past the keeper and down to third man,",
    "in the air but very safe in the end, it was pitched up and he made a bit of room to carve that over the off side, bisected mid-off an cover very well, the field was up",
    "committed to the sweep early, tossed up on the pads and he gets down and sweeps with conviction",
    "a clean pull, this is poor bowling, too short, sits up nicely for the pull, one bounce to deep midwicket",
    "short and wide outside off, slapped to deep point",
    "clears the infield, this was a length ball, ",
    "overpitched and on the pads, clipped through midwicket for four",
    "overpitched ball outside off, eases that through cover for four, doesn't try to power that one, gets the placement right",
    "welcome boundary there, the bowler errs by bowling it too wide outside off and short, he makes room and slaps it down to deep point",
    "looked a bit ungainly but effective, he shuffled across his stumps, exposed all of them and slogged him just wide of short fine leg",
    " good placement again, third man was up, he had the width outside off to steer it wide of point",
    "that's a lovely cover drive! Half volley outside off, he leans forward and drives crisply wide of cover, races away",
    "full outside off and he lofts him over mid-off",
    "Third man was up and he knew that, the ball was angled across and he had enough width to deftly steer that wide of short third man and backward point",
    "that's emphatic! Short ball pulled powerfully to the deep midwicket boundary",
    "in the slot and he has hoicked it over the long-on boundary. Cleared his front leg and let the hands go",
    "that was clever. Waited on this shortish ball with just a little room and he dabbed it fine of short third man and it just skimmed away",
    "big full toss outside of and he's reverse pulled it over the head of short third man",
    "he essays a lovely, orthodox cover drive. All along the ground and stamped with his considerable power.",
    " there wasn't much room to get under this but somehow he does and the sweep skims hard and flat to the deep midwicket boundary",
    " tossed up on off stump, the batsman plants his front leg down the pitch and slogged it away to the deep midwicket boundary. The fielder tried to flick it back into the field of play, but he was stamping on the boundary ropes while doing so",
    "drifting down on the pads and he sweeps him one-bounce to the long leg boundary ",
    " and he's switch hit to the point boundary! Changed his stance and then the grip on his bat and blasted it away to the fielder down there. Pulled out a diving effort but couldn't pull it back",
    "races down the track and though the bowler went short and tried to put it past the reach of the batsman's lashing blade",
    "gets another fortuitous edge to the third man boundary. Too much room on offer and an open blade is enough to take advantage",
    "low full toss wide of off stump and the batsman squeezes it away to the third man boundary",
    "length ball on off stump, the batsman swings madly and gets it more off a thickish inside edge than anything. But it's got enough wood on it to find the boundary at deep midwicket",
    "outside off, the batsman gets down on one-knee and reverses sweeps it to the third man boundary",
    "hint of room outside off and the batsman goes back and opens the face to beat short third man",
    "that's a bazooka down the ground!",
    "slashed behind point and this time the fielder isn't quick enough to cut it off.",
    "offers up another overpitched delivery outside off, the batsman says thank you very much and lofts it over extra cover",
    "bit of extra bounce outside off the off and he rides it well enough with a cut that sails well over the infield. Couple of bounces and into the hoardings",
    "digs it into the middle of the deck again and the batsman is comfortably pulling them from the crease to the square leg boundary",
    "shifted his weight onto the back foot and he's just picked up this short ball from outside off and carted it to the square leg boundary. Whistled away to the boundary",
    "smashed! Overpitched and he eases onto his front foot and drills it through extra cover",
    "got a lot closer to off stump with the back of a length delivery, the batsman goes for the pull and gets a top edge that sails over the keeper's desperate leap",
    "he tried to outsmart him by bowling short but the batsman is so good square of the wicket. Raced down the track and though it was dug in short he lashed it over the infield to the point boundary",
    "he manages to thump it through midwicket. Not enough pace to worry the batsman here",
    "this is short and it allows the batsman to rock back and pull in between the long-on and deep midwicket regions. Muscled away.",
    "this time he picked the line wonderfully well. Saw it drifting into the pads and swung it dead square",
    "flat-batted to the long-on boundary! Cleared his front leg and slammed the back of a length ball outside off stump",
    "Charges at him while making room outside leg and carves it over extra cover",
    "hoisted over the top. Got under it nicely and muscled it down the ground. The fielder at long-on can only usher it to the boundary",
    "smacked through extra cover. Made room for himself, opened his shoulders up and thumped this length ball on middle to the boundary",
    "this length ball has pummeled this between long-on and deep midwicket. Clears his front leg and let the bat just swing freely",
    "walks around his crease and he has upset the bowler's rhythm wonderfully well. Moved outside leg first and lured him to angle the fuller ball in at him. And once that was done he quickly switched outside off and lap swept it to the long leg boundary",
    "length ball carted away to the deep midwicket boundary! Terrible length to bowl and the batsman pounces on it as he clears his front leg and dismisses it.",
    "walks at him and swings it away to the long leg boundary! Top shot from the batsman. Picked it up off a length and whipped it into the gap",
    "This was full and outside off and he has reverse flicked it to the third man boundary! That is an astounding stroke!",
    "in the slot on off stump and he has smeared it to the extra cover boundary. Made room outside leg and launched it and more importantly found the gap",
    " dug in short and he takes it on to hook it powerfully behind square",
    "Perfect connection this time, and the length ball on middle is dispatched to the deep midwicket boundary. Hadn't middled it but he did hit the gap",
    "cleared his front leg away to whip the fuller delivery on leg stump away to the square leg boundary. Such quick hands ",
    "blindly swings again and this time he gets the benefit of a thick outside edge that scurries away to the third man boundary",
    "another slower ball as he rolls his fingers down the side of the ball. The batsman plants his front foot down the line and goes for that big golf swing again. Another outside edge, another third man boundary. The bowler throws his head back in dismay",
    "the batsman had to reach for it but he did manage to connect it well enough to beat the boundary fielder",
    " deep midwicket has a chance this time but he has rushed in too much and makes a mess of what should have been a simple catch. Low full toss on middle and the batsman hoicked it off the front foot and gets a boundary for his trouble",
    "great effort from the keeper there, flinging himself to his left to nearly grab that one off the batsman, who just glanced that leg-side delivery",
    "the ball is dropped short by Parnell, the batsman is quickly onto it, pulling it away in front of midwicket for four",
    "full and angled across him, the batsman swings from the crease and gets a thick outside edge that flies away to the third man boundary, despite a tumbling effort near the ropes",
    "spots the batsman charging and digs it in short, but makes the mistake of bowling wide. The batsman slaps it over point. Thumping boundary !",
    " pulls out the sweep and it's timed extremely well. He's not bothered with keeping the ball down and why should he, when he hits it in the gap",
    "that was a snorter of a bouncer. The eyes came off the ball and he was mostly taking evasive action when the bat sort or jutted out and the top edge was taken to run away to the boundary at long leg",
    "that was a set up for the batsman and he's walloped it to the square leg boundary. The bowler bowls waist-high short ball and it was the slower one as well. Comfortably dispatched. The ball seems to have caught the cables of the spider-cam and usually it provides grounds for a dead ball, but the umpires give a little leeway"
];
six=
[
    "this was pitched up outside off and he picked the length and slammed it over long-on",
    "this is bad bowling, nobody patrolling the deep on the off side and he bowls it short and wide outside off, the batsman goes airborne as he slaps it flat over deep point",
    "clears the long boundary! This was short of a length and the batsman was in position early for the pull, picked the length and clubbed it over deep midwicket",
    " and distance! That kept going and going....the batsman was down the track to a length ball and he slammed that into orbit over long-on, went several miles up in the air",
    "that was clean! Tossed up by the bowler and the batsman went down the track and took it downtown, the ball clears the straight boundary",
    "he gets low and slices it over cover this time",
    "the bowler tries a slower one, the batsman takes it from just outside off, and swats it in front of square leg",
    "another maximum, one more full toss from teh bowler, the batsman crashes it over extra cover",
    "low full toss, around off, he steps forward and launches it over long on",
    "goes back and flat-bats it into the sightscreen",
    "slower length ball down the pad, the batsman bends his knee and smacks it in front of square",
    "full, slow and on the stumps, he is backing away to leg, and has carted it high over long off",
    "goes off side this time, this is short and leaving him on the angle, he takes a couple of steps out, and forehands it over backward point",
    "a full toss, the batsman uses his wrists and swats it over deep square leg",
    "picked cleanly over deep square leg, full into his pads, and the batsman sends it soaring",
    " pings it back of a length outside off",
    "steps out now, is not to the pitch, but goes through with a mighty loft, and clears wide long off",
    "a full toss angled in, he wallops it high over deep midwicket",
    "this is overpitched on middle and leg, all he has to do is clear his front leg and smack it high and straight",
    "overpitched straighter now, and the batsman cracks it over the bowler",
    "this is overpitched on the stumps, and he's gone dead straight over the bowler, and over the rope",
    "this one will go, he tosses it up just outside off this time, the batsman makes some room outside leg, and lofts, very cleanly once more, over extra cover",
    "this has been picked up from just back of a length and dispatched with disdain over the deep midwicket boundary",
    "the batsman tees off now, picks this from a length and sends it soaring over the long on boundary",
    "mid off is up, this is pitched up, outside off, and the batsman lifts it calmly over the fielder",
    "he swings a quick delivery way over the deep backward square leg boundary, that is into the upper tier",
    "a full toss outside off, the batsman walks across and laps it miles over short fine leg, and over the rope too",
    "that's been swiped over deep square leg for six, short of a length, just above waist height for the him, and he attacks it eagerly, as if he was waiting for the length",
    "gets one away, jumps out, reaches this widish one and smashes it high over long off",
    "swiped this with a massive top edge off his pad, the tall fielder is there at fine leg, but this is too big a task for him as well",
    "clears front leg and lofts this length delivery cleanly over mid off",
    "shortish, the batsman bends, gets under it and hits it high in the air, clears the deep square leg boundary",
    "lashed over wide long off, the batsman gets a length ball, steps forward, bends a knee and hammers it high",
    "some much needed catching practice for the spectators...",
    "down the track, gets under the ball and wallops it high over deep midwicket",
    "that gets the crowd going! This was banged in a on a good length, the batsman was back at the crease and pulled it in front of square over deep midwicket",
    "the big hit! Tossed up on middle and leg, the batsman was on his knee and slogged it high over deep midwicket",
    "over long-off this time. Another little trip down the track and though it hit the bottom of the bat, it had enough to clear the fielder in the deep",
    "offers length and the batsman has pounced. He was down the track and belts it way into the crowd behind long-on",
    "short ball on off stump, he rocks back and smashes it way into the grass banks at cow corner",
    "lovely footwork as he leaves the crease to reach the pitch and a full swing of the arms brings up another straight six",
    "full tos outside off and he has crashed it over the man at deep cover. ",
    "again offers him room and the length to get under and the batsman needs no second invitation",
    "the batsman saw it early and hammers it over the square leg boundary.",
    "pummeled into the grass banks! It's short, it's on the leg stump and it's been pulled with the utmost authority. No point keeping it down when you can hit it that far",
    "Soars straight over the bowler's head as he gets forward to the overpitched delivery and just extends the arms from a forward defensive",
    "that's more like it! Shimmies down the track to get under the ball and launches it into the crowd behind long-on",
    "effortless swipe over the midwicket boundary",
    "goes fuller with that slower ball and he was expecting it this time. Stays still at the crease and whacks it over deep square leg",
    "picked it up and swats it over the deep midwicket boundary! It was length and he kept his front foot out of the way and muscled it.",
    "swiped into the crowd behind square leg! This was drifting into the pads and he gets down on one-knee and slog swept it powerfully",
    "Ensured his front foot was not in the way and an effortless whip of the wrists sends the ball beyond the square leg boundary",
    "peppers the sightscreen after skipping down the track.",
    "That has been launched into orbit ! We might as well bring a new ball right now...",
    "misses the mark with his length and the batsman gets under it and smacks it beyond the long-off boundary. Clean as a whistle",
    "mauled into the crowd behind deep midwicket! It was the slower ball and he'd picked it early and though the bat turned in his hands, it sailed past the ropes",
    "magnificent ! That ball had six written all over it !",
    "the bowler bowls a terrible long hop and the striker shuffles across and mauls it miles into the square leg boundary. Surely he would have enjoyed that. ",
    "away the ball goes goes. Flat, hard and just over the ropes. On leg stump and he swung for the fences",
    "Overpitched outside off and he waded into the shot and timed it perfectly",
    "outside leg stump and he's helped it on its way. Lands among the his teammates in the dug out and he has a big smile on his face while punching gloves with his non-striker",
    "and he's sent packing over long-on. Races down and gets to the pitch. Doesn't bother about where it's going and just launches it into the night sky",
    "a glorious shot over extra cover. Didn't get to the pitch as much as he would have liked, and had to sort of reach for it, but his timing was still top-notch",
    "long-on watches it clear his head and thud into the advertising boards. Pitches it up in his arc and a big back lift comes down in a thunderous swing",
    "terrible line from the bowler. On the pads and he's been swept miles into the boundary behind square leg. A batsman of such class against this kind of bowling is no contest at all.",
    "what a strike! It was short and afforded him enough room to upper cut it and he's put enough muscle into it to clear the ropes",
    "into orbit! Races down the track to pick it up off a length and deposit well into the crowd behind long-on. The batsman has done away with defensive strokes",
    "did that go all the way? This was bowled short and sat up nicely for the batsman to biff it over midwicket, the question was whether the ball hit the boundary cushion on the full or on the half volley, the on-field umpire asks the third umpire and after studying a few replays he calls it a six",
    " he top-edges it to Maddinson in the deep on the leg side"
];
caught=
[
    "",
    "played away from the body and he miscued it to long-off",
    "this was tossed up outside off and the batsman made room to carve that over cover, the fielder ran to his right at cover and took the catch easily at the edge of the circle",
    "straight to deep midwicket, the batsman attempts to slog that for a six over deep midwicket, fetches it from outside off, it went flat to the fielder,",
    "gets the line and length spot on this time! The away swinger gets him, swung away from the middle stump, the batsman was compelled to go for the drive, thick outside edge to the keeper",
    "made a lot of room and charged down the track looking to clear the off side, unfortunately he made too much room and the ball spooned off the bottom of the bat, the fielder ran backwards at mid-off and hung on on the dive just as the ball was leaving him, the fielder covered a lot of ground getting to the ball, amazing stuff",
    "has pulled off quite a stunner! The batsman looked to clear the straight boundary, it was high in the air and hes was running back from mid-off, the running catches are the toughest, hung on to it and fell backwards",
    "this time the fielder takes a terrific catch, the batsman has flopped, a length ball and he wanted to play that inside-out, bat turns as he plays that and the ball loops towards cover, the fielder has some ground to cover, he sprints to his left and pouches that one",
    "gets him with the slower ball, it was short and Jadeja swiveled and looked to pull it to fine leg, just shaved the face of the bat on the way to Karthik",
    "nearly spilled that! Slower ball and short, the batsman rocked back to pull and it was flat over square leg, the man in the deep ran to his left and grabbed at it, it popped out and he tried taking it in the second attempt and it slipped out again but he managed in the third attempt",
    "this was a length ball and the batsman made room to clear long-on, he closed the face of the bat as he made contact and hence didn't hit it well enough",
    "this was a length ball, the batsman stayed at the crease and looked to clear long-on, didn't get the distance, the fielder takes the skier well in front of the rope",
    "he mishits this full delivery, it goes straight and high, stays airborne for an age, but long on judges it neatly",
    "this is a sharp, tumbling take at deep backward square leg, the batsman swung a short of a length ball and teh fielder has not had to move much",
    "the batsman sees deep point, and he will take him on of course, slices this widish back of a length ball straight to the man.",
    "advances out to a flat one and lifts it straight into the hands of deep midwicket",
    "he slashes this short of a length ball in the air and straight to third man",
    "The bowler cranks it up on this ball, the batsman turns on one leg, trying to lift it over square leg, but he is not so lucky this time, loops straight to the man",
    "this is outside off now, the batsman gets down on his knee and swings, and inside-edges it into his stumps",
    "finds deep midwicket this time, it was shortish, angled in, right in the pulling zone, he swung it from outside the crease, and into the safe hands of long on",
    "and the plan has worked to perfection, he gets a back of a length ball down the pad, around hip height, tucks it fine instinctively, and there is a leg slip waiting to accept the gift",
    "terrific delivery, the bowler leaps as this one kicks from just back of a length around off, straightens on the batsman, he has to play at this, prods, and the thick edge flies low to widish slip",
    "Nothing behind this shot. Caught at long-on",
    "gets a touch too under a length ball, lofts this towards long-off where th fielder takes it overhead",
    "This is a slower-ball length ball hit wide of long-off, but the fielder makes so much ground he doesn't even have to dive.",
    "pitches this up on middle and leg, drilled to long-on where the fielder times his leap to perfection to take this overhead",
    "on a length, just outside off, he lazily drives into it. Makes no attempt to keep it down, nor is he trying to hit it out of the ground. Provides long-off a sitter.",
    "He is hurried into this shovel-pull. Mostly because the ball is not short enough, and he ends up slicing it to square leg",
    "he can't believe what he's done, he turns back to the umpire and waits for the crooked finger, this was pitched up on the off stump, just the right length, the batsman comes forward and there's a thick outside edge to the keeper, it was very obvious, the bowler waits and waits and the umpire does the rest",
    "that was a soft dismissal! This was a length ball outside off and the batsman looked to clear mid-off but it went off the bottom half of the bat and as a result it went rather tamely to mid-off",
    "finds the fielder at long-on, makes room and it's mistimed and it is taken at long-on",
    "This was a length ball and he made room to smash this over the off side, top edge and the keeper gets under the skier",
    "this was a friendly full tofss, whipped it straight to deep midwicket",
    "finds the man in the deep on the on side, this was a slower ball and bowled a bit short, Warner rocks back and pulls in front of square but finds the man at deep midwicket, went straight to him",
    "found the fielder with precision, the batsman was down on his knee to slog, played it flat and found the fielder at deep square leg",
    "that's a soft dismissal! But that wasn't a terribly good delivery either, this was short and wide outside off, the invitation was there for the cut but he could only hit it straight to the man at cover, didn't time it well and an easy catch in the end",
    "pushed through on middle and leg as he rocks back and goes for an almighty pull. Hasn't connected it properly and the fielder at deep midwicket takes a tumbling catch to break the opposition's partnership",
    " one slog too many for the batsman and he has to walk back dismissed off a full toss. Sought the wide yorker again but it ends up a lovely delivery to be smacked over the covers but he swung across the line and got a leading edge which is taken by the man in the covers",
    "scooped it straight into the hands of the man at short fine leg. It did not allow the batsman the pace he wanted. Walked right across his stumps to manufacture a big shot and perishes",
    "holes out at long-off !. Another full toss outside off but the batsman can't get the meaty part of the bat on this. Lofts it down the throat of the fielder",
    "safely taken! The batsman was lured into playing an expansive drive on the up and he was an age too early into the shot. Gets a leading edge and perishes in quite a tame fashion",
    "taken at long-off! This was full on middle and the batsman made a little room to blast it down the ground. Didn't get as much bat as he would have liked as the fielder rushes in and dives forward to pick up a neat, low catch! That was plucked inches off the ground.",
    "caught at the edge of the circle at cover! Fuller delivery on off stump and the batsman tries to force the pace by shoveling it over the infield. The ball was too full to get under as well as he would have liked.",
    "goes straight up in the air and the bowler himself takes the catch, albeit after a bit of a juggle. ",
    "what a soft dismissal, caught down the leg side! The captain high-fives his bowler. The batsman shuffled across to try and glance it fine but the ball, just short of a good length, runs off the face and the keeper collects another simple catch",
    "a shortish ball down the leg side, wasn't the most threatening delivery, the batsman wanted to pull that away, can only glove it away, easy catch for the keeper"
];
bowled=
[

    "was bowling round the wicket, the batsman made a lot of room early on looking to push it to the off side, he may have expected turn but it went straight through and knocked the middle stump",
    "skidded through and hit the stumps, the batsman was rooted to the crease, left a big gap",
    "right through him. The bowler nips this in a mile from just outside off, on a good length, he has moved across and set himself up for a forcing stroke, and there is no way he can account for so much movement, through the gate and into the stumps",
    "got him this time, slows it down a bit, gives it some air, the line is around off, the batsman is confused immediately, pushes weakly for some movement, there isn't any, and the stumps are rattled",
    "what a yorker! The batsman was so late on it and he throws a little look back at the stumps. That slingy action brought the ball back in at him and his jittery stay in the middle ends in the most emphatic fashion",
    "that stumps are in disarray again! Another fuller ball finds its mark. He was making room to try and open up the off side which made it all the more complicated for him to intervene with the ball's trajectory and off stump is knocked back",
    "castled! Skids on after pitching and sneaks through his bat and pad. The batsman's feet fail him once again as this one is pitched on a good length and deviates in at him. He looked all at sea trying to keep that out and by the time he played his shot the middle stump was knocked back",
    "off stump is knocked back !. The slog over midwicket fails again and this time it signals the end of his innings",
    " leg stump cartwheels! It was length and he was looking to slog it across the line seeking the stands at midwicket. Missed it by several inches as the ball sneaks between the bat and pad. The bowler exults!",
    "what a yorker! Leg stump has been uprooted. There was no room to maneouvre it, which was what he was trying to do with a bit of an open face but the ball just kept coming in at him and cramping him up. He also seemed a little surprised by the extra pace on that and walks off the field",
    "he telegraphs the slower ball with a change of action. The batsman slogs across the line of this delivery, and has his leg stump pegged back."
];
stumped=
[
    "",
    "The ball moved away from the batsman, beating his booming hoick in to the covers. The keeper does well to collect the ball behind the stumps, before ending this partnership. Smart keeping",
    "That is some effort by the opposition ! The keeper was standing up to the stumps, the batsman took the bait and charged out to an otherwise harmless delivery, and has lost his wicket in the process. Strange cricket this..."
];
    runout=
    [
        "",
        "fired this full on the stumps and the batsman drilled it down the pitch, the batsman had set off and had to quickly turn around, Shami back flicked it to the stumps and Ashwin was short, there was barely an appeal and nor did the umpire raise the finger, the batsman didn't wait and walk off, for a second we didn't know what was going on!",
        "That looked really tight from a certain distance, so the umpire has called for the big screen's help. The frame shows the batsman marginally out of this line, full credit to the fileder backing up at the right time to exact a dismissal.",
        "trouble here, there is a direct hit, superb work from the man at backward point, the batsman had walked too far down the pitch after getting hit on the thigh pad with an incoming ball, the fileder swooped on the ball and found him well short",
        "fuller, quicker, wants the leg-bye to point, but there is no run here. The runner has given up, and this time the throw doesn't miss"
    ];
    freehit=
    [
        "And we have a no-ball ! The dew has made the area around the popping crease quite slippery, and the bowler's front foot has snuck out just enough for a no-ball to be called. ",
        "Brilliant bowling, except for the fact that the bowler's front foot was miles out of the crease. No ball signalled by the umpire...",
        "Oh no! he has overstepped ! The batsman is all smiles, and why shouldn't he be ? It's free hit time..."
    ];
    lbw=
    [
        "And that has struck him in front ! The umpire doesn't have to spend a great deal of time on those, up goes the finger",
        "Pitched on middle and leg, the ball skidded through and went on straight, the batsman was trapped on the back foot and plumb in front",
        "The lack of pace accounts for him this time!",
        "Absolutely supreme ! The ball pitched just on the off stump line, moving that fraction of  a fraction inwards to flummox the batsman, who gets confused and offers no shot, only to find the umpire's raised finger, signalling his doom.",
        "what just happened here ? What would have otherwise been a straightforward delivery on middle stump has been made to look like a monster ball. The batsman tries a switch hit, only he manages to mess it up completely. The ball hit him low on the pads, he's a dead man.",
        "The umpire needed no technological assistance for this, it was as plumb as it can possibly be. Pitched on off stump, didn't bounce as much as the batsman would have liked, and he walks off with his tail between his legs.",
        "That's struck him in front ! The bowler is in ecstasy, doesn't even wait for the umpire's signal.",
        "that's gone, the bowler tries a reverse paddle, misses this big offspinner and is caught in front",
        "This bowler needs only balls to strike, he has the batsman lbw, it was a delayed appeal for lbw, that was a back of length ball around off stump, the batsman tries to whip that away, pad first, a bit of doubt over whether that would have hit off, the umpire is convinced though",
        "trapped in the crease and he has to trudge back. No doubt about this one. This came on and struck him on the back pad as he was looking to clip to midwicket. The ball skids on and he's a goner",
        " it's given! That's a pretty tight call from the umpire and the batsman walks back looking a little bemused. It pitched in line and went on with the arm as he went for a sweep. Struck low on the front pad and it might just have grazed off stump."
    ];
    wide=
    [
        "That is just criminal, to bowl deliveries like that in this format of the game. The batting team on the other hand, has no complaints",
        "he strays wide down the leg side",
        "that was way down the leg side, no mercy for that.",
        "that looked a little to close, but the line belongs to the umpire, wide called.",
        "he lost control of that! This was far too wide down the leg side and the wicketkeeper could do nothing",
        "wide, a little indiscipline fetches additional runs as this length ball goes down leg",
        "fires it down the leg side. Good take from the keeper. Moved with the ball and stayed low too",
        "That looked like it would have hit the thigh pad but the umpire reckons there was no contact. Back of a length down the leg side. He goes for the flick and has no success connecting",
        "terrible delivery as he bowls it well down the leg side. The batsman looks to help it away, but doesn't succeed",
        "short delivery that is just a shade down the leg side. That's rather harsh as the ball sailed over his hips as he was a little cramped up while attempting a shot"
    ];
console.log(dot.length,one.length,two.length,three.length,four.length,six.length,bowled.length,caught.length,lbw.length,stumped.length,runout.length,wide.length,freehit.length);